### PR TITLE
core: Move client-side decompressor selection to stream

### LINKED ISSUE #2157: Flaky CompressionTest
Found in https://travis-ci.org/grpc/grpc-java/jobs/151357545

```
io.grpc.testing.integration.CompressionTest > compression[23] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:369)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:217)
        Caused by:
        io.grpc.StatusRuntimeException: INTERNAL: Can't decode compressed frame as compression not configured.
```

### LINKED ISSUE #2865: Rare race condition in Client
While more prominent when using compression, this race occurs without it as well.  The typical race looks something like:

1.  Client starts and RPC
2.  The transport to the server is not yet available, so a DelayedClientTransport is used.
3.  The server handles the RPC and sends back headers and a compressed message.
4.  The client sees there are headers, and begins executing the queued stream callbacks, **on the channel executor threads** instead of the transport thread
5.  The client sees the Data frame, and tries to decompress it on the network thread.  *This fails since the headers from 4 have not yet been processed.
6.  The stream has already failed, but the queued callback for onHeaders() is finally executed on the app thread.  

This is the root cause of #2157.  As mentioned, this isn't just for compression.  ClientInterceptors will see headers *after* data has been received.   The solution (temporary?) seems to be to move OkHttp to used AbstractClientStream2 in #2821, and then move decompression from ClientCallImpl to the stream.  That will fix the decompression, but not interceptors.

### PR DESCRIPTION
**Pull request by ejona86**
Previously ClientCallImpl's stream listener would call
stream.setDecompressor(), but this has always been a bit strange as the
only case where the call listener calls the stream and forms a bit of a
loop. It also turned out to be racy in the presence of
DelayedClientStream since DelayedClientStream does not guarantee that
the listener has processed before returning.

Now we let the stream handle decompressor selection itself. Compressor
selection on client and server and decompressor selection on server
remain unchanged. Nothing prevents them from being changed, other than
it is currently unnecessary to fix the severe compressionTest flake.

Fixes #2865
Fixes #2157

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/AbstractClientStream.java [hunk 1]
```diff
@@ -218,6 +235,19 @@ protected final ClientStreamListener listener() {
     protected void inboundHeadersReceived(Metadata headers) {
       Preconditions.checkState(!statusReported, "Received headers on closed stream");
       statsTraceCtx.clientInboundHeaders();
+
+      Decompressor decompressor = Codec.Identity.NONE;
+      if (headers.containsKey(MESSAGE_ENCODING_KEY)) {
+        String encoding = headers.get(MESSAGE_ENCODING_KEY);
```
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/AbstractClientStream.java]: yikes, wanna combine this with the if?

File: core/src/main/java/io/grpc/internal/AbstractClientStream.java [hunk 2]
```diff
@@ -218,6 +235,19 @@ protected final ClientStreamListener listener() {
...
+        decompressor = decompressorRegistry.lookupDecompressor(encoding);
+        if (decompressor == null) {
+          deframeFailed(Status.INTERNAL.withDescription(
+              String.format("Can't find decompressor for %s", encoding)).asException());
```
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/AbstractClientStream.java]: RuntimeException() ?

File: core/src/main/java/io/grpc/internal/ClientStream.java [hunk 3]
```diff
@@ -52,6 +53,14 @@
   void setAuthority(String authority);
 
   /**
+   * Sets the registry to find a decompressor for the framer. May only be called before {@link
+   * #start}.
```
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/ClientStream.java]: Mention that this may be a noop, like for Inprocess.

File: core/src/main/java/io/grpc/internal/ServerStream.java [hunk 4]
```diff
@@ -59,6 +60,13 @@
   void cancel(Status status);
 
   /**
+   * Sets the decompressor on the deframer.
+   *
+   * @param decompressor the decompressor to use.
+   */
+  void setDecompressor(Decompressor decompressor);
```
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/ServerStream.java]: same comment about docs.

File: core/src/main/java/io/grpc/internal/AbstractClientStream.java (hunk 2 above)
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/AbstractClientStream.java]: `asRuntimeException()` produces identical behavior. The exception is thrown away and only the status is kept in all `deframeFailed()` handling. And `deframeFailed()` is also the only way the `TransportState` can kill the RPC.

File: core/src/main/java/io/grpc/internal/ClientStream.java (hunk 3 above)
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ClientStream.java]: Done

File: core/src/main/java/io/grpc/internal/ServerStream.java (hunk 4 above)
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ServerStream.java]: Done

File: core/src/main/java/io/grpc/internal/AbstractClientStream.java (hunk 2 above)
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/AbstractClientStream.java]: Done.

File: core/src/main/java/io/grpc/internal/AbstractClientStream.java (hunk 1 above)
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/AbstractClientStream.java]: Done.
