### PR TITLE
Fix flaky retry tests

### LINKED ISSUE #10873: interop-test, core: retryTest is flaky
```
> Task :grpc-interop-testing:test

io.grpc.testing.integration.RetryTest > statsRecorded FAILED
    java.lang.NullPointerException
        at io.grpc.testing.integration.RetryTest.assertRpcStatusRecorded(RetryTest.java:248)
        at io.grpc.testing.integration.RetryTest.statsRecorded(RetryTest.java:354)
```

cc. @larry-safran

### PR DESCRIPTION
**Pull request by larry-safran**
Fix retry tests that became flaky.  Fixes #10873

### CODE REVIEW

File: interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java [hunk 1]
```diff
@@ -103,8 +105,11 @@ public class RetryTest {
   @Rule
   public final GrpcCleanupRule cleanupRule = new GrpcCleanupRule();
   private final FakeClock fakeClock = new FakeClock();
-  @Mock
-  private ClientCall.Listener<Integer> mockCallListener;
+  private TestListener realMockCallListener = new TestListener();
```
Comment (temawi) [inline interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java:108]: I wouldn't use the word "mock" since it's not a mock object. Just `testCallListener` would do I think, or people ofthen use the term "fake" with these kinds of classes.

File: interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java [hunk 2]
```diff
@@ -169,6 +174,11 @@ public Listener<String> startCall(ServerCall<String, Integer> call, Metadata hea
   private Map<String, Object> retryPolicy = null;
   private long bufferLimit = 1L << 20; // 1M
 
+  @Before
+  public void setUp() throws Exception {
+  }
```
Comment (temawi) [inline interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java:179]: This can be removed, right?

Comment (larry-safran) [reply interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java]: removed.

File: interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java (hunk 1 above)
Comment (larry-safran) [reply interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java]: changed to testCallListener

File: core/src/main/java/io/grpc/internal/AbstractClientStream.java [hunk 3]
```diff
@@ -455,10 +455,10 @@ private void closeListener(
       if (!listenerClosed) {
         listenerClosed = true;
         statsTraceCtx.streamClosed(status);
-        listener().closed(status, rpcProgress, trailers);
         if (getTransportTracer() != null) {
           getTransportTracer().reportStreamClosed(status.isOk());
         }
+        listener().closed(status, rpcProgress, trailers);
```
Comment (YifeiZhuang) [inline core/src/main/java/io/grpc/internal/AbstractClientStream.java:461]: You switched the order of the the listener and transportTracer.
The original tests is about verifying census stats(in statsTraceCtx), how does that related to transportTracer?

**Comment by larry-safran** [comment]
The test is checking the stats which get set in the tracer.  It is waiting
for the closed to be called to make the check, but when the closed method
is called before the tracer report is generated there is a window where the
report isn't available, which is what caused the failures.

**Comment by YifeiZhuang** [comment]
> when the closed method is called before the tracer report is generated there is a window where the report isn't available, which is what caused the failures.

hmm, I had a theory about why the call closed method is called before those reports I put on the issue.

**Comment by larry-safran** [comment]
Your delay masked the window.

**Review by temawi — APPROVED** [review]
I don't have enough understanding of the original problem to know if @YifeiZhuang's concern here is warranted, but if she is ok with the change it LGTM.

**Comment by YifeiZhuang** [comment]
I agree that the test setup caused the flakiness, not a real problem. One thing to keep in mind: when canceling the retryable stream returns and close and master listener, all the substreams should have been closed already. Because notifying master listener is the last thing we should do in retryable stream. Otherwise there will be resource leak, e.g. RejectedExecutionException. 
But I don't see the fix address that problem. In the current fix, the master listener may still happen before the substream listener is closed. It might mitigate the flakiness, but I'm not yet convinced this is the appropriate fix. 
cc. @ejona86
