### PR TITLE
core: remember last pick status in no real stream

### LINKED ISSUE #10749: stub.withWaitForReady()'s DEADLINE_EXECEEDED lacks connection failure information
```java
try {
  stub.withWaitForReady().withDeadline().hello();
} catch(StatusRuntimeException e) {
  // always receiving DEADLINE_EXCEEDED as status code if server is unavailable or client certs are invalid
}
```

There is no way to distinguish the underlying cause of failure , say if the failure is due to SSLHanshake or server genuinely not being available.

As an alternative, without using withWaitForReady() we are receiving UNAVAILABLE code in StatusRuntimeException which wraps the underlying cause say for example the SSLHandshake exception. Looking at the UNAVAILABLE code how can we safely take a call if we to reattempt connection, as we do not want to reattempt the connection in SSLException scenarios?

### PR DESCRIPTION
**Pull request by shivaspeaks**
fixes #10749

### CODE REVIEW

**Review by kannanjgithub — APPROVED** [review]

File: core/src/main/java/io/grpc/internal/DelayedStream.java [hunk 1]
```diff
@@ -63,6 +63,7 @@ class DelayedStream implements ClientStream {
   private long streamSetTimeNanos;
   // No need to synchronize; start() synchronization provides a happens-before
   private List<Runnable> preStartPendingCalls = new ArrayList<>();
+  protected Status lastPickStatus;
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/DelayedStream.java:66]: Put this in `PendingStream`, as it is specific to wait-for-ready which is specific to DelayedClientTransport. Also, let's only show it when the RPC is wait-for-ready, as that's the only case that there could be an error status and it wasn't used. In fact, if the status isn't an error, let's not show it for wait-for-ready either.

File: core/src/main/java/io/grpc/internal/DelayedClientTransport.java [hunk 2]
```diff
@@ -286,6 +286,9 @@ final void reprocess(@Nullable SubchannelPicker picker) {
 
     for (final PendingStream stream : toProcess) {
       PickResult pickResult = picker.pickSubchannel(stream.args);
+      if (!pickResult.hasResult()) {
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/DelayedClientTransport.java:289]: This is inverted; status is always OK when there isn't a result. Add a test to confirm the behavior.

File: core/src/main/java/io/grpc/internal/DelayedStream.java [hunk 3]
```diff
@@ -109,6 +110,7 @@ public void appendTimeoutInsight(InsightBuilder insight) {
       } else {
         insight.appendKeyValue("buffered_nanos", System.nanoTime() - startTimeNanos);
         insight.append("waiting_for_connection");
+        insight.append(lastPickStatus);
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/DelayedStream.java:113]: There's no context here. It won't be clear what this means. Add a key to describe it.

File: core/src/main/java/io/grpc/internal/DelayedClientTransport.java [hunk 4]
```diff
@@ -286,6 +286,9 @@ final void reprocess(@Nullable SubchannelPicker picker) {
 
     for (final PendingStream stream : toProcess) {
       PickResult pickResult = picker.pickSubchannel(stream.args);
+      if (pickResult.hasResult()) {
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/DelayedClientTransport.java:289]: This code is needed in newStream() as well. Let's only run it when `callOptions.isWaitForReady()` is true as well.

File: core/src/main/java/io/grpc/internal/DelayedClientTransport.java [hunk 5]
```diff
@@ -347,6 +350,7 @@ private class PendingStream extends DelayedStream {
     private final PickSubchannelArgs args;
     private final Context context = Context.current();
     private final ClientStreamTracer[] tracers;
+    private Status lastPickStatus;
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/DelayedClientTransport.java:353]: This is accessed from multiple threads (pick attempts are single-threaded, but appendTimeoutInsight is a separate thread). I see the parent class DelayedStream is using `this` as a lock, and PendingStream could do the same for this variable.

Comment (ejona86) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java:363]: It still has synchronization problems. One assignment uses DelayedClientTransport.lock, another uses no lock, and a read uses PendingStream.this. To be useful, you have to use the same lock in all reads/writes.

Comment (shivaspeaks) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java:363]: I definitely cannot synchronize on local variable having references. That doesn't work. I cannot define a new lock at the top because then that will be blocking every stream. We need lock per pending stream.

Comment (shivaspeaks) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java]: @ejona86 I believe AtomicReference to store Status is viable here. I made a commit, take a look.

Comment (kannanjgithub) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java]: Before worrying about the  synchronization problem, there is a bigger problem. The PR doesn't help with the case of transport not established at all, and control will go beyond GrpcUtil.getTransportFromPickResult != null. 
Even if we didn't gate on the condition on transport != null ,pick result won't capture the transport status returned to the [listener](https://github.com/grpc/grpc-java/blob/b1bc0a9d240c2cc6ccf9cf02543c9d9118132c14/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L608) so (last) pick result will just be OK even when the picked sub channel fails to connect.

Comment (ejona86) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java]: The current rough approach seems fine to me. What you may not notice is `getTransportFromPickResult()` [is wait-for-ready-aware](https://github.com/grpc/grpc-java/blob/199a7ea3e828fc0fc4ce0de48666b222bb22218d/core/src/main/java/io/grpc/internal/GrpcUtil.java#L750) and queues if the RPC is wait-for-ready. What we want to do here is see the error that the RPC _would_ have failed with if it wasn't wait-for-ready.

Since we're dealing with RPCs here, there must be _no_ involvement with subchannel listeners. The LBs are responsible for that, and we don't know which subchannel is relevant. We need the LB to tell us if there is an error, which it does via the pick result.

When reviewing this earlier I saw that the flows can be simplified now that getTransportFromPickResult() is only used in one class (prior to 8844cf7b8 ManagedChannelImpl also used it). But I wanted to wait until this PR was merged before making such changes.

File: core/src/main/java/io/grpc/internal/DelayedClientTransport.java [hunk 6]
```diff
@@ -293,6 +298,15 @@ final void reprocess(@Nullable SubchannelPicker picker) {
     for (final PendingStream stream : toProcess) {
       PickResult pickResult = picker.pickSubchannel(stream.args);
       CallOptions callOptions = stream.args.getCallOptions();
+      synchronized (lock) {
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/DelayedClientTransport.java:301]: There's only one writing thread, so the lock here doesn't do much. This path happens much more often than `appendTimeoutInsight()`; it is weird to use a lock here but an atomic for reading. That works great when something is read more often than written, but here we are writing more often than reading. This is also acquiring the lock when unnecessary, as callOptions and pickResult don't need any lock protection.

Note that the AtomicReference could have been a basic `volatile`; you are only using get/set which are just normal reading and writing to a volatile.

`lock` is shared for RPCs across the channel, and we have access to `stream` already which is its own lock (DelayedStream uses `synchronized (this)`). So `stream` would be a better lock to use.

I see two easy possibilities:
 * Use only a lock. Synchronize on `stream` here/`this` in `appendTimeoutInsight()`. You'd mark `lastPickStatus` with `@GuardedBy("this")`. This would be perfect if we could combine it with nearby code. `DelayedStream.appendTimeoutInsight()` actually already grabs the lock, but it is generally hard to make that work nicely across classes. And in this method `transport == null` (which is the result for failing picks for wait-for-ready RPCs) is the time the lock _isn't_ acquired (by `stream.createRealStream()`)
 * Use only a volatile. Make `lastPickStatus` and don't do anything special when assigning to it. This is really, really easy in this case. The main thing to watch out for is things can get complicated when you have many independent volatiles. That's not really a problem here.

Comment (ejona86) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java:301]: (I see that using "lock" is convenient for the initial pick. That was a fair reason to consider it.)

File: core/src/main/java/io/grpc/internal/DelayedClientTransport.java [hunk 7]
```diff
@@ -293,6 +297,13 @@ final void reprocess(@Nullable SubchannelPicker picker) {
     for (final PendingStream stream : toProcess) {
       PickResult pickResult = picker.pickSubchannel(stream.args);
       CallOptions callOptions = stream.args.getCallOptions();
+      if (callOptions.isWaitForReady() && pickResult.hasResult()) {
+        stream.lastPickStatus = pickResult.getStatus();
+      }
+      // User code provided authority takes precedence over the LB provided one.
+      if (callOptions.getAuthority() == null && pickResult.getAuthorityOverride() != null) {
+        stream.setAuthority(pickResult.getAuthorityOverride());
```
Comment (kannanjgithub) [inline core/src/main/java/io/grpc/internal/DelayedClientTransport.java:305]: How did these lines come about (looks like an incorrect merge)? This undoes the change done in https://github.com/grpc/grpc-java/pull/11862/files.

Comment (shivaspeaks) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java:305]: Yes you're right. Somehow merge branch master into this branch caused it to happen.

**Review by kannanjgithub — APPROVED** [review]

**Review by ejona86 — APPROVED** [review]
