### PR TITLE
core: Use lazy message formatting in checkState

### LINKED ISSUE #12134: Performance Concern in grpc-java: Unnecessary Stack Trace Computation
Hi,

In the following code snippet:
[InternalSubchannel.java](https://github.com/grpc/grpc-java/blob/1fd29bc804d0820a8f72c061bd671811adf85546/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L349C10-L349C61
) the log message string is built even if it is not ultimately used.

The toString() method of ConnectivityStateInfo calls toString() on the Status object. If the Status contains an exception, its stack trace is computed via getStackTrace().

In our usage of gRPC—where we enforce retries to many servers, some of which may be down—this stack trace computation shows up in our profiler and accounts for a few percent of CPU usage.

Thank you,
Marc Guiot

### PR DESCRIPTION
**Pull request by shivaspeaks**
Fixes #12134

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/InternalSubchannel.java [hunk 1]
```diff
@@ -345,8 +345,9 @@ private void gotoState(final ConnectivityStateInfo newState) {
     syncContext.throwIfNotInThisSynchronizationContext();
 
     if (state.getState() != newState.getState()) {
-      Preconditions.checkState(state.getState() != SHUTDOWN,
-          "Cannot transition out of SHUTDOWN to " + newState);
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/InternalSubchannel.java]: The conventional way to solve this is to use the message template:
```java
      Preconditions.checkState(state.getState() != SHUTDOWN,
          "Cannot transition out of SHUTDOWN to %s", newState);
```

In addition, we can also consider using `newState.getState()` in the error message, as it looks like a bug that the full state info was included.
