### PR TITLE
Fix issue: grpc-previous-rpc-attempts not added to initial response metadata

### LINKED ISSUE #9641: grpc-previous-rpc-attempts not added to initial response metadata
RetriableStream should add `grpc-previous-rpc-attempts` to the response headers (or trailers for trailers-only) when committing a stream and a retry was performed.

From [the gRFC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#exposed-retry-metadata):
> the client will receive the number of retry attempts made when receiving the results of an RPC.

### PR DESCRIPTION
**Pull request by pandaapo**
Fixes #9641

Add `grpc-previous-rpc-attempts` to headers when response metadata is initialized.

### CODE REVIEW

**Comment by sanjaypujare** [comment]
You will have to [sign the CLA](https://github.com/grpc/grpc-java/pull/9686#issuecomment-1311051382) before we can consider this PR

**Comment by sanjaypujare** [comment]
How does it fix https://github.com/grpc/grpc-java/issues/9641 ? That issue talks about adding `grpc-previous-rpc-attempts` to the response headers (i.e. to ServerStreams) whereas this makes a small enhancement to the ClientStream when `previousAttemptCount` is 0.

**Comment by sanjaypujare** [comment]
> > How does it fix #9641 ? That issue talks about adding `grpc-previous-rpc-attempts` to the response headers (i.e. to ServerStreams) whereas this makes a small enhancement to the ClientStream when `previousAttemptCount` is 0.
> 
> I misunderstood the author's intention. I tried to fix it again.

I have sought clarification in https://github.com/grpc/grpc-java/issues/9641#issuecomment-1319304654 . I think @ejona86 was suggesting  adding`grpc-previous-rpc-attempts` to response headers within `RetriableStream` and not `ServerStream` as I had suggested earlier. Not sure what other languages do (if they do) and what the intent was in the [gRFC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#exposed-retry-metadata) since "Likewise, the client will receive the number of retry attempts made when receiving the results of an RPC" is kind of ambiguous although one would think it implies "the client will receive ... from server"

File: stub/src/main/java/io/grpc/stub/ServerCalls.java [hunk 1]
```diff
@@ -38,6 +38,9 @@ public final class ServerCalls {
   @VisibleForTesting
   static final String MISSING_REQUEST = "Half-closed without a request";
 
+  static final Metadata.Key<String> GRPC_PREVIOUS_RPC_ATTEMPTS =
```
Comment (sanjaypujare) [inline stub/src/main/java/io/grpc/stub/ServerCalls.java:41]: It will be nice to have a single definition shared with `RetriableStream` . The current one `RetriableStream.GRPC_PREVIOUS_RPC_ATTEMPTS` can be moved up to the common base class `Stream` then we can eliminate this?

File: stub/src/main/java/io/grpc/stub/ServerCalls.java [hunk 2]
```diff
@@ -126,8 +129,12 @@ public ServerCall.Listener<ReqT> startCall(ServerCall<ReqT, RespT> call, Metadat
       Preconditions.checkArgument(
           call.getMethodDescriptor().getType().clientSendsOneMessage(),
           "asyncUnaryRequestCall is only for clientSendsOneMessage methods");
+      String preRpcAttempts = null;
+      if (headers.containsKey(GRPC_PREVIOUS_RPC_ATTEMPTS)) {
```
Comment (sanjaypujare) [inline stub/src/main/java/io/grpc/stub/ServerCalls.java:133]: Why do we need this check? `get` returns null if not present, so why can't we do :

```
String preRpcAttempts = headers.get(GRPC_PREVIOUS_RPC_ATTEMPTS);
```

File: stub/src/main/java/io/grpc/stub/ServerCalls.java [hunk 3]
```diff
@@ -126,8 +129,12 @@ public ServerCall.Listener<ReqT> startCall(ServerCall<ReqT, RespT> call, Metadat
       Preconditions.checkArgument(
           call.getMethodDescriptor().getType().clientSendsOneMessage(),
           "asyncUnaryRequestCall is only for clientSendsOneMessage methods");
+      String preRpcAttempts = null;
```
Comment (sanjaypujare) [inline stub/src/main/java/io/grpc/stub/ServerCalls.java:132]: `previousRpcAttempts` (or at least `prevRpcAttempts`) as a name is much better than `preRpcAttempts` since pre as a short form of previous is not common

**Review by sanjaypujare — CHANGES_REQUESTED** [review]
There is not test case to test the added functionality. That will need to be there. Also added a few comments.

**Comment by ejona86** [comment]
> Not sure what other languages do (if they do) and what the intent was in the gRFC since

The intent was client-only, where the client library injects the value for the client application to see. Yes, it is strange. But that's what it is, since there are few ways for the library to communicate with the application.

**Comment by sanjaypujare** [comment]
In that case @pandaapo you will have to change this PR to add the trailer in `RetriableStream` on the response side. Also since the information is locally available you don't need to parse the request headers like in case of `ServerCalls` implementation. Pls make sure to add a test case

File: core/src/test/java/io/grpc/internal/RetriableStreamTest.java [hunk 4]
```diff
@@ -991,6 +991,34 @@ public void messageAvailable() {
...
+    ClientStream mockStream2 = mock(ClientStream.class);
+    doReturn(mockStream2).when(retriableStreamRecorder).newSubstream(1);
+    sublistenerCaptor1.getValue().closed(
+            Status.fromCode(RETRIABLE_STATUS_CODE_1), PROCESSED, new Metadata());
+    fakeClock.forwardTime((long) (INITIAL_BACKOFF_IN_SECONDS * FAKE_RANDOM), TimeUnit.SECONDS);
+
+    ArgumentCaptor<ClientStreamListener> sublistenerCaptor2 =
+            ArgumentCaptor.forClass(ClientStreamListener.class);
+    verify(mockStream2).start(sublistenerCaptor2.capture());
+    sublistenerCaptor2.getValue().headersRead(new Metadata());
```
Comment (sanjaypujare) [inline core/src/test/java/io/grpc/internal/RetriableStreamTest.java:1015]: I don't know if we need these additional lines or if the test needs to be so complicated e.g. 3 `start()` calls and 2 `headersRead` calls. What do these lines achieve?

File: core/src/test/java/io/grpc/internal/RetriableStreamTest.java [hunk 5]
```diff
@@ -991,6 +991,34 @@ public void messageAvailable() {
     verify(masterListener).messagesAvailable(messageProducer);
   }
 
+  @Test
+  public void addPrevRetryAttemptsToRespHeaders() {
```
Comment (sanjaypujare) [inline core/src/test/java/io/grpc/internal/RetriableStreamTest.java:995]: Do we need another test to verify there is no `GRPC_PREVIOUS_RPC_ATTEMPTS` header on the response of the very first attempt (since the gRFC says for the value of 0 there doesn't need  to be or shound't be that header)?

File: core/src/main/java/io/grpc/internal/RetriableStream.java [hunk 6]
```diff
@@ -817,6 +817,7 @@ private final class Sublistener implements ClientStreamListener {
 
     @Override
     public void headersRead(final Metadata headers) {
+      headers.put(GRPC_PREVIOUS_RPC_ATTEMPTS, String.valueOf(substream.previousAttemptCount));
```
Comment (sanjaypujare) [inline core/src/main/java/io/grpc/internal/RetriableStream.java:820]: Do you want to do this conditionally only if `substream.previousAttemptCount > 0` ?

File: core/src/main/java/io/grpc/internal/RetriableStream.java [hunk 7]
```diff
@@ -817,6 +817,9 @@ private final class Sublistener implements ClientStreamListener {
 
     @Override
     public void headersRead(final Metadata headers) {
+      if (substream.previousAttemptCount > 0) {
+        headers.put(GRPC_PREVIOUS_RPC_ATTEMPTS, String.valueOf(substream.previousAttemptCount));
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/RetriableStream.java:821]: To avoid confusion, do a `headers.discardAll(GRPC_PREVIOUS_RPC_ATTEMPTS)` just before this.

Comment (sanjaypujare) [reply core/src/main/java/io/grpc/internal/RetriableStream.java:821]: After doing this you can also enhance the test to make sure there is only one value for the key `"grpc-previous-rpc-attempts" . See below

File: core/src/test/java/io/grpc/internal/RetriableStreamTest.java [hunk 8]
```diff
@@ -991,6 +991,53 @@ public void messageAvailable() {
...
+    ClientStream mockStream2 = mock(ClientStream.class);
+    doReturn(mockStream2).when(retriableStreamRecorder).newSubstream(1);
+    sublistenerCaptor1.getValue().closed(
+            Status.fromCode(RETRIABLE_STATUS_CODE_1), PROCESSED, new Metadata());
+    fakeClock.forwardTime((long) (INITIAL_BACKOFF_IN_SECONDS * FAKE_RANDOM), TimeUnit.SECONDS);
+
+    ArgumentCaptor<ClientStreamListener> sublistenerCaptor2 =
+            ArgumentCaptor.forClass(ClientStreamListener.class);
+    verify(mockStream2).start(sublistenerCaptor2.capture());
+    sublistenerCaptor2.getValue().headersRead(new Metadata());
```
Comment (sanjaypujare) [inline core/src/test/java/io/grpc/internal/RetriableStreamTest.java:1034]: Instead of this how about:

```
    Metadata headers = new Metadata();
    headers.put(GRPC_PREVIOUS_RPC_ATTEMPTS, "3");
    sublistenerCaptor2.getValue().headersRead(headers);
    Iterable<String > iterable = headers.getAll(GRPC_PREVIOUS_RPC_ATTEMPTS);
   // make sure iterable has only 1 element and it is "1"
```

File: core/src/test/java/io/grpc/internal/RetriableStreamTest.java [hunk 9]
```diff
@@ -991,6 +991,53 @@ public void messageAvailable() {
...
+
+    ArgumentCaptor<Metadata> metadataCaptor = ArgumentCaptor.forClass(Metadata.class);
+    verify(masterListener).headersRead(metadataCaptor.capture());
+    assertEquals("1", metadataCaptor.getValue().get(GRPC_PREVIOUS_RPC_ATTEMPTS));
```
Comment (sanjaypujare) [inline core/src/test/java/io/grpc/internal/RetriableStreamTest.java:1038]: Similar to above, use `getAll(GRPC_PREVIOUS_RPC_ATTEMPTS)` instead of `get(GRPC_PREVIOUS_RPC_ATTEMPTS)` and verify only one element with value "1"?

Or alternatively you can verify that `metadataCaptor.getValue()` is the same value (reference) as `headers` passed to `sublistenerCaptor2.getValue().headersRead()` in my suggested code addition.

**Review by sanjaypujare — APPROVED** [review]
LGTM

**Comment by sanjaypujare** [comment]
@ejona86 do you need to approve as well?

**Comment by sanjaypujare** [comment]
@ejona86 you also need to approve it before we merge it?

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
Thank you!
