### PR TITLE
Fix javadoc, and remove deprecated OperationException classes

### LINKED ISSUE #750: Remove  Status.OperationRuntimeException and Status.OperationException
These are deprecated in favor of StatusException and StatusRuntimeException

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #750 and #752

### CODE REVIEW

File: core/src/main/java/io/grpc/Status.java [hunk 1]
```diff
@@ -324,17 +324,17 @@ public static Status fromCodeValue(int codeValue) {
    */
   public static Status fromThrowable(Throwable t) {
     for (Throwable cause : Throwables.getCausalChain(t)) {
-      if (cause instanceof OperationException) {
-        return ((Status.OperationException) cause).getStatus();
-      } else if (cause instanceof  OperationRuntimeException) {
-        return ((Status.OperationRuntimeException) cause).getStatus();
+      if (cause instanceof StatusException) {
+        return ((StatusException) cause).getStatus();
+      } else if (cause instanceof StatusRuntimeException) {
```
Comment (ejona86) [inline core/src/main/java/io/grpc/Status.java]: I've been waiting for this, just so that double-space gets removed :)

File: core/src/main/java/io/grpc/Status.java [hunk 2]
```diff
@@ -421,7 +421,7 @@ public boolean isOk() {
   }
 
   /**
-   * Convert this {@link Status} to a {@link RuntimeException}. Use {@code #fromThrowable}
+   * Convert this {@link Status} to a {@link RuntimeException}. Use {@link #fromThrowable}
```
Comment (ejona86) [inline core/src/main/java/io/grpc/Status.java]: Ditto for `asException`?

File: core/src/main/java/io/grpc/Status.java (hunk 1 above)
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/Status.java]: Feels good right?   Usually java style would nag about this.

File: core/src/main/java/io/grpc/Status.java (hunk 2 above)
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/Status.java]: Done.

File: core/src/main/java/io/grpc/Status.java [hunk 3]
```diff
@@ -44,7 +44,7 @@
 
 /**
  * Defines the status of an operation by providing a standard {@link Code} in conjunction with an
- * optional descriptive message. Instances of {@code Status} are created by starting with the
+ * optional descriptive message. Instances of {@link Status} are created by starting with the
```
Comment (ejona86) [inline core/src/main/java/io/grpc/Status.java]: I do think this one was on purpose, because it being a @ link adds no value and in a way is just blue-link noise.

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM, but with one comment about a @ link that was intended to be a @ code.
