### PR TITLE
Treat ClosedChannelException as UNAVAILABLE to squelch test failures

### LINKED ISSUE #1513: TlsTest flakiness
Found on Travis linux when testing for #1508
```
io.grpc.testing.integration.TlsTest > noClientAuthFailure[OPENSSL] FAILED
    java.lang.AssertionError: expected:<UNAVAILABLE> but was:<UNKNOWN>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.testing.integration.TlsTest.noClientAuthFailure(TlsTest.java:235)
```

### PR DESCRIPTION
**Pull request by ejona86**
Our tests are detecting cases where we are still getting
ClosedChannelException. We need to fix that because it is a useless
status, but until it is fixed we want a stable CI.

Fixes #1513 and NettyTransportTest.serverNotListening failures

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/Utils.java [hunk 1]
```diff
@@ -168,7 +168,10 @@ public static Status statusFromThrowable(Throwable t) {
     if (s.getCode() != Status.Code.UNKNOWN) {
       return s;
     }
-    if (t instanceof ClosedChannelException) {
+    // TODO(ejona): reenable once startup rances are resolved; ClosedChannelException is being seen
```
Comment (carl-mastrangelo) [inline netty/src/main/java/io/grpc/netty/Utils.java]: races

**Comment by carl-mastrangelo** [comment]
LGTM
