### PR TITLE
okhttp: don't crash if receive window_update for an non-exit stream which may have existed.

### LINKED ISSUE #441: WINDOW_UPDATE for unknown streams causes exception
As discovered by @madongfly. It is very easy to get a WINDOW_UPDATE for an unknown stream. For instance, if we sent RST_STREAM and there is a WINDOW_UPDATE en route from the server already.

https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java#L97

It seems we should just ignore such WINDOW_UPDATES instead.

### PR DESCRIPTION
**Pull request by madongfly**
Just ignore it.

This fixes #441

@ejona86

### CODE REVIEW

File: okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java [hunk 1]
```diff
@@ -476,6 +485,9 @@ public void run() {
         }
       } catch (IOException ioe) {
         abort(ioe);
+      } catch (RuntimeException e) {
```
Comment (ejona86) [inline okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java]: Just catch all Exceptions or Throwables?

File: okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java [hunk 2]
```diff
@@ -476,6 +485,9 @@ public void run() {
...
+        abort(e);
+        throw e;
```
Comment (ejona86) [inline okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java]: This does a log+throw. You should generally only log or only throw (like is being done for the IOException catch).

File: okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java [hunk 3]
```diff
@@ -94,13 +94,15 @@ synchronized void windowUpdate(int streamId, int delta) {
       writeStreams();
     } else {
       // Update the stream window and write any pending frames for the stream.
-      OutboundFlowState state = stateOrFail(streamId);
-      state.incrementStreamWindow(delta);
+      OutboundFlowState state = stateOrFailStranger(streamId);
```
Comment (ejona86) [inline okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java]: I don't like the idea of us throwing an exception like this. The approach in #443 is much better.

**Comment by madongfly** [comment]
@ejona86, rebased on top of #442, PTAL, thanks!

File: okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java [hunk 4]
```diff
@@ -94,24 +95,36 @@ synchronized void windowUpdate(int streamId, int delta) {
...
+
+    OutboundFlowState state = state(streamId);
+    if (state == null) {
+      // This is possible for a stream that has received end-of-stream from server (but hasn't sent
+      // end-of-stream), and was removed from the transport stream map.
+      // In such case, we just throw away the data.
+      return;
     }
 
-    OutboundFlowState state = stateOrFail(streamId);
```
Comment (ejona86) [inline okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java]: This was fine, since the transport is guaranteeing that the stream exists, right?

File: okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java [hunk 5]
```diff
@@ -94,24 +95,36 @@ synchronized void windowUpdate(int streamId, int delta) {
       writeStreams();
     } else {
       // Update the stream window and write any pending frames for the stream.
-      OutboundFlowState state = stateOrFail(streamId);
-      state.incrementStreamWindow(delta);
+      OutboundFlowState state = state(streamId);
+      if (state != null) {
```
Comment (ejona86) [inline okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java]: Can we move this check to the transport, like we are doing for DATA frames?

File: okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java (hunk 4 above)
Comment (madongfly) [inline okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java]: No, this is called by OkHttpClientStream (https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java#L179) for outbound messages, the stream might be removed as I described in the comment.

File: okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java (hunk 5 above)
Comment (madongfly) [inline okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java]: Done.

**Comment by madongfly** [comment]
@ejona86 PTAL, thanks!

**Comment by ejona86** [comment]
@madongfly LGTM
