### PR TITLE
test:Report the values that were compared rather than the underlying durat…

### LINKED ISSUE #6757: CallOptionsTest is flaky
https://travis-ci.org/grpc/grpc-java/jobs/655139606?utm_medium=notification&utm_source=github_status (java8)

```
io.grpc.CallOptionsTest > withDeadlineAfter FAILED
    expected               : 59.983802256s from now
    but was                : 59.983668916s from now
    outside tolerance in ns: 10000000
        at io.grpc.CallOptionsTest.withDeadlineAfter(CallOptionsTest.java:140)
```

i've seen this more than one time.

### PR DESCRIPTION
**Pull request by larry-safran**
Eliminate usage of BigInteger as its usage could lead to flakiness due to potential class loading issues and it is completely unnecessary.

Report the values that were compared rather than the underlying durations that generated those values and continue to change over time.

CallOptionsTest.withDeadlineAfter frequently fails even though the reported values seem to be within the specified delta.  Having the reported values differ from what is actually compared is confusing.

Fixes #6757

### CODE REVIEW

File: context/src/test/java/io/grpc/testing/DeadlineSubject.java [hunk 1]
```diff
@@ -65,9 +66,9 @@ public void of(Deadline expected) {
         BigInteger deltaNanos = BigInteger.valueOf(timeUnit.toNanos(delta));
         if (actualTimeRemaining.subtract(expectedTimeRemaining).abs().compareTo(deltaNanos) > 0) {
           failWithoutActual(
-              fact("expected", expected),
-              fact("but was", actual),
-              fact("outside tolerance in ns", deltaNanos));
+              fact("expected", expectedTimeRemaining.doubleValue() / SECONDS.toNanos(1)),
```
Comment (sergiitk) [inline context/src/test/java/io/grpc/testing/DeadlineSubject.java:69]: Why delete by one nanosecond? Would `TimeUnit.convert(expectedTimeRemaining.doubleValue(), TimeUnit.NANOSECONDS)` work?

**Comment by larry-safran** [comment]
It was previously reporting in seconds which I think really is the most
readable.  Since the BigInteger values were in nanoseconds, I wanted to
continue displaying seconds.

File: context/src/test/java/io/grpc/testing/DeadlineSubject.java (hunk 1 above)
Comment (sergiitk) [reply context/src/test/java/io/grpc/testing/DeadlineSubject.java:69]: Discussed IRL. All good.

**Review by sergiitk — APPROVED** [review]
