### PR TITLE
Fix for reconnecting when Android app comes to the foreground

### LINKED ISSUE #8850: AndroidChannel fails to reconnect after block
I'm having issues with Firestore (which uses gRPC) not connecting after a device is locked and was able to track it down to here.

https://github.com/grpc/grpc-java/blob/a35336c15fe3235b14a16af117515e113c8d5cee/android/src/main/java/io/grpc/android/AndroidChannelBuilder.java#L297

It seems that the network callback needs to override the onBlockedStatusChanged() function and reconnect when the blocked parameter is false.

I'm seeing onAvailable() only called when my app initially starts but onBlockedStatusChanged() is called with true when it has been idle for a while and false when it comes back up. This was tested on Android 12.

### PR DESCRIPTION
**Pull request by litclimbing**
When an app goes to the background, onBlockedStatusChanged is called with true and then called with false when it comes back to the foreground. The function onAvailable isn't called in this case and the connection wasn't being reset. Closes #8850

I noticed the comment that this is used for API versions 24+ but onBlockedStatusChanged was added in 29. I'm not sure if some kind of guard needs to be added or not. 
https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onBlockedStatusChanged(android.net.Network,%20boolean)

### CODE REVIEW

File: android/src/main/java/io/grpc/android/AndroidChannelBuilder.java [hunk 1]
```diff
@@ -297,6 +297,11 @@ public void enterIdle() {
       public void onAvailable(Network network) {
         delegate.enterIdle();
       }
+      @Override
```
Comment (dapengzhang0) [inline android/src/main/java/io/grpc/android/AndroidChannelBuilder.java:300]: I'm not sure how `@TargetApi` works but probably we need to define and register a separate filter for API level 29+

```
/** Respond to changes in the default network. Only used on API levels 29+. */
@TargetApi(Build.VERSION_CODES.Q)
private class BlockStatusChangedCallback extends ConnectivityManager.NetworkCallback {
```

Comment (ejona86) [reply android/src/main/java/io/grpc/android/AndroidChannelBuilder.java:300]: Well, I think `@Override` is the only thing that would break if `onBlockedStatusChanged()` is not present in the base class. So this code may "just work" on older android versions.

Comment (larssn) [reply android/src/main/java/io/grpc/android/AndroidChannelBuilder.java:300]: This **might** fix a old longstanding issue downstream: https://github.com/FirebaseExtended/flutterfire/issues/6749

**Comment by larssn** [comment]
This might fix a old longstanding issue downstream: FirebaseExtended/flutterfire#6749

File: android/src/main/java/io/grpc/android/AndroidChannelBuilder.java (hunk 1 above)
Comment (wu-hui) [reply android/src/main/java/io/grpc/android/AndroidChannelBuilder.java:300]: +1

This might just work, at least my test on a older version Android suggests nothing is broken.

**Review by dapengzhang0 — APPROVED** [review]

**Review by ejona86 — APPROVED** [review]
Doesn't entirely match our style, but the automated checker is happy so that can be fixed after it is merged.

**Comment by ejona86** [comment]
Thank you! Great find!

**Comment by larssn** [comment]
@ejona86 Any way this can find its way into a release before March 8th?

**Comment by ejona86** [comment]
@larssn, there'd be no problem backporting it to 1.44. We should do that.

But it is unclear when it'd be released. I'm not sure it is worth doing a release _just_ for this improvement. While it looks like it would be quite beneficial, this has apparently been an issue for 2.5 years, which makes it a hard case for urgency. Due to some other events we're more limited on time than ordinarily.

Looking around, I see some other fixes that might deserve a backport that haven't been backported. There may be enough to make it worthwhile.

@larssn, I assume this is a "Gee, 1.45 is a month away. Sure would be nice to get it sooner." You have no hard deadline, but simply "sooner is better than later"? I could easily make a 1.44.1-SNAPSHOT release, but that probably doesn't excite you.

**Comment by larssn** [comment]
@ejona86 Appreciate the reply. We're in a situation currently where our product doesn't handle coming out of standby correctly on Android, which is unfortunate because we're dealing with money. This is all the way upstream in Flutter territory. I'm not even sure this fixes it, but I'm pretty confident it does.

But the main reason I'm asking is because it will also take time for the fix to propagate all the way upstream. So yeah, you're spot on about the "sooner is better than later"-part 🙂

**Comment by ejona86** [comment]
@larssn, in asking around, it seems #8892 deserves backport and release(s?). So I'm expecting there's probably going to be a release of 1.44.1 within ~week.

**Comment by wu-hui** [comment]
> @larssn, in asking around, it seems #8892 deserves backport and release(s?). So I'm expecting there's probably going to be a release of 1.44.1 within ~week.

Do we have a tentative release date yet?

**Comment by ejona86** [comment]
@wu-hui, #8929 is out, which means the binaries will be available today or tomorrow and the announcement will probably be the day after.

**Comment by ejona86** [comment]
v1.44.1 is available on Maven Central. It isn't indexed by search.maven.org yet, but it is there.

**Comment by wu-hui** [comment]
Thank you, will upgrade from our side!
