### PR TITLE
[OkHtpp] Correct windowUpdateWithInboundFlowControl test.

### LINKED ISSUE #1168: OkHttpClientTransportTest > windowUpdateWithInboundFlowControl is flaky
```
io.grpc.okhttp.OkHttpClientTransportTest > windowUpdateWithInboundFlowControl FAILED
    Argument(s) are different! Wanted:
    frameWriter.windowUpdate(0, 32773);
    -> at io.grpc.okhttp.OkHttpClientTransportTest.windowUpdateWithInboundFlowControl(OkHttpClientTransportTest.java:494)
    Actual invocation has different arguments:
    frameWriter.windowUpdate(3, 32773);
    -> at io.grpc.okhttp.AsyncFrameWriter$13.doRun(AsyncFrameWriter.java:209)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at io.grpc.okhttp.OkHttpClientTransportTest.windowUpdateWithInboundFlowControl(OkHttpClientTransportTest.java:494)

70 tests completed, 1 failed
:grpc-okhttp:test FAILED
```

https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC-Java-PR-Windows/106/console
and
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC-Java-PR-Windows/105/console

### PR DESCRIPTION
**Pull request by madongfly**
We should check the window update is sent after the message is consumed.

Hopefully this will fix #1168

### CODE REVIEW

File: okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java [hunk 1]
```diff
@@ -492,6 +493,9 @@ public void windowUpdateWithInboundFlowControl() throws Exception {
     long messageFrameLength = buffer.size();
     frameHandler().data(false, 3, buffer, (int) messageFrameLength);
     verify(frameWriter, timeout(TIME_OUT_MS)).windowUpdate(eq(0), eq(messageFrameLength));
+    verify(frameWriter, times(0)).windowUpdate(eq(3), eq(messageFrameLength));
```
Comment (carl-mastrangelo) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Optional: you can use the never() function in Mockito

File: okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java [hunk 2]
```diff
@@ -482,7 +483,7 @@ public void windowUpdate() throws Exception {
   public void windowUpdateWithInboundFlowControl() throws Exception {
     initTransport();
     MockStreamListener listener = new MockStreamListener();
-    clientTransport.newStream(method, new Metadata(), listener).request(1);
+    OkHttpClientStream stream = clientTransport.newStream(method, new Metadata(), listener);
```
Comment (carl-mastrangelo) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: It seems like if you have the stream, you should be using the stream id in the checks below.  The 3 and 1 in the flaky tests are the http2 stream id I believe.

Comment (madongfly) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Done.

**Comment by madongfly** [comment]
@carl-mastrangelo PTAL, thanks!

File: okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java (hunk 1 above)
Comment (madongfly) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Done.

File: okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java (hunk 2 above)
Comment (madongfly) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Sorry, replied too hurry.

I think using 3 on the checks is better, it can potentially checks the streams id should be 3. I don't see any benefit of using stream.id() in the test checks.

Comment (carl-mastrangelo) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Being explicit is a good thing, and I agree it should be hard coded.  This change though doesn't seem to address the core of the issue:  why is it 1 something, and 3 others?

Comment (madongfly) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: I guess you meant 0 instead of 1?

0 means for the connection, 3 is the first valid stream id, 1 is reserved for special use case.

Comment (carl-mastrangelo) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Ah yes, you are right.  I am thinking of a different but ongoing issue also with this file, which exhibits the 1-3 ping-ponging.

In that case, it seems like you would want the verifier to fail on any number other than 0?  Perhaps a Captor would be more appropriate?

Comment (madongfly) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Done.

**Comment by carl-mastrangelo** [comment]
@madongfly LGTM

File: okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java (hunk 2 above)
Comment (ejona86) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: How does a captor help? Isn't it still doing the same asserts? It seems the actual fix is just delaying the `request(1)` like you did.
