### PR TITLE
OkHttpClientTransportTest's proxy to use loopback address

### LINKED ISSUE #8080: [Help wanted] io.grpc.okhttp.OkHttpClientTransportTest fails in Mac and GitHub Actions
In master, I cannot build :grpc-okhttp module because OkHttpClientTransportTest fails in my Mac (Mac OS 11.2.3) and GitHub Actions ([link](https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1982/checks?check_run_id=2328386670)). 

```
suztomo-macbookpro44% git log -1                                                                  
commit d4fa0ecc07495097453b0a2848765f076b9e714c (HEAD -> master, origin/master, origin/HEAD)
Author: Chengyuan Zhang <chengyuanzhang@google.com>
Date:   Mon Apr 12 14:55:31 2021 -0700
...(omit)...
suztomo-macbookpro44% cat gradle.properties 
skipCodegen=true
skipAndroid=true
suztomo-macbookpro44%  ./gradlew cleanTest :grpc-okhttp:test --tests=io.grpc.okhttp.OkHttpClientTransportTest
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

> Task :grpc-okhttp:test

io.grpc.okhttp.OkHttpClientTransportTest > proxy_200 FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_200(OkHttpClientTransportTest.java:1876)

io.grpc.okhttp.OkHttpClientTransportTest > proxy_500 FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_500(OkHttpClientTransportTest.java:1933)

io.grpc.okhttp.OkHttpClientTransportTest > proxy_immediateServerClose FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_immediateServerClose(OkHttpClientTransportTest.java:1989)

68 tests completed, 3 failed

> Task :grpc-okhttp:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-okhttp:test'.
> There were failing tests. See the report at: file:///Users/suztomo/grpc-java/okhttp/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
58 actionable tasks: 3 executed, 55 up-to-date
```

The build works fine in my Debian machine. (I also see this repository has setup Travis CI enabled.)

```
suztomo@suztomo:~/grpc-java$  ./gradlew cleanTest  :grpc-okhttp:test --tests=io.grpc.okhttp.OkHttpClientTransportTest
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

BUILD SUCCESSFUL in 5s
58 actionable tasks: 2 executed, 56 up-to-date
```

Therefore I think I'll need to setup something for the failing environment to make the test pass.

While I continue to dig further, I appreciate if anyone know the prerequisite for OkHttpClientTransportTest.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #8080.

### CODE REVIEW

**Comment by suztomo** [comment]
The method does not seem to exist in certain Android API.


```
> Task :grpc-okhttp:animalsnifferTest FAILED
2450
2451[Undefined reference | android-api-level-14-4.0_r4] io.grpc.okhttp.(OkHttpClientTransportTest.java:1853)
2452  >> java.net.InetAddress java.net.InetAddress.getLoopbackAddress()
2453
2454[Undefined reference | android-api-level-14-4.0_r4] io.grpc.okhttp.(OkHttpClientTransportTest.java:1910)
2455  >> java.net.InetAddress java.net.InetAddress.getLoopbackAddress()
2456
2457[Undefined reference | android-api-level-14-4.0_r4] io.grpc.okhttp.(OkHttpClientTransportTest.java:1966)
2458  >> java.net.InetAddress java.net.InetAddress.getLoopbackAddress()
2459
2460
2461

```

**Review by ejona86 — APPROVED** [review]

File: okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java [hunk 1]
```diff
@@ -1866,7 +1866,8 @@ public void proxy_200() throws Exception {
         INITIAL_WINDOW_SIZE,
         HttpConnectProxiedSocketAddress.newBuilder()
             .setTargetAddress(targetAddress)
-            .setProxyAddress(serverSocket.getLocalSocketAddress()).build(),
+            .setProxyAddress(new InetSocketAddress("localhost", serverSocket.getLocalPort()))
```
Comment (sanjaypujare) [inline okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java:1869]: Instead of "localhost" can we just use "127.0.0.1"? I did a small test where I modified my /etc/hosts file to have
```
192.16.10.23       localhost
```

and `localhost` resolved to that IP address which will break this test.

And can we also create the `ServerSocket` to bind to `127.0.0.1` instead of `0.0.0.0`? I don't see any upside to using `0.0.0.0`.

Comment (suztomo) [reply okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java:1869]: > any upside to using 0.0.0.0

I feel binding on 0.0.0.0 is more close to real-world use case than 127.0.0.1. I’m ok with 127.0.0.1 if you have a reason for 127.0.0.1.

Comment (suztomo) [reply okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: Changed "localhost" to "127.0.0.1". Thank you for input.

Comment (sanjaypujare) [reply okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: > I feel binding on 0.0.0.0 is more close to real-world use case than 127.0.0.1. I’m ok with 127.0.0.1 if you have a reason for 127.0.0.1.

Since 0.0.0.0 involves binding to all local interfaces if one of them fails I suspect the ServerSocket construction itself might fail so one more way to avoid extraneous test failures. You can look into it but I am okay with the current one.

**Review by sanjaypujare — APPROVED** [review]
LGTM

File: okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java (hunk 1 above)
Comment (ejona86) [reply okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java]: @sanjaypujare, we tend to prefer "localhost" because it works on IPv4-only and IPv6-only machines, although IPv4-only machines for loopback are rare so we'd favor ::1 if we had to choose an IP (but it [has bitten us before](https://github.com/grpc/grpc-java/commit/f9f603570d20d4507f4d90a3dc53915ac7db4d33)). This actually needs to be localhost here, or it will fail in our internal testing infrastructure since they are IPv6-only.

Comment (ejona86) [reply okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java:1869]: I went ahead and deleted the most recent commit from the branch, so it is now back to "localhost"

Comment (sanjaypujare) [reply okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java:1869]: Oh, okay. Good to know

**Comment by suztomo** [comment]
Thank you!
