### PR TITLE
Retry DNS resolution when there is an error.

### LINKED ISSUE #1546: If DNS resolution fails, the Channel is permanently failed
We should probably update DnsNameResolver to continue retrying the DNS query until shutdown, at maybe a fixed rate of 1 minute or such. Overall, it's not a superb solution, but it fixes a lot of the problem and is expedient to implement.

### PR DESCRIPTION
**Pull request by zhangkun83**
Resolves #1546

### CODE REVIEW

File: core/src/main/java/io/grpc/DnsNameResolverFactory.java [hunk 1]
```diff
@@ -63,7 +65,7 @@ public NameResolver newNameResolver(URI targetUri, Attributes params) {
       Preconditions.checkArgument(targetPath.startsWith("/"),
           "the path component (%s) of the target (%s) must start with '/'", targetPath, targetUri);
       String name = targetPath.substring(1);
-      return new DnsNameResolver(targetUri.getAuthority(), name, params);
+      return new DnsNameResolver(targetUri.getAuthority(), name, params, GrpcUtil.TIMER_SERVICE);
```
Comment (ejona86) [inline core/src/main/java/io/grpc/DnsNameResolverFactory.java]: If we are using this shared single-threaded `ScheduledExecutorService` we should probably make sure that we don't do blocking DNS resolution on that executor thread. Instead, we may need to use a combination of `SHARED_CHANNEL_EXECUTOR` and the `TIMER_SERVICE`.

File: core/src/main/java/io/grpc/DnsNameResolver.java [hunk 2]
```diff
@@ -85,39 +94,44 @@
...
+  private final Runnable resolutionRunnable = new Runnable() {
       @Override
       public void run() {
         InetAddress[] inetAddrs;
+        Listener savedListener;
+        synchronized (DnsNameResolver.this) {
+          savedListener = listener;
+          resolving = true;
+          if (resolutionTask != null) {
+            resolutionTask.cancel(false);
```
Comment (ejona86) [inline core/src/main/java/io/grpc/DnsNameResolver.java]: Isn't `resolutionTask` guaranteed to be the currently-executing Runnable? As in, it is guaranteed to never be cancelled at this point because it is running right now?

Comment (ejona86) [inline core/src/main/java/io/grpc/DnsNameResolver.java]: nm. I see, interaction with refresh() can call more than one task.

File: core/src/main/java/io/grpc/DnsNameResolverFactory.java (hunk 1 above)
Comment (zhangkun83) [inline core/src/main/java/io/grpc/DnsNameResolverFactory.java]: Done. PTAL.

**Comment by ejona86** [comment]
@zhangkun83 LGTM

**Comment by zhangkun83** [comment]
@ejona86 I just added shutdown handling. PTAL.

**Comment by ejona86** [comment]
resolutionRunnableOnExecutor needs to check shutdown as well, since it can race with shutdown() and then get NPE.

@zhangkun83, otherwise, LGTM
