### PR TITLE
netty:Fix Netty composite buffer merging to be compatible with Netty 4.1.111

### LINKED ISSUE #11284: grpc-netty breaks with Netty 4.1.111.Final
Added by ejona86: CORRUPTION. See https://github.com/grpc/grpc-java/issues/11284#issuecomment-2168264887

-----

### What version of gRPC-Java are you using?

1.60.2, 1.64.0

### What is your environment?

```
❯ uname -a
Darwin Laris-MBP.lan 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64 arm Darwin
❯ java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode)
```

### What did you expect to see?

I'd expect grpc-netty to work with Netty 4.1.111.Final . I understand that [grpc-java currently supports Netty 4.1.100.Final](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty), however many libraries depend on grpc-netty and cannot switch to use grpc-netty-shaded without relocating all classes to use the packages where grpc-netty-shaded contains shaded version of Netty. Examples of such popular libraries are io.etcd:jetcd-core and io.vertx:vertx-grpc.

### What did you see instead?

There weren't any log messages or exceptions, communications just timed out. There were some debug logging about attempts. I'll share more details later.

### Steps to reproduce the bug

I'll share more details later. I maintain Apache Pulsar and Apache Bookkeeper projects and this problem showed up there when Netty got upgrades from 4.1.108.Final to 4.1.111.Final. We use an older grpc version, but I also tested with 1.60.2 and 1.64.0 and the problem remained. I also tried upgrading to 4.1.110.Final and that works fine with the test using jetcd-core that fails.
This means that Netty release 4.1.111.Final introduces a change that breaks grpc-netty.
These are the 4.1.111.Final release notes and changes: 
* https://netty.io/news/2024/06/11/4-1-111-Final.html
* https://github.com/netty/netty/milestone/292?closed=1
* https://github.com/netty/netty/compare/netty-4.1.110.Final...netty-4.1.111.Final

### PR DESCRIPTION
**Pull request by larry-safran**
Change the logic for identifying changes to the read index when merging into a netty composite buffer so that it works with both older versions of netty and netty 4.1.111

Fixes #11284

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java [hunk 1]
```diff
@@ -22,10 +22,18 @@
...
+import io.netty.util.Version;
 
 class NettyAdaptiveCumulator implements Cumulator {
+  private static final boolean usingPre4_1_111_Netty;
   private final int composeMinSize;
 
+  static {
+    Version version = Version.identify().get("netty-buffer");
+    usingPre4_1_111_Netty =
+        version != null && version.artifactVersion().compareTo("4.1.111.Final") < 0;
```
Comment (panchenko) [inline netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:34]: How likely the version would be `4.1.99` ?

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java [hunk 2]
```diff
@@ -155,25 +163,20 @@ static void mergeWithCompositeTail(
...
+          // Because of the way duplicate() works in older netty versions this works.  It stops
+          // working in 4.1.111 because they changed what duplicate returns.
+          ByteBuf sliceDuplicate = composite.internalComponent(tailComponentIndex).duplicate();
+          newTail.setIndex(sliceDuplicate.readerIndex(), sliceDuplicate.writerIndex());
+        } else {
+          int arrayOffset = composite.internalComponent(tailComponentIndex).arrayOffset();
+          if (arrayOffset > 0 && arrayOffset + tail.readerIndex() < tailSize) {
+            // The tail is a slice of a larger buffer, so we need to adjust the read index.
+            newTail.setIndex(arrayOffset + tail.readerIndex(), tail.writerIndex());
+          }
```
Comment (lhotari) [inline netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:178]: `.arrayOffset()` is only available for heap ByteBufs (when `hasArray()` returns true). Are the components of the composite always heap ByteBufs?

The [javadoc of CompositeByteBuf.internalComponent](https://github.com/netty/netty/blob/8b803abf36a757911e77f747b338b55a02822022/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java#L1570-L1571) says that "updating the indexes of the returned buffer will lead to an undefined behavior of this buffer". 
Is this solution attempting to update the indexes?

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java [hunk 3]
```diff
@@ -155,25 +163,20 @@ static void mergeWithCompositeTail(
...
-        // Hence composite.internalComponent().duplicate() returns a buffer with the
-        // indexes that should've been on the composite.component() in the first place.
-        // Until the issue is fixed, we manually adjust the indexes of the removed component.
-        ByteBuf sliceDuplicate = composite.internalComponent(tailComponentIndex).duplicate();
-        newTail.setIndex(sliceDuplicate.readerIndex(), sliceDuplicate.writerIndex());
+        // In older versions some buffers don't support arrayOffset(), so for performance
+        // we don't want to rely on the arrayOffset when we know the alternate path works
+        if (usingPre4_1_111_Netty) {
+          // Because of the way duplicate() works in older netty versions this works.  It stops
+          // working in 4.1.111 because they changed what duplicate returns.
```
Comment (lhotari) [inline netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:170]: I don't think it's fair to put blame on changes in Netty. It seems that this might have always been violating the API contract of Netty's CompositeByteBuf. The [javadoc of CompositeByteBuf.internalComponent](https://github.com/netty/netty/blob/8b803abf36a757911e77f747b338b55a02822022/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java#L1570-L1571) says that "updating the indexes of the returned buffer will lead to an undefined behavior of this buffer". That's exactly what happened here.

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java [hunk 4]
```diff
@@ -155,25 +163,20 @@ static void mergeWithCompositeTail(
...
+          ByteBuf sliceDuplicate = composite.internalComponent(tailComponentIndex).duplicate();
+          newTail.setIndex(sliceDuplicate.readerIndex(), sliceDuplicate.writerIndex());
```
Comment (lhotari) [inline netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:172]: I don't think it's fair to put blame on changes in Netty. It seems that this might have always been violating the API contract of Netty's CompositeByteBuf. The [javadoc of CompositeByteBuf.internalComponent](https://github.com/netty/netty/blob/8b803abf36a757911e77f747b338b55a02822022/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java#L1570-L1571) says that "updating the indexes of the returned buffer will lead to an undefined behavior of this buffer". That's exactly what happened here.

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java (hunk 1 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java]: Good point.  I've updated the logic.

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java (hunk 4 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:189]: @lhotari No, it isn't updating the indexes of the `internalComponent` buffer, it is using values retrieved from the internalComponent to update the `readerIndex` of the buffer returned by `composite.component`. You can see https://github.com/netty/netty/issues/12844 for a description of why this is being done.  Note that this has been in place and working for a couple of years.

If you know of a better approach in netty 4 for appending to the existing last buffer in a composite than the approach we are taking, I'd be very interested in it.

**Review by ejona86 — APPROVED** [review]
The approach for this change is "`CompositeByteBuf.addFlattenComponents()` is broken, so stop using it." Only when using `addFlattenComponents()` do the components' readable area not equal the Composite's capacity.

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java [hunk 5]
```diff
@@ -150,31 +150,13 @@ static void mergeWithCompositeTail(
...
     try {
-      if (tail.refCnt() == 1 && !tail.isReadOnly() && newTailSize <= tail.maxCapacity()) {
+      if (tail.refCnt() == 1 && !tail.isReadOnly() && newTailSize <= tail.maxCapacity()
+          && !isWrappedComposite(tail)) {
         // Ideal case: the tail isn't shared, and can be expanded to the required capacity.
+
         // Take ownership of the tail.
         newTail = tail.retain();
 
-        // TODO(https://github.com/netty/netty/issues/12844): remove when we use Netty with
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:158]: Added to class javadoc

**Review by ejona86 — APPROVED** [review]

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java [hunk 6]
```diff
@@ -23,6 +23,18 @@
 import io.netty.buffer.CompositeByteBuf;
 import io.netty.handler.codec.ByteToMessageDecoder.Cumulator;
 
+
+/**
+ * "Adaptive" cumulator: cumulate {@link ByteBuf}s by dynamically switching between merge and
+ * compose strategies.
+ * <br><br>
+ *
+ * <p><b><font color="red">Avoid using</font></b>
```
Comment (sergiitk) [inline netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:32]: I'm not sure this phrasing in red font makes a lot of sense here. It's not actionable for the user of this class. If it's for modifying the class itself, should we just note that on `mergeWithCompositeTail` method instead?

**Review by sergiitk — APPROVED** [review]
Great job figuring out this solution, @larry-safran!

File: netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java [hunk 7]
```diff
@@ -639,13 +637,6 @@ public void mergeWithCompositeTail_outOfSyncComposite() {
       CompositeByteBuf cumulation = (CompositeByteBuf) cumulator.cumulate(alloc, composite2,
           ByteBufUtil.writeAscii(alloc, "56789"));
       assertThat(cumulation.toString(US_ASCII)).isEqualTo("0123456789");
-
-      // Correctness check: we still have a single component, and this component is still the
-      // original underlying buffer.
-      assertThat(cumulation.numComponents()).isEqualTo(1);
-      // Replace '2' with '*', and '8' with '$'.
-      buf.setByte(5, '*').setByte(11, '$');
-      assertThat(cumulation.toString(US_ASCII)).isEqualTo("01*34567$9");
```
Comment (sergiitk) [inline netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java:648]: wait, we still want these assertions!

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java (hunk 6 above)
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:32]: It isn't just for `mergeWithCompositeTail`. It is for the entire class. So `cumulate()` and `addTail` are impacted as well.

**Comment by idelpivnitskiy** [comment]
@ejona86 @larry-safran I see you added "backport" and "release blocker" tags. Could you please share in what versions do you plan to backport this fix and what is ETA for new releases?

**Comment by larry-safran** [comment]
I plan to backport to 1.65 (not yet released), 1.64 & 1.63

**Comment by idelpivnitskiy** [comment]
@larry-safran what is ETA for 1.64.1 to be available in Maven Central?

**Comment by larry-safran** [comment]
I'm actively working on the patch release so it should be available this
week.
