### PR TITLE
benchmarks: reset context in AsyncClient to avoid chaining.

### LINKED ISSUE #1878: Stack Overflow when running AsyncClient
```
INFO: [ManagedChannelImpl@506e6d5e] Created with target directaddress:///localhost/127.0.0.1:1234
May 27, 2016 9:43:05 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@668bc3d5] Created with target directaddress:///localhost/127.0.0.1:1234
May 27, 2016 9:43:05 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@62043840] Created with target directaddress:///localhost/127.0.0.1:1234
Exception in thread "grpc-default-executor-32" java.lang.StackOverflowError
        at io.grpc.Context.removeListener(Context.java:454)
        at io.grpc.Context.removeListener(Context.java:462)
        at io.grpc.Context.removeListener(Context.java:462)
        at io.grpc.Context.removeListener(Context.java:462)
        at io.grpc.Context.removeListener(Context.java:462)
        at io.grpc.Context.removeListener(Context.java:462)
        at io.grpc.Context.removeListener(Context.java:462)
        at io.grpc.Context.removeListener(Context.java:462)
        at io.grpc.Context.removeListener(Context.java:462)
```

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #1878

### CODE REVIEW

File: benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncClient.java [hunk 1]
```diff
@@ -198,10 +199,16 @@ public void onCompleted() {
         histogram.recordValue((now - lastCall) / 1000);
         lastCall = now;
 
-        if (endTime > now) {
-          stub.unaryCall(request, this);
-        } else {
-          future.done();
+        Context prevCtx = null;
+        try {
+          prevCtx = Context.ROOT.attach();
```
Comment (ejona86) [inline benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncClient.java]: This line can be moved before the try, which will also prevent prevCtx from being `null` and throwing an exception in `detach()`

**Comment by ejona86** [comment]
@carl-mastrangelo LGTM

File: benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncClient.java (hunk 1 above)
Comment (carl-mastrangelo) [inline benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncClient.java]: Done.
