### PR TITLE
stub: Add null check for responseObserver

### LINKED ISSUE #10064: NullPointerException at ClientCalls.java:487
### What version of gRPC-Java are you using?
io.grpc:grpc-core:1.50.1
io.grpc:grpc-protobuf:1.50.1
io.grpc:grpc-stub:1.50.1
### What is your environment?

Apple M1 Max
macOS Ventura Version 13.31
openjdk version "11.0.18" 2023-01-17

### What did you expect to see?
I expect not to see the NPE
### What did you see instead?
```
message:"Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed@3f42672c",
logger_name:"i.g.i.SerializingExecutor",

java.lang.NullPointerException: null
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
	

### Steps to reproduce the bug
It's hard to reproduce it. It happens from time to time.

What could be an issue for this NPE? Any advice or feedback would be appreciated

### PR DESCRIPTION
**Pull request by larry-safran**
Add null check for responseObserver in the methods for initiating a call that take a responseObserver argument.  This insures a fail fast with a clearer cause instead of an NPE when the observer is first used.

Fixes #10064

### CODE REVIEW

File: stub/src/test/java/io/grpc/stub/ClientCallsTest.java [hunk 1]
```diff
@@ -503,6 +504,50 @@ public void onCompleted() {
...
   }
 
+  @Test
+  public void checkForNullInAsyncUnaryCall()  {
+    NoopClientCall<Integer, String> call = new NoopClientCall<>();
+    try {
+      ClientCalls.asyncUnaryCall(call, Integer.valueOf(1), null);
+      Assert.fail("Should have gotten an exception for the null responseObserver");
+    } catch (NullPointerException e) {
+      assertSame("responseObserver", e.getMessage());
```
Comment (sergiitk) [inline stub/src/test/java/io/grpc/stub/ClientCallsTest.java:514]: Why not `assertEquals`? Do we care that the instance of the string is the same as returned by error message?

Comment (larry-safran) [reply stub/src/test/java/io/grpc/stub/ClientCallsTest.java]: Good point.  It was being used all over the test so I've updated all of the assertSame to assertEquals.

File: stub/src/test/java/io/grpc/stub/ClientCallsTest.java [hunk 2]
```diff
@@ -155,8 +155,8 @@ public void start(io.grpc.ClientCall.Listener<String> listener, Metadata headers
       ClientCalls.blockingUnaryCall(call, req);
       fail("Should fail");
     } catch (StatusRuntimeException e) {
-      assertSame(status, e.getStatus());
-      assertSame(trailers, e.getTrailers());
+      assertEquals(status, e.getStatus());
```
Comment (sergiitk) [inline stub/src/test/java/io/grpc/stub/ClientCallsTest.java:158]: Here and below: I think you accidentally changes `assertSame` to `assertEquals` in unrelated places.

**Review by sergiitk — CHANGES_REQUESTED** [review]

File: stub/src/test/java/io/grpc/stub/ClientCallsTest.java (hunk 2 above)
Comment (larry-safran) [reply stub/src/test/java/io/grpc/stub/ClientCallsTest.java:158]: No, it was very much on purpose.  I don't think that in any of those places that it is important for it to be the same object rather than them being equal.  Of course, the same objects are always equal, but it would be better to only check for the meaningful comparison.

Comment (sergiitk) [reply stub/src/test/java/io/grpc/stub/ClientCallsTest.java:158]: I don't think it's fair to assume whoever wrote this code didn't consider whether they want to do `assertSame` or `assertEquals`. 
For example, on the line below they do `assertEquals(trailers, e.getTrailers())`, which, IMHO makes a lot of sense here - they're checking that what got propagated in `e.getTrailers()` is the same instance of `Metadata`, as was passed into `listener.onClose(status, trailers);`.

**Review by sergiitk — CHANGES_REQUESTED** [review]
Please revert `assertSame` to `assertEquals` on the lines unrelated to the scope of this change.

File: stub/src/test/java/io/grpc/stub/ClientCallsTest.java (hunk 2 above)
Comment (larry-safran) [reply stub/src/test/java/io/grpc/stub/ClientCallsTest.java]: Okay, reverted the ones that were in previous tests.

File: stub/src/test/java/io/grpc/stub/ClientCallsTest.java [hunk 3]
```diff
@@ -65,6 +65,7 @@
 import java.util.concurrent.TimeUnit;
 import java.util.concurrent.atomic.AtomicReference;
 import org.junit.After;
+import org.junit.Assert;
```
Comment (sergiitk) [inline stub/src/test/java/io/grpc/stub/ClientCallsTest.java:68]: nit: noticed there's already a static import of `Assert.fail`, could you please replace `Assert.fail()` with `fail()` and remove this import?

**Review by sergiitk — APPROVED** [review]
One small nit.

File: stub/src/test/java/io/grpc/stub/ClientCallsTest.java (hunk 3 above)
Comment (larry-safran) [reply stub/src/test/java/io/grpc/stub/ClientCallsTest.java]: done
