### PR TITLE
Client-side support for h2c via Upgrade #4518

### LINKED ISSUE #4518: Client-side h2c (insecure HTTP/1.1-to-h2) upgrade does not work
When specifying `NegotiationType.PLAINTEXT_UPGRADE`, the client should connect over HTTP/1.1 with headers indicating that this request should be upgraded to (still insecure) h2.

There seems to be quite a bit of machinery in place to make this work, but currently the client does not start sending the request after performing the TCP handshake. A possible fix for this has been previously proposed in https://github.com/grpc/grpc-java/pull/3529/files#diff-e805c3ddf2a8c848220b85c467f5f408R379 (and when I tried this locally it did appear to help), but the code has evolved since.

Our use case for this feature is that while in production you'd use TLS and ALPN to serve both HTTP/1.1 and h2 requests on the same port, during development it can be convenient to run without TLS. `NegotiationType.PLAINTEXT` is available for non-TLS connections, but does not (really) support HTTP/1.1 and h2 coexisting on the same port.

### What version of gRPC are you using?

Checked on 1.11.0, 1.12.0 and master.

### What did you expect to see?

I expected the grpc-java Netty client to successfully connect to a h2c endpoint when configured with `NegotiationType.PLAINTEXT_UPGRADE`.

### PR DESCRIPTION
**Pull request by raboof**
Upgrading from HTTP/1.1 to h2c (HTTP/2 in cleartext).

This is best avoided if possible (since it not widely implemented and comes at
the cost of a roundtrip), but a nice option to have.

Based on work by @xujianhai in #3529

Related to #3528 and fixes #4518

Not sure how to properly test this...

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java [hunk 1]
```diff
@@ -726,6 +728,7 @@ public void channelActive(ChannelHandlerContext ctx) throws Exception {
       // which causes the upgrade headers to be added
       DefaultHttpRequest upgradeTrigger =
           new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.GET, "/");
+      upgradeTrigger.headers().add(HttpHeaderNames.HOST, "");
```
Comment (carl-mastrangelo) [inline netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java]: This should be /something/ right?

File: netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java [hunk 2]
```diff
@@ -710,8 +711,9 @@ public void channelActive(ChannelHandlerContext ctx) throws Exception {
 
     private final GrpcHttp2ConnectionHandler grpcHandler;
 
-    BufferingHttp2UpgradeHandler(ChannelHandler handler, GrpcHttp2ConnectionHandler grpcHandler) {
-      super(handler);
+    BufferingHttp2UpgradeHandler(ChannelHandler handler, ChannelHandler upgradeHandler,
+                                 GrpcHttp2ConnectionHandler grpcHandler) {
```
Comment (carl-mastrangelo) [inline netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java]: We typically wrap lines +4 spaces.

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java [hunk 3]
```diff
@@ -323,10 +323,13 @@ void returnProcessedBytes(Http2Stream stream, int bytes) {
   }
 
   private void onHeadersRead(int streamId, Http2Headers headers, boolean endStream) {
-    NettyClientStream.TransportState stream = clientStream(requireHttp2Stream(streamId));
-    stream.transportHeadersReceived(headers, endStream);
-    if (keepAliveManager != null) {
-      keepAliveManager.onDataReceived();
+    // Stream 1 is reserved for the Upgrade response, so we should ignore its headers here:
+    if (streamId != 1) {
```
Comment (carl-mastrangelo) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: It seems like this should check the negotiation type before ignoring the headers.

File: netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java (hunk 1 above)
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java]: Seems like it should be the authority. See how `TlsNegotiator`'s host+port is plumbed, partly in this file.

File: netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java (hunk 2 above)
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java]: Note that what is here does adhere to the style guide, but yes, we do tend to wrap with 4 spaces.

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java (hunk 3 above)
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: @carl-mastrangelo, how do you suggest checking the negotiation type? At present, Netty reserves streamId 1 only for upgrades.

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java [hunk 4]
```diff
@@ -323,10 +323,13 @@ void returnProcessedBytes(Http2Stream stream, int bytes) {
...
+      NettyClientStream.TransportState stream = clientStream(requireHttp2Stream(streamId));
+      stream.transportHeadersReceived(headers, endStream);
+      if (keepAliveManager != null) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: This should be outside of the if. It should always run.

File: interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java [hunk 5]
```diff
@@ -162,6 +165,9 @@ void parseArgs(String[] args) {
           + "\n  --use_tls=true|false        Whether to use TLS. Default " + c.useTls
           + "\n  --use_alts=true|false       Whether to use ALTS. Enable ALTS will disable TLS."
           + "\n                              Default " + c.useTls
+          + "\n  --use_upgrade=true|false    Whether to use the h2c Upgrade mechanism. "
+          + "Enabling h2c Upgrade will disable TLS."
```
Comment (ejona86) [inline interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java]: We would want this to be on a new line and indented, to make it look fine even on non-super-wide terminals.

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java (hunk 3 above)
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: Let's reference https://github.com/netty/netty/blob/netty-4.1.25.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2CodecUtil.java#L47 here instead of just plain `1`.

**Comment by ejona86** [comment]
> If possible, could you add a test that shows upgrade works?

The description mentions that it's unclear how to test this. I'd agree it is unclear, because today we mainly test it against a server... and our server doesn't support h2c Upgrade. Because the response is in h2... yeah, it's hard to avoid having a "real" server here (although the gRPC part could be hacked out; it could be based on the "http2 example" in Netty...) May be a pain...

File: netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java (hunk 1 above)
Comment (carl-mastrangelo) [reply netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java]: authority was my guess too, but I don't know if it maps exactly to HTTP/1.1 Host.  Also, what happens if both are present? o_O

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java (hunk 3 above)
Comment (carl-mastrangelo) [reply netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: The comment made it seem like it was more general than Netty.  Maybe the comment should be updated?

**Comment by zpencer** [comment]
Hi @raboof friendly ping for an update on this PR.

**Comment by zhangkun83** [comment]
@ejona86 @carl-mastrangelo ping

**Comment by ejona86** [comment]
As I mentioned in my review, this is waiting on a test, or being okay with it breaking again because it doesn't have a test.

**Comment by raboof** [comment]
Thanks for the ping. I would like to add a test and gave it a shot a while ago, but had trouble digesting `ProtocolNegotiatorsTest.httpProxy_completes` - I'm not too familiar with the infrastructure used there. I'm OK with merging as-is (and fully aware that means it could break again at any time :) )

**Comment by ejona86** [comment]
@raboof, thanks for the fix! I might poke later to form up a test for it. I wrote `httpProxy_completes` so it is probably easier for me :)

**Comment by ejona86** [comment]
I created #5102 to track the test creation.
