### PR TITLE
netty: Fix NPE in NettyClientTransport when keepalive is enabled

### LINKED ISSUE #2726: NPE during NettyClientTransport.start() if keepAlive is enabled
### What version of gRPC are you using?
GRPC 1.1.2

### What JVM are you using (`java -version`)?
1.8.0_112

### What did you do?
Just simply call io.grpc.netty.NettyChannelBuilder#enableKeepAlive(boolean) during channel build. and the grpc always throw NPE exception.

```
java.lang.NullPointerException: null
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:169)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:44)
	at io.grpc.internal.TransportSet.startNewTransport(TransportSet.java:233)
	at io.grpc.internal.TransportSet.obtainActiveTransport(TransportSet.java:203)
	at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:739)
	at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:677)
	at io.grpc.PickFirstBalancerFactory$PickFirstBalancer$1.get(PickFirstBalancerFactory.java:129)
	at io.grpc.internal.DelayedClientTransport$2.run(DelayedClientTransport.java:271)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

and inspect the code(io.grpc.netty.NettyClientTransport#start):

```java
 @SuppressWarnings("unchecked")
  @Override
  public Runnable start(Listener transportListener) {
    lifecycleManager = new ClientTransportLifecycleManager(
        Preconditions.checkNotNull(transportListener, "listener"));

    if (enableKeepAlive) {
      keepAliveManager = new KeepAliveManager(this, channel.eventLoop(), keepAliveDelayNanos,
          keepAliveTimeoutNanos);
    }
    ....
}
```

i believe the field `channel` is never initialized right now, so NPE is throw by field call `channel.eventLoop()`.

### PR DESCRIPTION
**Pull request by lukaszx0**
* Move creation of `keepAliveManager` to the bottom of `start()`
* Enable keepAlive in `NettyClientTransportTest`
* Add test cases checking if keepalive is enabled/disabled, specifically.

Fixes #2726

cc @ejona86 @bobwenx

### CODE REVIEW

File: netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java [hunk 1]
```diff
@@ -344,6 +345,24 @@ public void clientStreamGetsAttributes() throws Exception {
     assertEquals(address, rpc.stream.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR));
   }
 
+  @Test
+  public void keepAliveEnabled() throws Exception {
```
Comment (ejona86) [inline netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java]: Could you do an RPC in each of these tests and just make sure you get OK? That will check many of the `== null` checks in the code.

Comment (lukaszx0) [inline netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java]: Done

**Comment by ejona86** [comment]
retest this please

**Comment by ejona86** [comment]
Thanks @lukaszx0!

**Comment by bobwenx** [comment]
can't wait to see this fix released

**Comment by bobwenx** [comment]
Any plan to release this backport fix?

**Comment by carl-mastrangelo** [comment]
@bobwenx probably not, it will show up in 1.2 which will be released in about 2 weeks.

**Comment by bobwenx** [comment]
@carl-mastrangelo 2 weeks past, is there any progress on the 1.2 released?
