### PR TITLE
compiler: generate blocking v2 unary calls that throw StatusException

### LINKED ISSUE #11937: blocking v2 client stub inconsistent about StatusRuntimeException verus StatusException
`io.grpc.stub.BlockingClientCall` uses the checked `StatusException`, so server-streaming and client-streaming v2 blocking RPCs have to deal with `StatusException`. However, the unary blocking v2 RPCs stubs have the implementation and thus behavior as v1; namely, all status exceptions are `StatusRuntimeException`. Should this be made consistent?

### PR DESCRIPTION
**Pull request by shivaspeaks**
#### Note on API-breaking change:
This change modifies the blocking unary call behavior in v2 stubs to throw a checked StatusException instead of an unchecked StatusRuntimeException.

Existing code using v1 stubs will continue to behave as before — no changes are required for v1.
For users not ready to adopt the new behavior in v2, you may continue using code generated with v1 stub style until you’re ready to migrate.

Fixes #11937

### CODE REVIEW

File: stub/src/main/java/io/grpc/stub/ClientCalls.java [hunk 1]
```diff
@@ -182,6 +182,23 @@ public static <ReqT, RespT> RespT blockingUnaryCall(
     }
   }
 
+  /**
+   * Executes a unary call and blocks on the response, converting StatusRuntimeException to
+   * StatusException for consistency with other blocking call types.
```
Comment (kannanjgithub) [inline stub/src/main/java/io/grpc/stub/ClientCalls.java]: Remove "for consistency with other blocking call types."

**Comment by kannanjgithub** [comment]
You have included the generated stubs in the commit for interop-testing but not for android-interop-testing which causes Android build to fail.

**Comment by shivaspeaks** [comment]
I see.
So, interop-testing files were generated automatically after clean build but we do keep the flag `-PskipAdroid=true` to skip android related builds.

**Comment by kannanjgithub** [comment]
You can install Android sdk following [these steps](https://github.com/grpc/grpc-java/blob/master/buildscripts/kokoro/android.sh#L22-L29) and then do a build with Android build enabled. If you run into OOM during the build then we can look into upgrading the cloudtop or using a custom Kokoro VM and work on that VM.

File: stub/src/main/java/io/grpc/stub/ClientCalls.java [hunk 2]
```diff
@@ -182,6 +182,23 @@ public static <ReqT, RespT> RespT blockingUnaryCall(
     }
   }
 
+  /**
+   * Executes a unary call and blocks on the response, converting StatusRuntimeException
```
Comment (ejona86) [inline stub/src/main/java/io/grpc/stub/ClientCalls.java]: Converting the exceptions is an implementation detail. You can say it uses a checked exception, but don't say it is "converting"

**Comment by ejona86** [comment]
> If you run into OOM during the build then we can look into upgrading the cloudtop or using a custom Kokoro VM and work on that VM.

If you get an OOM, it normally isn't really the machine you're on. You generally just need to tell Gradle to use more memory. I think I put `org.gradle.jvmargs=-Xmx2048m` in my gradle.properties for that.

**Review by ejona86 — APPROVED** [review]
Make some note in the commit/PR description how users should handle the API-breaking nature of the change (i.e., v1 will worth the same before/after this change, and they can stay on the old generated code for a little bit).

**Comment by shivaspeaks** [comment]
> If you get an OOM, it normally isn't really the machine you're on. You generally just need to tell Gradle to use more memory. I think I put org.gradle.jvmargs=-Xmx2048m in my gradle.properties for that.

Yes right, I have kept `org.gradle.jvmargs=-Xmx4096m` 👀

**Review by kannanjgithub — APPROVED** [review]

**Comment by shivaspeaks** [comment]
I don't know how to resolve this Android failure. Android build in local works just fine, there's no reason to fail. @kannanjgithub

**Comment by ejona86** [comment]
The Android CI is using the new code generator with the old version. That will break. I think we just need to ignore it for this PR, as we can't easily use the old code generator either.
