### PR TITLE
core fix 5450 (alternative approach)

### LINKED ISSUE #5450: Data race in NameResolve.Listener.onError
`NameResolve.Listener.onError` can be called concurrently in different threads, so the following code in `onError()` impl may have data race.

```
if (haveBackends == null || haveBackends) {
    channelLogger.log(ChannelLogLevel.WARNING, "Failed to resolve name: {0}", error);
    haveBackends = false;
}
```

### PR DESCRIPTION
**Pull request by dapengzhang0**
Resolves #5450

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/ManagedChannelImpl.java [hunk 1]
```diff
@@ -1339,41 +1341,45 @@ public void onError(final Status error) {
       checkArgument(!error.isOk(), "the error status must not be OK");
       logger.log(Level.WARNING, "[{0}] Failed to resolve name. status={1}",
```
Comment (zhangkun83) [inline core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: I would move this line into the runnable to be consistent with the logging in `onAddresses()`.

Comment (dapengzhang0) [reply core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: Done.
