### PR TITLE
Fix memory leak with cancellation timeouts

### LINKED ISSUE #1307: ScheduledFutureTask cancellation does not guarantee queue removal
GRPC users using timeout may observe a memory leak when using long RPC timeouts with calls that complete quickly.

In ClientCallImpl we add a Runnable to trigger the timeout to a ScheduledExecutorService and retain a ScheduledFuture to that we can cancel the timeout if the call completes before that time.

The issue is that calling ScheduleFuture.cancel is not guaranteed to remove the task from the executors queue and so a leak of ClientCallImpl and its retained objects can occur.

We use ScheduledThreadPoolExecutor as the default and can call setRemoveOnCancelPolicy(true) to cause the task to be correctly removed from the queue. We would need a strong guarantee that a ScheduledExecutorService with this behavior is being used to rely on it.

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #1307

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/GrpcUtil.java [hunk 1]
```diff
@@ -404,10 +406,32 @@ public String toString() {
...
+          // the executors queue.  This forces immediate removal upon cancellation to avoid a
+          // memory leak.  Reflection is used because we cannot use methods added in Java 1.7.  If
+          // the method does not exist, we give up.  Note that the method is not present in 1.6, but
+          // _is_ present in the android standard library.
+          try {
+            Method method = service.getClass().getMethod("setRemoveOnCancelPolicy", boolean.class);
+            method.invoke(service, true);
+          } catch (NoSuchMethodException e) {
+            // no op
+          } catch (SecurityException e) {
```
Comment (zhangkun83) [inline core/src/main/java/io/grpc/internal/GrpcUtil.java]: The following catch blocks can be simplified:
```
} catch (Exception e) {
  throw Throwables.propagate(e);
}
```

Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/GrpcUtil.java]: Done.

**Comment by zhangkun83** [comment]
LGTM
