### PR TITLE
benchmarks: Avoid sending a message after half close

### LINKED ISSUE #2372: Java QpsWorker produces many exceptions
We've recently enabled printing output from QPS workers in the benchmark suite, but the logs are 93MB big, which makes them completely useless.
It seems that it's mostly because java worker is super chatty (tons of exceptions get printed to the console)

https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_experiment/3192/consoleFull

### PR DESCRIPTION
**Pull request by ejona86**
This doesn't impact test behavior per-se, but causes it to produce less
useless log output of the form:

```
java.lang.IllegalStateException: call was half-closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:380)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:299)
	at io.grpc.benchmarks.driver.LoadClient$AsyncPingPongWorker$1.onNext(LoadClient.java:406)
	at io.grpc.benchmarks.driver.LoadClient$AsyncPingPongWorker$1.onNext(LoadClient.java:400)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:382)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:473)
	... 7 more
```

Fixes #2372

### CODE REVIEW

**Comment by ejona86** [comment]
@carl-mastrangelo, I pushed a cleaner version.

File: benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadClient.java [hunk 1]
```diff
@@ -403,11 +403,13 @@ public void run() {
               @Override
               public void onNext(Messages.SimpleResponse value) {
                 delay(System.nanoTime() - now);
```
Comment (carl-mastrangelo) [inline benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadClient.java]: nit: won't now be wrong here?

Comment (ejona86) [inline benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadClient.java]: onNext won't be called again. If it is, then an exception will be thrown because onCompleted is called more than once.

Comment (ejona86) [inline benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadClient.java]: `now` is initialized to `nanoTime()`, and the first message is sent outside of the StreamObserver. So it looks like it is consistent.
