### PR TITLE
api: When forwarding from Listener onAddresses to Listener2 continue to use onResult

### LINKED ISSUE #11662: since grpc-java 1.68.1, pekko-grpc has issues with RetryingNameResolver (throwIfNotInThisSynchronizationContext)
Similar to #10407 but has started affecting us with grpc-java 1.68.1

```
Error:  [11/03/2024 08:12:31.956] [default-pekko.actor.default-dispatcher-6] [org.apache.pekko.dispatch.Dispatcher] Not called from the SynchronizationContext
java.lang.IllegalStateException: Not called from the SynchronizationContext
	at com.google.common.base.Preconditions.checkState(Preconditions.java:515)
	at io.grpc.SynchronizationContext.throwIfNotInThisSynchronizationContext(SynchronizationContext.java:134)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult2(ManagedChannelImpl.java:1686)
	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult2(RetryingNameResolver.java:107)
	at io.grpc.NameResolver$Listener2.onAddresses(NameResolver.java:228)
	at org.apache.pekko.grpc.internal.PekkoDiscoveryNameResolver.$anonfun$lookup$1(PekkoDiscoveryNameResolver.scala:56)
	at org.apache.pekko.grpc.internal.PekkoDiscoveryNameResolver.$anonfun$lookup$1$adapted(PekkoDiscoveryNameResolver.scala:53)
```

pekko-grpc PR: https://github.com/apache/pekko-grpc/pull/397

pekko-grpc is written in Scala and we are using Scala Futures when doing lookups asynchronously. grpc-java seems now to require that we use your SynchronizationContext instead.

* Is there anyway to disable the SynchronizationContext requirement?
* Alternatively, is it possible to get the SynchronizationContext from a NameResolver (or its Listener)?

I added an experimental change to pekko-grpc name resolution to add blocking code. This allowed me to avoid this issue but I discovered that we have some tests that still fail because io.grpc is unhappy that we are using Scala Futures. I wouldn't be delighted about the hack in our name resolver either.

### PR DESCRIPTION
**Pull request by kannanjgithub**
When forwarding from Listener onAddresses to Listener2 continue to use onResult and not onResult2 because the latter requires to be called from within synchronization context and it breaks existing code that didn't need to do so when using the old Listener interface.

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java [hunk 1]
```diff
@@ -878,13 +878,14 @@ public String getServiceAuthority() {
...
         @Override
         public void start(Listener2 listener) {
-          listener.onResult2(
-              ResolutionResult.newBuilder()
-                  .setAddressesOrError(
-                      StatusOr.fromValue(
-                          Collections.singletonList(new EquivalentAddressGroup(address))))
-                  .setAttributes(Attributes.EMPTY)
-                  .build());
+          args.getSynchronizationContext().execute(() ->
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java:881]: I don't see why this was added. [`start()` should be called from the synchronization context.](https://grpc.github.io/grpc-java/javadoc/io/grpc/NameResolver.Args.html#getSynchronizationContext())

File: netty/src/main/java/io/grpc/netty/UdsNameResolver.java [hunk 2]
```diff
@@ -58,7 +60,8 @@ private void resolve() {
     List<EquivalentAddressGroup> servers = new ArrayList<>(1);
     servers.add(new EquivalentAddressGroup(new DomainSocketAddress(authority)));
     resolutionResultBuilder.setAddressesOrError(StatusOr.fromValue(servers));
-    listener.onResult2(resolutionResultBuilder.build());
+    args.getSynchronizationContext().execute(() ->
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/UdsNameResolver.java:63]: This was also fine, because start() and refresh() are called from the synchronization context.

File: core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java (hunk 1 above)
Comment (kannanjgithub) [reply core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java]: Removed.

File: netty/src/main/java/io/grpc/netty/UdsNameResolver.java (hunk 2 above)
Comment (kannanjgithub) [reply netty/src/main/java/io/grpc/netty/UdsNameResolver.java]: Removed.

**Comment by ejona86** [comment]
Fixes #11666
