### PR TITLE
netty: Fix client keepalive initialization (again)

### LINKED ISSUE #2828: KeepAliveManager is not apply to ConnectionHandler in netty transport
### What version of gRPC are you using?
GRPC 1.2.0

### What JVM are you using (`java -version`)?
1.8.0_112

### What did you do?
I am try to make `KeepAlive` work with netty transport just now(grpc-java 1.2.0), and after some function test, i think the `KeepAlive` feature still not work functionally.

Debugging the code(io.grpc.netty.NettyClientTransport#start):
image

So, we known the `KeepAliveManager` only make effective in `io.grpc.netty.NettyClientHandler` instance. But the code showing the creation of `io.grpc.netty.NettyClientHandler` always receive a `null` keepAliveManager.

image

Probably because the `keepAliveManager` field is assigning in the end of `io.grpc.netty.NettyClientTransport#start()` call.

Associated commit: https://github.com/grpc/grpc-java/pull/2729: the commit resolve the problem of NPE(https://github.com/grpc/grpc-java/issues/2726)

cc @lukaszx0 @ejona86

### PR DESCRIPTION
**Pull request by ejona86**
d116cc9 fixed the NPE, but the initialization of the manager happened
_after_ newHandler() was called, so a null manager was passed to the
handler.

Fixes #2828 

------

I haven't tested this manually yet. I wanted to send it out to get opinions on whether this is the fix we want. It seems considerably less invasive than some other options we were discussing.

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 1]
```diff
@@ -165,14 +166,20 @@ public ClientStream newStream(MethodDescriptor<?, ?> method, Metadata headers) {
   public Runnable start(Listener transportListener) {
     lifecycleManager = new ClientTransportLifecycleManager(
```
Comment (dapengzhang0) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: did you forget to replace the `lifecycleManager ` field with a local variable? Ditto for the `keepaliveManager` field if it is not exposed to test.

Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: `lifecycleManager` is used in `statusFromFailedFuture`, so it must remain a field. I left `keepaliveManager` because it is used by the test... although I agree that is questionable given the test didn't catch this bug.

Comment (dapengzhang0) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: oops, I see `lifecycleManager` is also used in `statusFromFailedFuture`. But why did you add `lifecycleManager` as an extra argument of `newHandler`?

Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: I thought my comment explained that:
> Only use fields initialized before start()

Since `lifecycleManager` is initialized in `start()`, the flow in `start()` is more obvious when being passed as an argument. Otherwise you could move `newHandler()` within `start()` and not notice that a field is no longer initialized.

Comment (dapengzhang0) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: I see. I think move it inside `start()` is cleaner since it's only one line of code and used only once.

Comment (dapengzhang0) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: I see. I think move it inside `start()` is cleaner since it's only one line of code and used only once.

Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: Good idea. Done.

**Comment by ejona86** [comment]
I've run manual tests and I see keepalive pings!
