### PR TITLE
core: use fakeClock in MessageDeframer tests to fix flaky test

### LINKED ISSUE #5038: MessageDeframerTest is flaky
I observed this test failed on travis more than twice today.

```
io.grpc.internal.MessageDeframerTest > io.grpc.internal.MessageDeframerTest$WithAndWithoutFullStreamCompressionTests.simplePayload[0: useGzipInflatingBuffer=false] FAILED
    expected to be at most: 50
    but was               : 157
        at io.grpc.internal.MessageDeframerTest.checkStats(MessageDeframerTest.java:508)
        at io.grpc.internal.MessageDeframerTest.access$200(MessageDeframerTest.java:73)
        at io.grpc.internal.MessageDeframerTest$WithAndWithoutFullStreamCompressionTests.simplePayload(MessageDeframerTest.java:131)
```

### PR DESCRIPTION
**Pull request by creamsoup**
resolves #5038

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/TransportTracer.java [hunk 1]
```diff
@@ -159,7 +158,6 @@ public FlowControlWindows(long localBytes, long remoteBytes) {
   public static final class Factory {
     private TimeProvider timeProvider;
 
-    @VisibleForTesting
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/TransportTracer.java]: Why this change?
