### PR TITLE
Proper buffer closure when receiving DATA with EOS

### LINKED ISSUE #176: IllegalReferenceCountException for DATA frame with EOS
If a DATA frame is received with EOS set, an attempt is made to read the Netty ByteBuf after it has been closed.

The problem is this line: https://github.com/grpc/grpc-java/blob/ef878187581f5d7d7d43d10f7d4efb229639042f/core/src/main/java/io/grpc/transport/Http2ClientStream.java#L139

Since the buffer was already added to the deframer and the user callback notified, they will then attempt to read from the buffer which has already been closed.  This causes the IllegalReferenceCountException to mask the actual problem with is that a DATA frame was received with EOS set.

### PR DESCRIPTION
**Pull request by nmittler**
The Http2ClientStream should not close the buffer in this case since
it's already been given to the deframer and potentially to the user.

Added cleanup code to MessageDeframer and AbstractClientStream to make
sure that we free the Buffer when appropriate.

Fixes #176

### CODE REVIEW

**Comment by nmittler** [comment]
@ejona86 can you take a look?

File: core/src/main/java/io/grpc/transport/AbstractClientStream.java [hunk 1]
```diff
@@ -121,22 +125,30 @@ protected void inboundHeadersReceived(Metadata.Headers headers) {
...
-    if (inboundPhase() == Phase.HEADERS) {
-      // Have not received headers yet so error
-      inboundTransportError(Status.INTERNAL.withDescription("headers not received before payload"));
-      frame.close();
-      return;
-    }
-    inboundPhase(Phase.MESSAGE);
+    boolean needToCloseFrame = true;
+    try {
+      Preconditions.checkNotNull(frame, "frame");
```
Comment (louiscryan) [inline core/src/main/java/io/grpc/transport/AbstractClientStream.java]: can occur outside of try we can't close a null frame

File: core/src/main/java/io/grpc/transport/MessageDeframer.java [hunk 2]
```diff
@@ -153,14 +153,23 @@ public void request(int numMessages) {
...
    */
   public void deframe(Buffer data, boolean endOfStream) {
-    checkNotClosed();
-    Preconditions.checkNotNull(data, "data");
-    Preconditions.checkState(!this.endOfStream, "Past end of stream");
-    unprocessed.addBuffer(data);
+    boolean needToCloseData = true;
+    try {
+      checkNotClosed();
+      Preconditions.checkNotNull(data, "data");
```
Comment (louiscryan) [inline core/src/main/java/io/grpc/transport/MessageDeframer.java]: can also move checkNotNull out of try here

**Comment by louiscryan** [comment]
LGTM

File: core/src/main/java/io/grpc/transport/MessageDeframer.java (hunk 2 above)
Comment (nmittler) [inline core/src/main/java/io/grpc/transport/MessageDeframer.java]: Done.

File: core/src/main/java/io/grpc/transport/AbstractClientStream.java (hunk 1 above)
Comment (nmittler) [inline core/src/main/java/io/grpc/transport/AbstractClientStream.java]: oof ... done :)

File: core/src/main/java/io/grpc/transport/Http2ClientStream.java [hunk 3]
```diff
@@ -136,8 +136,7 @@ protected void transportDataReceived(Buffer frame, boolean endOfStream) {
       if (endOfStream) {
         // This is a protocol violation as we expect to receive trailers.
         transportError = Status.INTERNAL.withDescription("Recevied EOS on DATA frame");
-        frame.close();
-        inboundTransportError(transportError);
+        inboundTransportError(transportError, true);
```
Comment (ejona86) [inline core/src/main/java/io/grpc/transport/Http2ClientStream.java]: Why did this need to stop delivery? Shouldn't we just have removed the frame.close() line and then the deframer would be closed (closing its frames) in AbstractClientStream.closeListener()?

Comment (nmittler) [inline core/src/main/java/io/grpc/transport/Http2ClientStream.java]: Not stopping delivery was causing the unit test to never report status.  In [transportReportStatus](https://github.com/grpc/grpc-java/blob/2a425090d1fb995464e1df63e88dbaed03635ce1/core/src/main/java/io/grpc/transport/AbstractClientStream.java#L230) when we reach EOS deliveryStalled is false, so we never deliver the status.

Comment (ejona86) [inline core/src/main/java/io/grpc/transport/Http2ClientStream.java]: That's because request() needed to be called in order to read through the partial message. I'll send out a PR that reverts the stop delivery and fixes the test.

Comment (ejona86) [inline core/src/main/java/io/grpc/transport/Http2ClientStream.java]: Wait... We shouldn't need to request another message. Something else isn't right.

Comment (ejona86) [inline core/src/main/java/io/grpc/transport/Http2ClientStream.java]: MessageDeframer should have been stalling sooner than it was. Created https://github.com/grpc/grpc-java/pull/191
