### PR TITLE
core: fix channel.getState(true) will not reconnect

### LINKED ISSUE #4170: channel.getState(true) will not reconnect
The javadoc for ManagedChannel.getState:
_Gets the current connectivity state. Note the result may soon become outdated.
Parameters:requestConnection if true, the channel will try to make a connection if it is currently IDLE_

However, it attempts to connect only if there has not been an open connection already. After disconnect, channel.getState(true) will not attempt to reconnect (state is IDLE).

### What version of gRPC are you using?
1.9.0

### What did you expect to see?
channel.getState(true) should try to reconnect the channel if the state is idle.

### PR DESCRIPTION
**Pull request by dapengzhang0**
resolves #4170

### CODE REVIEW

**Comment by zhangkun83** [comment]
@ejona86, I proposed this solution. Does it sound good to you?

File: core/src/main/java/io/grpc/internal/ManagedChannelImpl.java [hunk 1]
```diff
@@ -821,6 +821,12 @@ public ConnectivityState getState(boolean requestConnection) {
             @Override
             public void run() {
               exitIdleMode();
+              if (subchannelPicker != null) {
+                if (shutdown.get() || panicMode) {
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: This looks unnecessary. I would really hope this is unnecessary. We don't want to be checking these all over the place.

Comment (zhangkun83) [reply core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: We can probably instead check channelStateManager.getState() again here.

Comment (ejona86) [reply core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: If `shutdownNameResolverAndLoadBalancer()` has been called, which is done by both shutdown and panic, then `subchannelPicker` will have been cleared. If in `panicMode`, it will point to a `panicPickResult` which should do nothing. There's no risk in using the `subchannelPicker` incorrectly now, and that should be maintained in the future.

Code _setting_ subchannelPicker could reasonably need to look at those fields. But readers shouldn't need to, as a rule.

Comment (zhangkun83) [reply core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: `shutdownNameResolverAndLoadBalancer()` is called when the channel is terminating, not immediately after `shutdown()`. That said, even when state == SHUTDOWN and `subchannelPicker` is not null, there is no harm calling `requestConnection()`. Yes I agree we can remove this `if`.
