### PR TITLE
services: fix HealthService notifyWatchers

### LINKED ISSUE #11853: HealthStatusManager.setStatus can throw a runtime exception when notifying (already cancelled) watchers
### What version of gRPC-Java are you using? 
1.65.1

### What is your environment?
Jammy Ubuntu running on ARM64, JDK 21.0.4

### What did you expect to see?

No exception. Healthcheck watchers with connections cancelled can/should be ignored.

### What did you see instead?

The follow exception occurs:

```
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled. Use ServerCallStreamObserver.setOnCancelHandler() to disable this exception
	at io.grpc.Status.asRuntimeException(Status.java:525)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:366)
	at io.grpc.protobuf.services.HealthServiceImpl.notifyWatchers(HealthServiceImpl.java:179)
	at io.grpc.protobuf.services.HealthServiceImpl.setStatusInternal(HealthServiceImpl.java:130)
	at io.grpc.protobuf.services.HealthServiceImpl.setStatus(HealthServiceImpl.java:122)
	at io.grpc.protobuf.services.HealthStatusManager.setStatus(HealthStatusManager.java:67)
	...
```

Due to this exception not all Healthcheck watching clients are notified.

### Steps to reproduce the bug

Use HealthStatusManager.setStatus to set the health check status on a running server with a large number of clients, including some recently closed clients. Setting the status too recently after a client has closed its stream will trigger the exception.

### PR DESCRIPTION
**Pull request by JoeCqupt**
fix #11853 

Use ServerCallStreamObserver.setOnCancelHandler() to disable this exception

### CODE REVIEW

**Comment by JoeCqupt** [comment]
@zhangkun83  @carl-mastrangelo  PTAL

File: services/src/main/java/io/grpc/protobuf/services/HealthServiceImpl.java [hunk 1]
```diff
@@ -169,14 +171,30 @@ int numWatchersForTest(String service) {
...
     HealthCheckResponse response = getResponseForWatch(status);
     IdentityHashMap<StreamObserver<HealthCheckResponse>, Boolean> serviceWatchers =
         watchers.get(service);
     if (serviceWatchers != null) {
       for (StreamObserver<HealthCheckResponse> responseObserver : serviceWatchers.keySet()) {
-        responseObserver.onNext(response);
+        try {
+          responseObserver.onNext(response);
+        } catch (Exception e) {
+          logger.log(Level.WARNING, String.format("Exception notify service %s", service), e);
```
Comment (JoeCqupt) [inline services/src/main/java/io/grpc/protobuf/services/HealthServiceImpl.java:196]: Do we need to collect all the exception and throw out finally?

**Review by ejona86 — COMMENTED** [review]
I don't think we want to catch the exception. I think we want to avoid the exception by using `setOnCancelHandler()` as mentioned in the error to update `watchers`. That will release resources as soon as the RPC is cancelled.

**Review by ejona86 — APPROVED** [review]

**Review by kannanjgithub — APPROVED** [review]

**Comment by ejona86** [comment]
@JoeCqupt, thank you!
