### PR TITLE
okhttp: Fix okio 2.x API incompatibility

### LINKED ISSUE #8004: Okio 2.x incompatibilities
### What version of gRPC-Java are you using?
1.36.0

### What is your environment?

Linux and macOS, built with Bazel from sources using the tools provided in this repo, rather than through a Maven dependency. The same repo contains an Android app using OkHttp3 (4.9.1), which depends on Okio 2.8+.

### What did you expect to see?
gRPC-Java should build just fine.

### What did you see instead?
gRPC-Java either overrides the dependencies and force Okio 1.x (which causes issues with OkHttp3, e.g. https://github.com/square/okhttp/issues/5378), or fails to compile when using Okio 2.8+. For example:
https://github.com/grpc/grpc-java/blob/b2e475712d67a0660e1d16d6465a4ccb9b8a6b40/okhttp/src/main/java/io/grpc/okhttp/OkHttpReadableBuffer.java#L43
`buffer.readByte()` now throws an exception, which causes a compilation error as it's not caught or thrown by `readUnsignedByte()`. This points to incompatibilities between Okio 1.x and 2.x, and makes adopting gRPC-Java in any repo using "recent" (mid-2019...) versions of OkHttp an issue. OkHttp3 has been depending on Okio 2.x since its 4.0.0 release.

### Steps to reproduce the bug

Depend on both OkHttp3 4.x and gRPC-Java at the same time.

### PR DESCRIPTION
**Pull request by ejona86**
okio 2.x is ABI compatible with 1.x but not API compatible. This hasn't
been a problem as users use binaries from Maven Central so the ABI
compatibility is the important part. However, when building with Bazel
the API compatibily is the important part.

Tested with okio 2.10.0

Fixes #8004

CC @Kernald

### CODE REVIEW

**Comment by Kernald** [comment]
I confirm that this fixes #8004 for me - thanks again!

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpReadableBuffer.java [hunk 1]
```diff
@@ -40,9 +40,16 @@ public int readableBytes() {
 
   @Override
   public int readUnsignedByte() {
-    return buffer.readByte() & 0x000000FF;
+    try {
+      fakeEofExceptionMethod(); // Okio 2.x can throw EOFException from readByte()
```
Comment (voidzcy) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpReadableBuffer.java:44]: Err, a bit ugly...  Why not just put `return buffer.readByte() & 0x000000FF;` into the helper method that does the throw?

**Review by voidzcy — APPROVED** [review]

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpReadableBuffer.java (hunk 1 above)
Comment (ejona86) [reply okhttp/src/main/java/io/grpc/okhttp/OkHttpReadableBuffer.java:44]: I also considered `if (false) throw new EOFException()`. I could wrap it, but I'm not wild to add a level of indirection just to make the compiler happy here. While this is ugly, it is clear and it is obvious when it is no longer necessary.

Comment (ejona86) [reply okhttp/src/main/java/io/grpc/okhttp/OkHttpReadableBuffer.java:44]: Also, with the helper method you really have to read the comment to see that the `throws` was on purpose. Here, it is _very clear_ that something strange is going on while at the same time having no impact on behavior. The comment just explains _why_, not "WATCH OUT!"

**Review by voidzcy — APPROVED** [review]
