### PR TITLE
binder: Dispatch transact() calls on an Executor when FLAG_ONEWAY would not be respected.

### LINKED ISSUE #8914: binder: Deadlock due to unexpected re-entrancy of transactions on process-local Binder
BinderTransport locking was written under the assumption that calls to `IBinder#transact()` enqueued the Parcel for delivery to the peer and returned immediately. However, Android guarantees the unique object identity of IBinder instances within a process. And so when a client creates a Channel to a Server/Service within its own process, `BinderClientTransport.outgoingBinder == BinderServerTransport.outgoingBinder`. `android.os.Binder#transact()` on that object is implemented not as a system call to the binder driver but as a direct call to its own onTransact() method.

This is a problem because `BinderTransport#handleTransaction()` holds its 'this' lock while calling `outgoingBinder.transact()` in multiple places. If two peer instances of `BinderClientTransport` and `BinderServerTransport` are running `handleTransaction()` on different threads at the same time, they can each end up holding their own lock while waiting (forever) for the other's.

### Steps to reproduce one instance of this bug
- Use `BinderChannelBuilder` to create a Channel to an `android.app.Service` hosted by the same process
- Have both the client and server repeatedly send messages to each other around the same time from different threads

### What did you expect to see?
No deadlock

### What did you see instead?
Example deadlock, via `sendAcknowledgeBytes()`:

```
"xxx" prio=5 tid=25 Blocked
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x12c40c00 self=0xb400006e9ce43460
  | sysTid=24211 nice=10 cgrp=background sched=0/0 handle=0x6caac7dcb0
  | state=S schedstat=( 6776198013 56795686488 17245 ) utm=455 stm=221 core=1 HZ=100
  | stack=0x6caab7a000-0x6caab7c000 stackSize=1039KB
  | held mutexes=
  **at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:449)**
  **- waiting to lock <0x04f85343> (a io.grpc.binder.internal.BinderTransport$BinderClientTransport) held by thread 64**
  at io.grpc.binder.internal.LeakSafeOneWayBinder.onTransact(LeakSafeOneWayBinder.java:63)
  at android.os.Binder.transact(Binder.java:1157)
  at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:514)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  <OR> at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:515)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  <OR> at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:516)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  <OR> at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:517)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  **- locked <0x0f79cc83> (a io.grpc.binder.internal.BinderTransport$BinderServerTransport)**
  **at io.grpc.binder.internal.LeakSafeOneWayBinder.onTransact(LeakSafeOneWayBinder.java:63)**
  at android.os.Binder.transact(Binder.java:1157)
  at io.grpc.binder.internal.BinderTransport.sendTransaction(BinderTransport.java:402)
  at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:261)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  <OR> at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:262)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  <OR> at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:263)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  <OR> at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:264)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  at io.grpc.binder.internal.Outbound$ClientOutbound.sendSingleMessageAndHalfClose(Outbound.java:381)
  at io.grpc.binder.internal.SingleMessageClientStream.halfClose(SingleMessageClientStream.java:105)
  <OR> at io.grpc.binder.internal.Outbound$ClientOutbound.sendSingleMessageAndHalfClose(Outbound.java:382)
  at io.grpc.binder.internal.SingleMessageClientStream.halfClose(SingleMessageClientStream.java:105)

"yyy" prio=5 tid=64 Blocked
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x12d41100 self=0xb400006e9cf25400
  | sysTid=16535 nice=10 cgrp=background sched=0/0 handle=0x6ca795fcb0
  | state=S schedstat=( 84994090 239215329 419 ) utm=5 stm=2 core=1 HZ=100
  | stack=0x6ca785c000-0x6ca785e000 stackSize=1039KB
  | held mutexes=
  **at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:449)**
  **- waiting to lock <0x0f79cc83> (a io.grpc.binder.internal.BinderTransport$BinderServerTransport) held by thread 25**
  at io.grpc.binder.internal.LeakSafeOneWayBinder.onTransact(LeakSafeOneWayBinder.java:63)
  at android.os.Binder.transact(Binder.java:1157)
  at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:514)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  <OR> at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:515)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  <OR> at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:516)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  <OR> at io.grpc.binder.internal.BinderTransport.sendAcknowledgeBytes(BinderTransport.java:517)
  at io.grpc.binder.internal.BinderTransport.handleTransaction(BinderTransport.java:477)
  **- locked <0x04f85343> (a io.grpc.binder.internal.BinderTransport$BinderClientTransport)**
  **at io.grpc.binder.internal.LeakSafeOneWayBinder.onTransact(LeakSafeOneWayBinder.java:63)**
  at android.os.Binder.transact(Binder.java:1157)
  at io.grpc.binder.internal.BinderTransport.sendTransaction(BinderTransport.java:402)
  at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:261)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  <OR> at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:262)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  <OR> at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:263)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  <OR> at io.grpc.binder.internal.Outbound.sendInternal(Outbound.java:264)
  at io.grpc.binder.internal.Outbound.send(Outbound.java:212)
  at io.grpc.binder.internal.Outbound$ServerOutbound.sendSingleMessageAndClose(Outbound.java:460)
  at io.grpc.binder.internal.SingleMessageServerStream.close(SingleMessageServerStream.java:102)
  <OR> at io.grpc.binder.internal.Outbound$ServerOutbound.sendSingleMessageAndClose(Outbound.java:461)
  at io.grpc.binder.internal.SingleMessageServerStream.close(SingleMessageServerStream.java:102)
  \- locked <0x0f7ee7bb> (a io.grpc.binder.internal.Outbound$ServerOutbound)
  at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:223)
  at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:207)
  at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)
```

### PR DESCRIPTION
**Pull request by jdcormie**
Fixes #8914

### CODE REVIEW

File: binder/src/main/java/io/grpc/binder/internal/BinderTransport.java [hunk 1]
```diff
@@ -326,39 +326,30 @@ final void sendSetupTransaction() {
...
 
   @GuardedBy("this")
-  final void sendSetupTransaction(IBinder iBinder) {
-    Parcel parcel = Parcel.obtain();
-    try {
-      parcel.writeInt(WIRE_FORMAT_VERSION);
-      parcel.writeStrongBinder(incomingBinder);
-      if (!iBinder.transact(SETUP_TRANSPORT, parcel, null, IBinder.FLAG_ONEWAY)) {
-        shutdownInternal(
-            Status.UNAVAILABLE.withDescription("Failed sending SETUP_TRANSPORT transaction"), true);
```
Comment (markb74) [inline binder/src/main/java/io/grpc/binder/internal/BinderTransport.java:336]: Just confirming that this case will become an "INTERNAL" error now.

I think that's ok since we don't expect it, but I also want to be paranoid about how OEMs might have changed edge-case semantics of this API.

File: binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    checkState(parcel != null, "get() after close()/release()");
+    return parcel;
+  }
+
+  /**
+   * Returns the wrapped {@link Parcel} and releases ownership of it.
+   *
+   * @throws IllegalStateException if ownership has already been given up by {@link #release()}
+   */
+  public Parcel release() {
```
Comment (markb74) [inline binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java:44]: getWithRelease? (not a strong opinion though).

File: binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+      parcel = null;
+    }
+  }
+
+  /**
+   * Returns true iff this container no longer owns a {@link Parcel}.
+   *
+   * <p>{@link #isEmpty()} is true after all call to {@link #close()} or {@link #release()}.
+   */
+  public boolean isEmpty() {
```
Comment (markb74) [inline binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java:68]: @VisibleForTesting maybe?  (Since it's not actually used otherwise).

Also maybe isReleased instead?

**Review by markb74 — APPROVED** [review]
Thanks so much for this!

File: binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+import android.os.RemoteException;
+import io.grpc.internal.SerializingExecutor;
+import java.util.concurrent.Executor;
+import java.util.logging.Level;
+import java.util.logging.Logger;
+
+/**
+ * Wraps an {@link IBinder} with a safe and uniformly asynchronous transaction API.
+ *
+ * <p>The android.os.Binder implementation of {@link IBinder} is problematic for clients that want
```
[the remark this answers is not in the document]
Comment (jdcormie) [reply binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java]: Good point. Done but in somewhat different words.

File: binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+  }
+
+  /**
+   * Returns a new instance of {@link OneWayBinderProxy} that wraps {@code iBinder}.
+   *
+   * @param iBinder the binder to wrap
+   * @param executor a non-direct Executor used to dispatch calls to onTransact(), if necessary
+   * @return a new instance of {@link OneWayBinderProxy}
+   */
+  public static OneWayBinderProxy wrap(IBinder iBinder, Executor executor) {
```
[the remark this answers is not in the document]
Comment (jdcormie) [reply binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java]: done

File: binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java (hunk 3 above)
Comment (jdcormie) [reply binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java:73]: Added @VisibleForTesting. isReleased() isn't quite accurate because it returns true post-close() as well.

File: binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java (hunk 2 above)
Comment (jdcormie) [reply binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java:45]: I think I prefer just release() because at a glance getWithRelease() looks too similar to get()

File: binder/src/main/java/io/grpc/binder/internal/BinderTransport.java (hunk 1 above)
Comment (jdcormie) [reply binder/src/main/java/io/grpc/binder/internal/BinderTransport.java:336]: Yes you are right this will be a small behavior change. 

According to the AOSP source code, the only way BinderProxy.transact() can return false (which we now turn into a RemoteException) is if there's something internally wrong with the iBinder or parcel arguments. Feels like INTERNAL is a more accurate description of this.

File: binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+                // would have if the android.os.Binder was in another process.
+                logger.log(Level.FINEST, "A oneway transaction was not understood - ignoring");
+              }
+            } catch (Exception e) {
+              // onTransact() in our same process threw this. Ignore it, just like Android would
+              // have if the android.os.Binder was in another process.
+              logger.log(Level.FINEST, "A oneway transaction threw - ignoring", e);
+            }
+          });
+      wrappedParcel.release();
```
Comment (ejona86) [inline binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java:139]: @jdcormie, @markb74, this `release()` is suspicious. Should it be done within the executor instead?

Comment (jdcormie) [reply binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java:139]: The OneWayBinderProxy contract says that callers of transact() must unconditionally call close() on 'wrappedParcel'. If we called release() inside the Runnable, the non-thread-safe wrappedParcel might be accessed concurrently from multiple threads.

The idea here is to transfer ownership to the Runnable as a raw Parcel in an Exception safe way. There are two cases. Either:
1) execute() returns successfully, the Runnable promises to eventually recycle() 'parcel' in transactAndRecycleParcel(), and we release ownership of 'wrappedParcel' on the very next line.
OR
2) execute() throws RejectedExecutionException. In this case, the Runnable never runs and wrappedParcel.release() is never called so the caller of OneWayBinderProxy#transact() will recycle the Parcel when it calls ParcelHolder#close() in its finally.

LMK if you see a problem or have a better suggestion.

Comment (ejona86) [reply binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java:139]: Ah, `release()` is not like a `close()`. It steals the ownership instead of releasing the object. (The holder releases ownership because it is transferring to the caller; the caller is not releasing ownership overall which is what I'm used to with a release method, where release is similar to unref/close.)

I think this is fine then. Thank you!
