### PR TITLE
xds: fix xDS HTTP CONNECT's transport socket name bug

### LINKED ISSUE #12739: xDS HTTP Connect: Supported transport socket name parsing bug
There's a bug in the logic that identifies supported `Http11ProxyUpstreamTransport` transport sockets. Input:

```json5
{
  "versionInfo": "1769538225641032355",
  "resources": [{
    "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
    "name": "cloud-internal-istio-staging:cloud_mp_357736519905_4795705583231421394",
    "type": "EDS",
    // ...
    "transportSocket": {
      "name": "envoy.transport_sockets.http_11_proxy",
      "typedConfig": {
        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.http_11_proxy.v3.Http11ProxyUpstreamTransport"
      }
    },
  }],
  "typeUrl": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
  "nonce": "1"
}
```

The current logic compares `TransportSocket`'s name ([proto](https://github.com/envoyproxy/envoy/blob/d6120f3c769e70c988ddcc5c7e9cbc2737b5f63c/api/envoy/config/core/v3/base.proto#L583)) with the `TRANSPORT_SOCKET_NAME_HTTP11_PROXY` constant:

https://github.com/grpc/grpc-java/blob/15788b772910e3d437ce12cd33fb783ba266bbb7/xds/src/main/java/io/grpc/xds/XdsClusterResource.java#L263-L267

However, the constant itself contains the `typed_config` (Any) type, not the name: https://github.com/grpc/grpc-java/blob/15788b772910e3d437ce12cd33fb783ba266bbb7/xds/src/main/java/io/grpc/xds/XdsClusterResource.java#L83-L85

Java expected: `type.googleapis.com/envoy.extensions.transport_sockets.http_11_proxy.v3.Http11ProxyUpstreamTransport`
Actual xds config: `envoy.transport_sockets.http_11_proxy`.'

## Implementation details

While the simplest approach is to replaces the value of `TRANSPORT_SOCKET_NAME_HTTP11_PROXY` constant with `envoy.transport_sockets.http_11_proxy`, we should not be using extension names to identify supported sockets (or any other wrapped  `typed_config`s for this matter).

The proper fix should change the logic to inspecting `transportSocket.typed_config.type` instead of the name. 

Quoting @markdroth:

> All extension points in xDS should use the protobuf type inside of the Any field to determine which extension to use, not the name. 
>
> The fact that extensions have names is essentially a historical artifact in almost all cases, because Envoy originally used the names instead of the protobuf types to identify the extensions, but they've long since switched to using the protobuf types instead.
>
> The only case I can think of offhand where an extension name is still used for something is HTTP filters.  But in that case, it's a filter instance name, not the name of the filter implementation.  It's used to match up top-level filter instances with the corresponding override configs in various typed_per_filter_config fields.  The name is useful here because it's totally possible to have two instances of the same filter implementation, in which case they'd both have the same protobuf message type but they'd have two different names, and those names could be used in typed_per_filter_config to indicate which of the two a given override config is associated with.

### PR DESCRIPTION
**Pull request by shivaspeaks**
fixes https://github.com/grpc/grpc-java/issues/12739

### CODE REVIEW

**Comment by shivaspeaks** [comment]
Note: I will not pollute this PR with `TRANSPORT_SOCKET_NAME_TLS` changes. I'll keep this focused on bug fix for HTTP CONNECT.

File: xds/src/main/java/io/grpc/xds/XdsClusterResource.java [hunk 1]
```diff
@@ -261,14 +261,14 @@ private static StructOrError<CdsUpdate.Builder> parseNonAggregateCluster(
     TransportSocket transportSocket = cluster.getTransportSocket();
 
     if (hasTransportSocket && !TRANSPORT_SOCKET_NAME_TLS.equals(transportSocket.getName())
-        && !(isEnabledXdsHttpConnect
-        && TRANSPORT_SOCKET_NAME_HTTP11_PROXY.equals(transportSocket.getName()))) {
+        && !(isEnabledXdsHttpConnect && TYPE_URL_HTTP11_PROXY_UPSTREAM_TRANSPORT
+        .equals(transportSocket.getTypedConfig().getTypeUrl()))) {
```
Comment (ejona86) [inline xds/src/main/java/io/grpc/xds/XdsClusterResource.java]: Because you're working with an Any, this would normally be written as `transportSocket.getTypedConfig().is(Http11ProxyUpstreamTransport.class)`.

**Review by ejona86 — APPROVED** [review]
