### PR TITLE
netty: detect when ALPN was not used. Fixes #522

### LINKED ISSUE #522: Netty Client does not detect when ALPN was not used
When I tried to reproduce the APLN silence failure, I expected the following change fails our tests, but not, all tests still passed. 
```
diff --git a/interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java b/interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
index 504c815..2ae8160 100644
--- a/interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
+++ b/interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
@@ -37,6 +37,7 @@ import io.grpc.transport.netty.GrpcSslContexts;
 import io.grpc.transport.netty.NettyChannelBuilder;
 import io.grpc.transport.netty.NettyServerBuilder;
 
+import io.netty.handler.ssl.ApplicationProtocolConfig;
 import org.junit.AfterClass;
 import org.junit.BeforeClass;
 import org.junit.runner.RunWith;
@@ -74,7 +75,8 @@ public class Http2NettyTest extends AbstractTransportTest {
       return NettyChannelBuilder
           .forAddress(TestUtils.testServerAddress(serverPort))
           .sslContext(GrpcSslContexts.forClient().trustManager(
-                  TestUtils.loadCert("ca.pem")).build())
+                  TestUtils.loadCert("ca.pem"))
+              .applicationProtocolConfig(ApplicationProtocolConfig.DISABLED).build())
           .build();
     } catch (Exception ex) {
       throw new RuntimeException(ex);
```
The problem itself is not a big deal, but investigating it may expose some hidden bugs.

### PR DESCRIPTION
**Pull request by buchgr**
For client + server.

However, when connecting to a server that does not support ALPN, the TLS Handshake fails (on the client) and the client dies with a `SSLException: engine closed`. I believe this is a bug in Netty + OpenSSL, as it does not appear to happen when using JDK + Jetty. I am looking into it right now.

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/GrpcSslContexts.java [hunk 1]
```diff
@@ -165,4 +168,18 @@ private static ApplicationProtocolConfig selectApplicationProtocolConfig(SslProv
...
+  static void ensureAlpnAndH2Enabled(ApplicationProtocolNegotiator alpnNegotiator) {
+    checkArgument(alpnNegotiator != null, "ALPN must be configured");
+    checkArgument(alpnNegotiator.protocols() != null && !alpnNegotiator.protocols().isEmpty(),
+        "ALPN must be enabled and list HTTP/2 as a supported protocol.");
+    for (String protocol : alpnNegotiator.protocols()) {
+      if (HTTP2_VERSIONS.contains(protocol)) {
+        return;
+      }
+    }
+    checkArgument(false, "This ALPN config does not support HTTP/2. Expected one of "
```
Comment (carl-mastrangelo) [inline netty/src/main/java/io/grpc/netty/GrpcSslContexts.java]: Optional: a plain old throw would work here.

**Comment by carl-mastrangelo** [comment]
@buchgr LGTM, Thanks for doing this.

**Comment by buchgr** [comment]
@carl-mastrangelo @ejona86 I assume I should still hold off merging PRs? Ping me when it's safe to merge again.

**Comment by buchgr** [comment]
can this be merged, as I saw other PRs have been merged?

File: netty/src/main/java/io/grpc/netty/GrpcSslContexts.java [hunk 2]
```diff
@@ -165,4 +168,18 @@ private static ApplicationProtocolConfig selectApplicationProtocolConfig(SslProv
         throw new IllegalArgumentException("Unsupported provider: " + provider);
     }
   }
+
+  static void ensureAlpnAndH2Enabled(ApplicationProtocolNegotiator alpnNegotiator) {
+    checkArgument(alpnNegotiator != null, "ALPN must be configured");
+    checkArgument(alpnNegotiator.protocols() != null && !alpnNegotiator.protocols().isEmpty(),
+        "ALPN must be enabled and list HTTP/2 as a supported protocol.");
+    for (String protocol : alpnNegotiator.protocols()) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/GrpcSslContexts.java]: As an option, we could go ahead and get rid of the list of HTTP2 versions and only have one. Then we could use protocols().contains().

File: netty/src/main/java/io/grpc/netty/GrpcSslContexts.java (hunk 1 above)
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/GrpcSslContexts.java]: +1

**Comment by ejona86** [comment]
@buchgr LGTM.

It's now fine to merge PRs, as of a ~2 hours ago.

**Comment by buchgr** [comment]
Test failure on Windows seems unrelated.
```
io.grpc.netty.NettyTransportTest > earlyServerClose_withServerHeaders FAILED
    java.io.IOException: Failed to bind

        Caused by:
        java.net.BindException: Address already in use: bind

    java.lang.AssertionError
```
