### PR TITLE
Deflake CallOptionsTest.withDeadlineNanoTime

### LINKED ISSUE #1645: CallOptionsTest.withDeadlineNanoTime is flaky
```
io.grpc.CallOptionsTest > withDeadlineNanoTime FAILED
    java.lang.AssertionError: <-25128839 ns from now> and <-1322031 ns from now> should have been within <20000000ns> of each other
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
        at com.google.common.truth.Subject.failWithRawMessage(Subject.java:381)
        at io.grpc.testing.DeadlineSubject.access$400(DeadlineSubject.java:52)
        at io.grpc.testing.DeadlineSubject$1.of(DeadlineSubject.java:81)
        at io.grpc.CallOptionsTest.withDeadlineNanoTime(CallOptionsTest.java:161)
```

As seen (may have been restarted):
https://travis-ci.org/grpc/grpc-java/jobs/121289248
https://travis-ci.org/grpc/grpc-java/jobs/121487416
(<-33620603 ns from now> and <-2319629 ns from now> should have been within <20000000ns> of each other)

### PR DESCRIPTION
**Pull request by ejona86**
Two prong approach: increase the tolerance and decrease code between
nanoTime() calls.

Fixes #1645

### CODE REVIEW

File: core/src/test/java/io/grpc/CallOptionsTest.java [hunk 1]
```diff
@@ -150,15 +150,19 @@ public void toStringMatches_withDeadline() {
   }
 
   @Test
-  @SuppressWarnings("deprecation")
+  @Deprecated
```
Comment (carl-mastrangelo) [inline core/src/test/java/io/grpc/CallOptionsTest.java]: I don't think this is right.   `@Deprecated`  is for telling API users not to call the method, the suppress warnings is to tell the ide/compiler to just ignore it for now.  The latter is the right thing for a unit test.

Comment (ejona86) [inline core/src/test/java/io/grpc/CallOptionsTest.java]: I don't quite agree, but reverted.

**Comment by carl-mastrangelo** [comment]
@ejona86 LGTM

**Comment by ejona86** [comment]
Some recent failures have been > 30 ms, so this wasn't enough. I'm bumping it to 50 ms.

**Comment by carl-mastrangelo** [comment]
Still LGTM

**Comment by ejona86** [comment]
And to be clear, those recent failures were just over 30 ms _before_ this change. So the code reorganization have prevented them after this change. But I don't want to see this flake, thus the multiple approaches.
