### PR TITLE
netty: Eliminate buffer release when there is an error as caller still owns the buffer.

### LINKED ISSUE #10255: NettyAdaptiveCumulator incorrectly releases `ByteBuf in` twice
### What version of gRPC-Java are you using?

Version 1.51.0 introduced this issue.

### What is your environment?
Any

### Steps to reproduce the bug

```java

io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.read(Http2ConnectionHandler.java:539)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:839)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.grpc.netty.NettyAdaptiveCumulator.cumulate(NettyAdaptiveCumulator.java:95)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
	... 33 common frames omitted

```

In the case below, NettyAdaptiveCumulator incorrectly releases `ByteBuf in` twice.

* io.grpc.netty.NettyAdaptiveCumulator.cumulate(ByteBufAllocator alloc, ByteBuf cumulation, ByteBuf in) 

* cumulation: UnpooledHeapByteBuf(ridx: 9, widx: 14, cap: 14/14) 
* in:  UnpooledHeapByteBuf(ridx: 0, widx: 8, cap: 8/8)

---

* The finally block of `NettyAdaptiveCumulator#mergeWithCompositeTail` is released once
* Release again in the finally block of `NettyAdaptiveCumulator#cumulate`

### PR DESCRIPTION
**Pull request by larry-safran**
Fixes #10255

### CODE REVIEW

**Review by sergiitk — CHANGES_REQUESTED** [review]
I don't think this is right. I was very thorough working on this code. This change contradicts the comments in the test:

```java
// Input must be released unless its ownership has been to the composite cumulation.
assertEquals(1, in.refCnt());
```

Not releasing input buffer in `finally` is dangerous.
I need more time to look at the reported issue and understand the consequences of this change.

**Comment by larry-safran** [comment]
@sergiitk after our discussion yesterday are you now okay with this?

File: netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java [hunk 1]
```diff
@@ -204,16 +204,9 @@ static void mergeWithCompositeTail(
       composite.addFlattenedComponents(true, newTail);
       // New tail's ownership transferred to the composite buf.
       newTail = null;
-      in.release();
-      in = null;
-      // Restore the reader. In case it fails we restore the reader after releasing/forgetting
-      // the input and the new tail so that finally block can handles them properly.
       composite.readerIndex(prevReader);
+      in.release(); // Successful so took over ownership of in
```
Comment (sergiitk) [inline netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java:208]:
```suggestion
      // Input buffer was successfully merged with the tail.
      // Must be the last line in the try because we release it only on success.
      in.release();
```

File: netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java [hunk 2]
```diff
@@ -582,6 +583,7 @@ public CompositeByteBuf addFlattenedComponents(boolean increaseWriterIndex,
         assertEquals(0, compositeRo.numComponents());
       } finally {
         compositeRo.release();
+        in.release();
```
Comment (sergiitk) [inline netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java:586]: I think we should keep it above`fail("Cumulator didn't throw");`

File: netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java [hunk 3]
```diff
@@ -546,6 +546,7 @@ public CompositeByteBuf addFlattenedComponents(boolean increaseWriterIndex,
         assertEquals(0, compositeThrows.numComponents());
       } finally {
         compositeThrows.release();
+        in.release();
```
Comment (sergiitk) [inline netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java:549]: I think we should keep it above`fail("Cumulator didn't throw");`

File: netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java (hunk 2 above)
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java:586]: We need to release when there is an error since the new paradigm is that only successes change ownership.

File: netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java (hunk 3 above)
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java:549]: It is expected the in the case of an error that the ownership remained with the calling method so it is this method's responsibility to do the release.

File: netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java (hunk 2 above)
Comment (sergiitk) [reply netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java:586]: Discussed IRL, we do want to move it, but to another place

**Review by sergiitk — APPROVED** [review]
Awesome! Thank you so much for catching this!
