### PR TITLE
netty: GOAWAY should trigger transportShutdown

### LINKED ISSUE #1359: Netty should call transportShutdown on GOAWAY
This will cause `TransportSet` to divert new traffic away from the transport which would prevent many failed RPCs.

### PR DESCRIPTION
**Pull request by ejona86**
Long-lived streams or lengthy RPCs can keep the transport open for
minutes after a GOAWAY is received. Previously, during this time any new
RPCs would fail with a message like:

> Cannot create stream 5 since this endpoint has received a GOAWAY frame
> with last stream id 3

All usages of goAwayStatus were replaced with lifecycleManager. Although
note that previously goAwayStatus() would never return null because it
would generate a Status if the current field was null.
getShutdownStatus() does not have this feature, so some code was
rearranged to guarantee the Status is non-null before retrieving it.

The listener handling was simplified by 1) avoiding the need for
thread-safety and 2) moving state keeping into a small class for easy
comprehensibility and simplified usage in tests.

NettyClientTransport.shutdown() no longer calls transportShutdown()
because it lies (because the message can be delayed for quite some time)
and because it was the only usage of lifecycleManager not on the event
loop.

Fixes #1359

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+ * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+ */
+
+package io.grpc.netty;
+
+import io.grpc.Status;
+import io.grpc.internal.ManagedClientTransport;
+
+/** Maintainer of transport lifecycle status. */
+final class ClientTransportLifecycleManager {
```
Comment (nmittler) [inline netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java]: Are the methods in this class always called by the event loop or do we have to worry about concurrency?

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java [hunk 2]
```diff
@@ -145,18 +142,7 @@ static NettyClientHandler newHandler(Http2Connection connection,
     frameWriter = new Http2OutboundFrameLogger(frameWriter, frameLogger);
 
     StreamBufferingEncoder encoder = new StreamBufferingEncoder(
-        new DefaultHttp2ConnectionEncoder(connection, frameWriter)) {
```
Comment (nmittler) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: why this change?

File: netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+    }
+    transportReady = true;
+    listener.transportReady();
+  }
+
+  public void notifyShutdown(Status s) {
+    if (transportShutdown) {
+      return;
+    }
+    transportReady = true; // Inhibit ready callback
```
Comment (nmittler) [inline netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java]: Rather than setting `transportReady = true`, why not just add conditions to `notifyReady` to return if `transportShutdown`?

File: netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+    shutdownStatus = s;
+    shutdownThrowable = s.asException();
+    listener.transportShutdown(s);
+  }
+
+  public void notifyTerminated(Status s) {
+    if (transportTerminated) {
+      return;
+    }
+    notifyShutdown(s);
```
Comment (nmittler) [inline netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java]: do you want to set `transportTerminated = true` before calling `notifyShutdown`?

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java (hunk 2 above)
Comment (nmittler) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: nm ... looks like the frameListener is doing it now

**Comment by nmittler** [comment]
@ejona86 Looks great! just a couple comments/questions

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java (hunk 2 above)
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: Your question was still valid. Before `listener` was _only_ used in the encoder here. However, `lifecycleManager` must be a field because it is called at other times. So instead of using a `final`-based closure here and the field, I just moved it to `FrameListener.onSettingsRead` which seemed cleaner as well.

File: netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java (hunk 1 above)
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java]: I have a comment in `NettyClientTransport` reminding us that it isn't thread-safe:
> /** Since not thread-safe, may only be used from event loop. */

I only had to make one minor change to shutdown() in order to make all calls to it occur on the event loop.

File: netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java (hunk 3 above)
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java]: Sure. Done.

File: netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java (hunk 4 above)
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java]: Done.

**Comment by ejona86** [comment]
@nmittler PTAL

**Comment by nmittler** [comment]
@ejona86 LGTM ... ship it!
