### PR TITLE
netty: Handle write queue promise failures

### LINKED ISSUE #10849: NettyClientStream does not handle netty write data failure promise
### What version of gRPC-Java are you using?
1.26.0 (latest version has the same problem)

### What is your environment?

linux, jdk8

### What did you expect to see?
grpc client throw a exception when netty write data frame failed

### What did you see instead?
grpc client blocking stub hangs forever when netty StreamBufferingEncoder return an unexpected failure promise

### Steps to reproduce the bug
when the client http2 stream id is exhausted(using Integer.MAX_VALUE), netty codec-http2 [StreamBufferingEncoder#writeData](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/StreamBufferingEncoder.java#L209) return a failure promise unexpectly , more details in https://github.com/netty/netty/issues/13805
but grpc [NettyClientStream](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L188)  does not report the failure future, and the grpc blocking stub will block forever.

### PR DESCRIPTION
**Pull request by sergiitk**
Handles Netty write frame failures caused by issues in the Netty itself.

Normally we don't need to do anything on frame write failures because the cause of a failed future would be an IO error that resulted in the stream closure.  Prior to this PR we treated these issues as a noop, except the initial headers write on the client side.

However, a case like netty/netty#13805 (a bug in generating next stream id) resulted in an unclosed stream on our side.
This PR adds write frame future failure handlers that ensures the stream is cancelled, and the cause is propagated via Status.

Fixes #10849

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java [hunk 1]
```diff
@@ -96,14 +96,18 @@ private class Sink implements AbstractServerStream.Sink {
...
-        writeQueue.enqueue(
-            SendResponseHeadersCommand.createHeaders(
-                transportState(),
-                Utils.convertServerHeaders(headers)),
-            flush);
+        writeHeadersInternal(headers, flush);
       }
     }
 
+    private void writeHeadersInternal(Metadata headers, boolean flush) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyServerStream.java:103]: Could we just do this inline?

We have the `*Internal` methods because 1) some methods were pretty large and when adding the PerfMark tracing we didn't want to change the entire method's indentation and 2) some methods had lots of indentation already.

File: netty/src/main/java/io/grpc/netty/NettyClientStream.java [hunk 2]
```diff
@@ -183,17 +183,31 @@ private void writeFrameInternal(
...
+              if (future.isSuccess() && transportState().http2Stream() == null) {
+                return;
+              }
+
+              if (future.isSuccess()) {
+                // Remove the bytes from outbound flow control, optionally notifying
+                // the client that they can send more bytes.
+                transportState().onSentBytes(numBytes);
+                NettyClientStream.this.getTransportTracer().reportMessageSent(numMessages);
+              } else if (isReady()) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientStream.java:198]: As discussed offline, `isReady()` will give false negatives, because of flow control.

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java (hunk 1 above)
Comment (sergiitk) [reply netty/src/main/java/io/grpc/netty/NettyServerStream.java]: Done. I've inlined writeFrameInternal as well - it ended up to be small too.

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java [hunk 3]
```diff
@@ -96,48 +96,46 @@ private class Sink implements AbstractServerStream.Sink {
...
+        Preconditions.checkArgument(numMessages >= 0);
+        ByteBuf bytebuf = ((NettyWritableBuffer) frame).bytebuf().touch();
+        final int numBytes = bytebuf.readableBytes();
+        // Add the bytes to outbound flow control.
+        onSendingBytes(numBytes);
+        writeQueue.enqueue(new SendGrpcFrameCommand(transportState(), bytebuf, false), flush)
+            .addListener((ChannelFutureListener) future -> {
               // Remove the bytes from outbound flow control, optionally notifying
               // the client that they can send more bytes.
+              // TODO(sergiitk): should onSentBytes be called only on success?
```
Comment (sergiitk) [inline netty/src/main/java/io/grpc/netty/NettyServerStream.java:119]: TODO: discuss with @ejona86

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java [hunk 4]
```diff
@@ -96,48 +96,46 @@ private class Sink implements AbstractServerStream.Sink {
...
               transportState().onSentBytes(numBytes);
               if (future.isSuccess()) {
+                // TODO(sergiitk): when all moved to transport state, transportTracer becomes unused
```
Comment (sergiitk) [inline netty/src/main/java/io/grpc/netty/NettyServerStream.java:122]: TODO: discuss with @ejona86

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java [hunk 5]
```diff
@@ -206,6 +204,29 @@ public void deframeFailed(Throwable cause) {
...
+      // isStreamDeallocated() check protects from spamming stream resets by scheduling multiple
+      // CancelServerStreamCommand commands.
+      if (future.isSuccess() || isStreamDeallocated()) {
+        return;
+      }
+      // Future failed, fail RPC.
+      // Normally we don't need to do anything here because the cause of a failed future
+      // while writing DATA frames would be an IO error and the stream is already closed.
+      // However, we still need handle any unexpected failures raised in Netty.
+      // TODO(sergiitk): check if something similar to
```
Comment (sergiitk) [inline netty/src/main/java/io/grpc/netty/NettyServerStream.java:217]: TODO: discuss with @ejona86

File: netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java [hunk 6]
```diff
@@ -205,6 +211,42 @@ public void writeMessageShouldSendRequestUnknownLength() throws Exception {
...
 
+  @Test
+  public void writeFrameFutureFailedShouldCancelRpc() {
+    Http2Exception h2Error = connectionError(PROTOCOL_ERROR, "Stream does not exist %d", STREAM_ID);
+    when(writeQueue.enqueue(any(SendGrpcFrameCommand.class), eq(true))).thenReturn(
+        new DefaultChannelPromise(channel).setFailure(h2Error));
+
+    // Force stream creation.
+    stream().transportState().setId(STREAM_ID);
+    // TODO(sergiitk): multiple messages?
```
Comment (sergiitk) [inline netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java:222]: multiple messages / multi-frame message
TODO: discuss with @ejona86

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java (hunk 5 above)
Comment (sergiitk) [reply netty/src/main/java/io/grpc/netty/NettyServerStream.java:217]: From IRL: doesn't matter

Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/NettyServerStream.java:217]: For posterity: it doesn't matter much on server-side because few things will see this error message. We just report "cancelled!" to the server. The status code shows up in metrics, but not the messages. We do use them in debugging, but we really don't expect this to trigger except if there is a bug, so it isn't much of a concern.

Comment (sergiitk) [reply netty/src/main/java/io/grpc/netty/NettyServerStream.java:217]: Thanks for the note!

File: netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java (hunk 6 above)
Comment (sergiitk) [reply netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java]: For IRL conversation: yes, we need this.

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java [hunk 7]
```diff
@@ -206,6 +192,40 @@ public void deframeFailed(Throwable cause) {
       handler.getWriteQueue().enqueue(new CancelServerStreamCommand(this, status), true);
     }
 
+    private void onWriteFrameData(ChannelFuture future, int numMessages, int numBytes) {
+      // Remove the bytes from outbound flow control, optionally notifying
+      // the client that they can send more bytes.
+      // TODO(sergiitk): should onSentBytes be called only on success?
```
Comment (sergiitk) [inline netty/src/main/java/io/grpc/netty/NettyServerStream.java:198]: @ejona86 this is might be out-of-scope of this PR, but I've noticed that the client side only calls it when the future has succeeded: https://github.com/grpc/grpc-java/blob/f7ee5f3182dddde775069155d17ed93f7270f1ca/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L191-L196

While server-side does not:
https://github.com/grpc/grpc-java/blob/f7ee5f3182dddde775069155d17ed93f7270f1ca/netty/src/main/java/io/grpc/netty/NettyServerStream.java#L116-L124

I assume this was based on the assumption the promises won't fail. I think we should move `onSentBytes` into `if (future.isSuccess())`.

File: netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java [hunk 8]
```diff
@@ -205,6 +210,51 @@ public void writeMessageShouldSendRequestUnknownLength() throws Exception {
...
+        .skip(2).findFirst().get()
+        // Get the first argument (QueuedCommand command)
+        .getArgument(0);
+
+    Status cancelReason = cancelCommand.reason();
+    assertThat(cancelReason.getCode()).isEqualTo(Status.INTERNAL.getCode());
+    assertThat(cancelReason.getCause()).isEqualTo(h2Error);
+    // Verify listener closed.
+    // TODO(sergiitk): should we expect REFUSED/MISCARRIED instead?
+    verify(listener).closed(same(cancelReason), eq(PROCESSED), any(Metadata.class));
```
Comment (sergiitk) [inline netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java:255]: @ejona86 Should we be closing the listener with REFUSED instead of processed?

https://github.com/grpc/grpc-java/blob/f7ee5f3182dddde775069155d17ed93f7270f1ca/core/src/main/java/io/grpc/internal/ClientStreamListener.java#L55-L62

There's also MISCARRIED (`The stream is closed even before anything leaves the client.`), but I assume "anything" includes initial headers and doesn't apply to our case.

Comment (sergiitk) [reply netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java:255]: Thanks for the clarification here and in the docs (#11045)!

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java [hunk 9]
```diff
@@ -96,48 +93,37 @@ private class Sink implements AbstractServerStream.Sink {
...
       try (TaskCloseable ignore = PerfMark.traceTask("NettyServerStream$Sink.writeHeaders")) {
-        writeQueue.enqueue(
-            SendResponseHeadersCommand.createHeaders(
-                transportState(),
-                Utils.convertServerHeaders(headers)),
-            flush);
+        Http2Headers http2headers = Utils.convertServerHeaders(headers);
+        SendResponseHeadersCommand headersCommand =
+            SendResponseHeadersCommand.createHeaders(transportState(), http2headers);
+        writeQueue.enqueue(headersCommand, true)
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyServerStream.java:99]: Looks like this should have remained `flush` instead of becoming `true`.

**Review by ejona86 — APPROVED** [review]

File: netty/src/main/java/io/grpc/netty/NettyServerStream.java (hunk 9 above)
Comment (sergiitk) [reply netty/src/main/java/io/grpc/netty/NettyServerStream.java:99]: As I said IRL, this the exact situation for which 🦅 👀  emoji exist.
