### PR TITLE
stub: disable exception if onCancelHandler set

### LINKED ISSUE #5061: Add option to disable cancellation causing exception on Server
As mentioned some in #4351, if there is a cancellation on server-side we end up throwing an exception when sending from the async stub. That's very surprising and isn't great.

That used to be the only way of receiving cancellation notification with the async stub. However, we now have ways to let users add their own cancellation listeners. So we could either disable the throwing when using cancellation callback or have an option that will disable the throwing behavior.

### PR DESCRIPTION
**Pull request by venilnoronha**
This restrains a cancellation `Exception` when an `onCancelHandler` is set in `ServerCallStreamObserverImpl`. Fixes #5061.

### CODE REVIEW

**Comment by venilnoronha** [comment]
ping

File: stub/src/main/java/io/grpc/stub/ServerCalls.java [hunk 1]
```diff
@@ -332,13 +332,16 @@ public void setCompression(String compression) {
     @Override
     public void onNext(RespT response) {
       if (cancelled) {
-        throw Status.CANCELLED.withDescription("call already cancelled").asRuntimeException();
-      }
-      if (!sentHeaders) {
-        call.sendHeaders(new Metadata());
-        sentHeaders = true;
+        if (onCancelHandler == null) {
```
Comment (ejona86) [inline stub/src/main/java/io/grpc/stub/ServerCalls.java]: nit: Could this have an `else` that `return`s? That would allow removing the current `else` and returning the code to look a bit more like it did before. (I do see that this code as written mirrors onCompleted, but it also has a single line in the else, so it doesn't matter as much.)

Comment (venilnoronha) [reply stub/src/main/java/io/grpc/stub/ServerCalls.java]: Addressed in 8276d64.

**Comment by ejona86** [comment]
@venilnoronha, Thank you!

**Comment by venilnoronha** [comment]
@ejona86 thanks for reviewing/merging!
