### PR TITLE
Use status UNAVAILABLE for IOException thrown by OkHttp reading path,…

### LINKED ISSUE #608: Make sure error status codes are consistent with other implementations

### PR DESCRIPTION
**Pull request by madongfly**
… which can also be triggered by HTTP/2 issues.

Fixes #608

### CODE REVIEW

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java [hunk 1]
```diff
@@ -580,9 +580,9 @@ public void run() {
         while (frameReader.nextFrame(this)) {
         }
       } catch (IOException ioe) {
-        // We call onError instead of onIoException here, because OkHttp wraps many protocol errors
-        // as IOException, we should send GoAway for such errors.
-        onError(ErrorCode.PROTOCOL_ERROR, ioe.getMessage());
+        // We send GoAway here because OkHttp wraps many protocol errors as IOException.
+        frameWriter.goAway(0, ErrorCode.PROTOCOL_ERROR, new byte[0]);
```
Comment (ejona86) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: If there is a message in the `ioe`, we could send it in the GOAWAY. Probably a good idea. No need to do it now, but add a TODO.

**Comment by ejona86** [comment]
@madongfly LGTM

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java (hunk 1 above)
Comment (madongfly) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: Done, thanks!
