### PR TITLE
api, core, services: make ProtoReflectionService interceptor compatible

### LINKED ISSUE #3469: Could not add interceptor(s) to `ProtoReflectionService`
### What did you do?
Add interceptor(s) to `ProtoReflectionService`.

### What did you expect to see?
`ProtoReflectionService` works with interceptor(s).

### What did you see instead?
Got a NullPointerException or compilation error.

### Problem
I ask a question on Gitter.
https://gitter.im/grpc/grpc?at=59b9090bcfeed2eb65033bad
and I have got a reply from @e.jona86.
https://gitter.im/grpc/grpc?at=59b9a7f9c101bc4e3ac3404a
I think it is not easy to fix. So I report an issue.

`ProtoReflectionService` needs a reference to `Server` via `notifyOnBuild` but it could not, because an intercepted service is an instance of `ServerServiceDefinition`.

I think it is consisting some problems (may not a bug or may not a problem) as below.
- `ServerInterceptors#intercept` binds a service and returns `ServerServiceDefinition`.
- `ServerBuilder#addService` doesn't add `ServerServiceDefinition` to `notifyOnBuildList`.
- `ServerServiceDefinition` doesn't implement `InternalNotifyOnBuild`.

Therefore, I could not add interceptor(s) to `ProtoReflectionService`.

### PR DESCRIPTION
**Pull request by voidzcy**
Resolves #3469.

Major changes:
- Put `ServerImpl` instance to its `Context` so that all server calls have access to the Server instance from which they are dispatched.
- `InternalNotifyOnServerBuild` is eliminated as the server reference can be captured with a server interceptor.
- Enhancement: allow using the same `ProtoReflectionService` instance across multiple servers without recomputing the whole service index for each server.

### CODE REVIEW

File: api/src/main/java/io/grpc/ServerCall.java [hunk 1]
```diff
@@ -229,4 +229,10 @@ public String getAuthority() {
    * The {@link MethodDescriptor} for the call.
    */
   public abstract MethodDescriptor<ReqT, RespT> getMethodDescriptor();
+
+  /**
+   * Returns the {@link Server} that dispatches the call.
+   */
+  // TODO(chengyuanzhang): add ExperimentalApi annotation.
+  public abstract Server getServer();
```
Comment (ejona86) [inline api/src/main/java/io/grpc/ServerCall.java:237]: It must have a default implementation. Either return null or UnsupportedOperationException. The documentation should say what the default behavior is when unsupported.

File: api/src/main/java/io/grpc/ServerCall.java [hunk 2]
```diff
@@ -229,4 +229,10 @@ public String getAuthority() {
    * The {@link MethodDescriptor} for the call.
    */
   public abstract MethodDescriptor<ReqT, RespT> getMethodDescriptor();
+
+  /**
+   * Returns the {@link Server} that dispatches the call.
+   */
+  // TODO(chengyuanzhang): add ExperimentalApi annotation.
```
Comment (ejona86) [inline api/src/main/java/io/grpc/ServerCall.java:236]: Yeah, we can go ahead and create that.

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java [hunk 3]
```diff
@@ -140,6 +150,21 @@ private ServerReflectionIndex updateIndexIfNecessary() {
...
+    private final AtomicReference<Server> captor;
+
+    ServerCaptureInterceptor(AtomicReference<Server> captor) {
+      this.captor = captor;
+    }
+
+    @Override
+    public <ReqT, RespT> Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call,
+        Metadata headers, ServerCallHandler<ReqT, RespT> next) {
+      captor.set(call.getServer());
```
Comment (ejona86) [inline services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:163]: I don't think it would be obvious that you must use a different reflection service instance for each server. Can we instead add the Server to the Context and handle multiple servers? (WeakHashMap may make sense)

File: api/src/main/java/io/grpc/ServerCall.java (hunk 1 above)
Comment (voidzcy) [reply api/src/main/java/io/grpc/ServerCall.java]: Default to return null.

Some thoughts about this: isn't the semantics of a `ServerCall` a call dispatched by a server? Then it's kind of reasonable to always require concrete implementations (the only real one in gRPC is `ServerCallImpl`).

File: api/src/main/java/io/grpc/ServerCall.java (hunk 2 above)
Comment (voidzcy) [reply api/src/main/java/io/grpc/ServerCall.java]: Added. It's #6989.

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java (hunk 3 above)
Comment (voidzcy) [reply services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:159]: As our offline discussion, added a WeakHashMap to cache indexes for servers. This supports a single reflection service instance to be shared across multiple servers, without recomputing its service index upon each RPC.

I don't think adding the cache to the Context is necessary. Did I miss anything?

File: api/src/main/java/io/grpc/ServerCall.java (hunk 1 above)
Comment (ejona86) [reply api/src/main/java/io/grpc/ServerCall.java]: The problem is this is an API anyone can implement, and so wouldn't already be implementing this method. The "common case" would return non-null, but that doesn't mean we can guarantee all cases will.

Comment (ejona86) [reply api/src/main/java/io/grpc/ServerCall.java]: (And note, it isn't entirely theoretical. _Many_ interceptors implement this API. We just so happen to encourage them to use ForwardingServerCall, but it is possible they don't.)

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java [hunk 4]
```diff
@@ -77,8 +77,7 @@
   private ProtoReflectionService() {}
 
   /**
-   * Creates a instance of {@link ProtoReflectionService}. Intended usage is one instance per
```
Comment (ejona86) [inline services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java]: Doh. I missed this before. Of course it was already limited to one server. Sorry for asking for the WeakHashMap, although it is nicer that way. I guess previously we'd have just returned wrong data? Yeah, using the WeakHashMap is much nicer for users.

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java [hunk 5]
```diff
@@ -68,11 +68,8 @@
 @ExperimentalApi("https://github.com/grpc/grpc-java/issues/2222")
 public final class ProtoReflectionService extends ServerReflectionGrpc.ServerReflectionImplBase {
 
-  private final Object lock = new Object();
-
+  private final Map<Server, ServerReflectionIndex> serverReflectionIndexes = new WeakHashMap<>();
```
Comment (ejona86) [inline services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:71]: `@GuardedBy("this")`?

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java [hunk 6]
```diff
@@ -68,11 +68,8 @@
 @ExperimentalApi("https://github.com/grpc/grpc-java/issues/2222")
 public final class ProtoReflectionService extends ServerReflectionGrpc.ServerReflectionImplBase {
 
-  private final Object lock = new Object();
```
Comment (ejona86) [inline services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:67]: Why get rid of this lock? We generally do this on purpose to avoid letting a user from interacting with our synchronization.

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java (hunk 5 above)
Comment (voidzcy) [reply services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:71]: Does `@GuardedBy` checks accessing collection elements? I thought I was just the field itself.

Comment (ejona86) [reply services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:71]: It would notice most method invocations on the map, like get/put.

Comment (voidzcy) [reply services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:75]: Oh, good to know. Thanks. Added back.

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java (hunk 6 above)
Comment (voidzcy) [reply services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:67]: Added back.

File: services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java (hunk 3 above)
Comment (ejona86) [reply services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java:165]: No, this AtomicReference doesn't work. This is not thread-safe. If two reflection RPCs come in at the same time, the responses may be for the wrong Server. Add the `Server` to Context here (not the cache; although adding the cache entry instead would be "fine" functionally).

**Comment by voidzcy** [comment]
Per offline discussion, we decided to expose Server through Context (with an internal key). So no new API needs to be added.

File: core/src/main/java/io/grpc/internal/InternalServerAccessor.java [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+
+/**
+ * Internal accessor for getting the {@link Server} instance inside server RPC {@link Context}.
+ * This is intended for usage internal to the gRPC team, as it's unclear to us what users would
+ * need. If you *really* think you need to use this, please file an issue for us to discuss a
+ * public API.
+ */
+@Internal
+public class InternalServerAccessor {
+  public static final Context.Key<Server> SERVER_KEY = ServerImpl.SERVER_CONTEXT_KEY;
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/InternalServerAccessor.java:31]: Since this instance is being used as API and not as convenience, the instance needs to be created in `io.grpc` (not just copied, like here). If we shaded `io.grpc.internal` this reference would no longer match between implementations.

File: core/src/main/java/io/grpc/internal/InternalServerAccessor.java [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+package io.grpc.internal;
+
+import io.grpc.Context;
+import io.grpc.Internal;
+import io.grpc.Server;
+
+/**
+ * Internal accessor for getting the {@link Server} instance inside server RPC {@link Context}.
+ * This is intended for usage internal to the gRPC team, as it's unclear to us what users would
+ * need. If you *really* think you need to use this, please file an issue for us to discuss a
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/InternalServerAccessor.java:26]: Let's drop the "*really*". I don't see the need for the emphasis, and no real need to scare off users from filing an issue.

File: core/src/main/java/io/grpc/internal/InternalServerAccessor.java (hunk 7 above)
Comment (voidzcy) [reply core/src/main/java/io/grpc/internal/InternalServerAccessor.java]: Moved the creation to `io.grpc.Server` and accessor to `io.grpc`.

File: core/src/main/java/io/grpc/internal/InternalServerAccessor.java (hunk 8 above)
Comment (voidzcy) [reply core/src/main/java/io/grpc/internal/InternalServerAccessor.java]: Reworded. Users should refer to the documentation at where the Context key is created (`io.grpc.Server`). The accessor is just for our own usage.

File: api/src/main/java/io/grpc/Server.java [hunk 9]
```diff
@@ -30,6 +30,14 @@
 @ThreadSafe
 public abstract class Server {
 
+  /**
+   * Key for accessing the {@link Server} instance inside server RPC {@link Context}. It's
+   * unclear to us what users would need. If you think you need to use this, please file an
+   * issue for us to discuss a public API.
+   */
+  protected static final Context.Key<Server> SERVER_CONTEXT_KEY =
```
Comment (ejona86) [inline api/src/main/java/io/grpc/Server.java:38]: `protected` leaks it. Using package-private is probably better.
