### PR TITLE
[okhttp] Make sure transportShutdown() always be called before callin…

### LINKED ISSUE #1111: transportShutdown() should be called before calling transportTerminated().
With the changes of TransportSet, transportShutdown() must be called before calling transportTerminated().

```
10-06 15:32:45.917  5126  5126 E AndroidRuntime: FATAL EXCEPTION: OkHttpClientTransport
10-06 15:32:45.917  5126  5126 E AndroidRuntime: Process: com.google.android.apps.fireball, PID: 5126
10-06 15:32:45.917  5126  5126 E AndroidRuntime: java.lang.IllegalStateException: Listener is still attached to activeTransportFuture. Seems transportTerminated was not called.
10-06 15:32:45.917  5126  5126 E AndroidRuntime: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
10-06 15:32:45.917  5126  5126 E AndroidRuntime: 	at io.grpc.internal.TransportSet$TransportListener.transportTerminated(TransportSet.java:249)
10-06 15:32:45.917  5126  5126 E AndroidRuntime: 	at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:606)
10-06 15:32:45.917  5126  5126 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-06 15:32:45.917  5126  5126 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-06 15:32:45.917  5126  5126 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
10-06 15:32:45.918   745  1319 W ActivityManager:   Force finishing activity com.google.android.apps.fireball/.ui.photoviewer.FireballPhotoViewActivity
```

### PR DESCRIPTION
**Pull request by madongfly**
…g transportTerminated().

Fixes #1111 

@ejona86 @zhangkun83

### CODE REVIEW

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java [hunk 1]
```diff
@@ -493,6 +493,14 @@ private void onGoAway(int lastKnownStreamId, Status status) {
     boolean notifyShutdown;
     synchronized (lock) {
       notifyShutdown = !goAway;
+    }
+    if (notifyShutdown) {
+      // We call transportShutdown() here, because once the goAway becomes true, other thread may
+      // call stopIfNecessary() and cause listener.transportTerminated() be called.
```
Comment (zhangkun83) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: `ClientTransport.Listener` is not thread-safe, notifications to it must be [properly synchronized externally](https://github.com/grpc/grpc-java/blob/a508c1d4f5024c2a5fd6d103edcab43542293ae7/core/src/main/java/io/grpc/internal/ClientTransport.java#L102). If more than one thread is calling the listener, is there any synchronization between them?

Comment (madongfly) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: The transportTerminated() is always called after the goAway becomes true, after this change, the goAway will only becomes true after transportShutdown() is called, so they should be fine.

Comment (madongfly) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: The transportTerminated() is always called after the goAway becomes true, after this change, the goAway will only becomes true after transportShutdown() is called, so they should be fine.

**Comment by zhangkun83** [comment]
LGTM

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java (hunk 1 above)
Comment (madongfly) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: Actually this code is wrong, if two threads call into onGoAway(), then transportShutdown() may be called twice, will figure out another way.

**Comment by zhangkun83** [comment]
`onGoAway()` is called not only under the go-away case, but also called in all other shutdown cases. This name doesn't reflect its functionality and usage well. Can we rename it to something like `startTermination()`?

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java (hunk 1 above)
Comment (madongfly) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: Updated.

**Comment by madongfly** [comment]
@zhangkun83 I renamed it to `startGoAway` because we set the goAway, goAwayStatus variables inside that method, `startGoAway` tells the relation between this method and the goAway variables, and unlike `onGoAway` implicating the process of receiving go-away, `startGoAway` shows the method can be called by client side operations.

Let me know whether you are OK with it.

File: okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java [hunk 2]
```diff
@@ -486,13 +487,23 @@ void onException(Throwable failureCause) {
...
-    onGoAway(0, toGrpcStatus(errorCode).augmentDescription(moreDetail));
+    startGoAway(0, toGrpcStatus(errorCode).augmentDescription(moreDetail));
   }
 
-  private void onGoAway(int lastKnownStreamId, Status status) {
-    boolean notifyShutdown;
+  private void startGoAway(int lastKnownStreamId, Status status) {
+    synchronized (lock) {
+      if (goingAway) {
+        // Another go-away is inprocess, ignore this one.
```
Comment (zhangkun83) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: s/inprocess/in progress/
However, this description is still not accurate. `goingAway` will remain true even if the process is completed. I feel `isShutdown` would be a better name. Because `transportShutdown()` will be called afterwards, setting `isShutdown=true` here makes perfect sense. And if we name the variable as `isShutdown`, naming the method as something related to "shutdown" would make more sense.

Comment (madongfly) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: In my opinion, the `goAway` process lasts until the transport is finally shut down, during the process, the transport is `going away`, and after that, we don't care since the transport is fully stopped.

I don't think renaming the `goingAway`, `goAway`, `goAwayStatus` to `isShutingdown`, `isShutdown`, `shutdownStatus` will gain us any benefit, especially when `shutdown` implicates `stop per the caller's request`.

Comment (zhangkun83) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: Fair enough. I don't feel that strong for it. Could you add a comment to `goingAway` to document its semantics?

Comment (madongfly) [inline okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java]: Done.

**Comment by madongfly** [comment]
@zhangkun83 PTAL, thanks!

**Comment by madongfly** [comment]
@zhangkun83 updated per offline discussion, PTAL, thanks!

**Comment by zhangkun83** [comment]
LGTM
