### PR TITLE
testing: add tests for Netty bug where a channel would break after a …

### LINKED ISSUE #1682: Cancelling a call results in onClose never being invoked.
Consider the following code:

```
      final ClientCall<Void, Void> call = channel.newCall(..., ...);
      ClientCall.Listener<Void> listen =
          new ClientCall.Listener<Void>() {
            @Override
            public void onMessage(Void message) {
              call.cancel();
            }

            @Override
            public void onClose(Status status, Metadata trailers) {
              // NEVER CALLED!
            }
          };
      call.start(listen, new Metadata());
      call.sendMessage(msg);
      call.halfClose();
      call.request(1);
```

onClose will not be invoked, so it becomes impossible to know when the call is actually done.  This seems wrong.  If the call is cancelled from outside of the listener, onClose is invoked.

### PR DESCRIPTION
**Pull request by buchgr**
…RST_STREAM frame. Fixes #1682 

cc: @ejona86

### CODE REVIEW

**Comment by buchgr** [comment]
This test reliably fails when using Netty CR7. Triggering the stream exception

```
FINE: Stream error for unknown stream 3
io.netty.handler.codec.http2.Http2Exception$StreamException: Received HEADERS frame for an unknown stream 3
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:124)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:567)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:293)
....
```

File: testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java [hunk 1]
```diff
@@ -170,6 +171,52 @@ public void tearDown() throws InterruptedException {
   //   queued message InputStreams are closed on stream cancel
   //     (and maybe exceptions handled)
 
+  /**
+   * Test for issue https://github.com/grpc/grpc-java/issues/1682
+   */
+  @Test
+  public void foo() throws Exception {
```
Comment (carl-mastrangelo) [inline testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java]: name

**Comment by carl-mastrangelo** [comment]
@buchgr LGTM
