### PR TITLE
grpclb: include fallback reason in error status of failing to fallback

### LINKED ISSUE #7997: grpclb: Improve error information for "Unable to fallback, no fallback addresses found"
https://github.com/grpc/grpc-java/pull/7960 fixed a case for grpclb that would cause it to hang if there were no fallback addresses. Now in that case instead of hanging it produces the error "UNAVAILABLE: Unable to fallback, no fallback addresses found", which is much better than hanging. However, it doesn't give any information to actually debug what's happening.

I'm thinking something along the lines of:
1. If there are fallback addresses, use one of their subchannel's error (ideally we'd round-robin over them or some such, but baby steps)
2. If we have no primary addresses (RPC to gRPCLB has never been successful), we should include the gRPC-LB contact error information (the information from the failing RPC, or create a message describing the RPC hasn't returned yet)
3. Otherwise, there are primary addresses and we should use one of their subchannel's error (ideally we'd round-robin over them or some such, but baby steps)

### PR DESCRIPTION
**Pull request by voidzcy**
Enhance error information reflected by RPC status when failing to fallback (aka, no fallback addresses provided by resolver), by including the original cause of entering fallback. This falls into cases:

  - balancer RPC timeout before receiving any backend addresses (includes a timeout message)
  - balancer RPC failed before receiving any backend addresses (use the error occurred in balancer RPC)
  - all balancer-provided addresses failed, while balancer RPC had failed causing fallback (use the error status for one of the balancer-provided backend)

Note for cases that connections to fallback address fail, it's already using one of fallback addresses' error. See `handleSubchannelState(...)` -> `maybeUseFallbackBackends()` (no-op as it's already using fallback backends) -> `maybeUpdatePicker()` with `backendList` being non-empty.

---------------------
Fixes #7997

### CODE REVIEW

File: grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java [hunk 1]
```diff
@@ -252,6 +269,7 @@ void handleAddresses(
       }
       // Start the fallback timer if it's never started
       if (fallbackTimer == null) {
+        fallbackReason = BALANCER_TIMEOUT_STATUS;
```
Comment (ejona86) [inline grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:272]: Put this in FallbackModeTask? That'd also be more obviously before maybeUseFallbackBackends(). I recognize it'd have to be passed to the constructor.

File: grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java [hunk 2]
```diff
@@ -717,6 +743,7 @@ private void handleStreamClosed(Status error) {
       cleanUp();
       propagateError(error);
       balancerWorking = false;
+      fallbackReason = error;
```
Comment (ejona86) [inline grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:746]: This may not be UNAVAILABLE. We need to create a new Status.

File: grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java (hunk 1 above)
Comment (voidzcy) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java]: Ah, that was what my previous revision look like. But I was afraid of missing cases that just let the fallback timer fire and reply on condition checks in `maybeUseFallbackBackends()` to skip (re-) entering fallback. It looks all cases that certainly not entering fallback or entering fallback early are cancelling the timer. So this should be fine.

File: grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java (hunk 2 above)
Comment (voidzcy) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: What about the `propagateError(error)` two lines above? I was wanting to delete that line. That line fails RPCs for a short time window between balancer RPC closed and trying fallback. Right after fallback is attempted, if failing to fallback, RPCs will change to fail with `fallbackReason` (which is the same status for the balancer's failure plus a "fail to fallback" message).

So I am wondering if we should remove the `propagateError(error)` line here and fall RPCs with a single status, after attempting fallback.

Comment (ejona86) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: `propagateError()` is called two places. On of them isn't as it seems. `InetAddress.getByAddress()` only throws UnknownHostException "if IP address is of illegal length" so the error string "Host for server not found" is wrong.

`propagateError()` does two things: log and adjust the picker. For logging, we really want to log the original Status, so `error` here. But we can't use `error` directly for the picker, even if it is for a short period of time.

> So I am wondering if we should remove the propagateError(error) line here and fall RPCs with a single status, after attempting fallback.

That's a functional change, as you _no longer_ cause failures if fallback succeeds. I don't think we'd chose the behavior based on what makes the implementation easiest. I think we want it to behave _a certain way_ in this case. I thought grpclb was supposed to try fallback before failing RPCs, at least when starting up. I honestly don't know where to look up the expected behavior in this case.

Calling @markdroth to help inform us of when gRPC-LB should begin failing RPCs.

Comment (markdroth) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: I don't have enough context here to know which specific cases you're asking about.

In general, there are two types of grpclb fallback, fallback at startup and fallback after startup.

Fallback at startup is triggered in the following cases:
- When the fallback timer fires before we have received the first response from the balancer.
- When the balancer channel goes into TRANSIENT_FAILURE before reaching READY.  (This short-circuits the fallback timer.)
- When the balancer call finishes (regardless of status) without receiving the first response from the balancer.  (This short-circuits the fallback timer.)

Fallback after startup occurs only after we receive an initial response from the balancer.  It is triggered in the following cases:
- When we get an explicit response from the balancer telling us go into fallback.
- When both of the following are true:
  - The balancer call has finished (regardless of status) and we have not yet received the first response on the subsequent call.
  - We cannot connect to any of the backends in the last response we received from the balancer.

None of these cases have anything to do with the status of individual data plane calls.  However, there are two cases above where fallback is triggered by receiving status on the balancer call, but only when other conditions are also met.

Comment (voidzcy) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: This still did not directly answer the question if we should fail RPCs before trying fallback. The specific case we are talking about is when the balancer RPC finishes (regardless of status) and none of the connections to any backends received previously has been READY. Do we fail RPCs immediately while trying to use fallback addresses (which implies RPCs may succeed back again if connections to fallback succeeds)? Or do we wait until fallback has been attempted?

Comment (voidzcy) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: On the other hand, based on fallback conditions mentioned above, looks we do have different behaviors in our existing implementation.

In our existing implementation, _having no READY connection to balancer-given backends_ is a _necessary requirement_ to attempt fallback for any cases, even for case that balancer is explicitly telling us to fallback. That is, as long as there is READY subchannels to backends, any reason (e.g., balancer response explicitly tells to do so, address update containing no balancer addresses) to fallback will be ignored.

That would be a separate issue. If we do want to fix every case, we would need crystal clear definitions with all conditions included. For the current change, I guess we should try to preserve existing behaviors but just report desired errors.

File: grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java (hunk 1 above)
Comment (voidzcy) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java]: It turned out that I did miss one case: we need to short-circuit the fallback timer when the balancer RPC closes, instead of just let it execute. Although fallback logic won't be executed again as it's already in fallback, it will overwrite the fallback reason. To avoid this happen, we need to ensure the fallback timer is cancelled for all cases that we enter fallback early.

File: grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java (hunk 2 above)
Comment (markdroth) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: In the fallback-at-startup case, we should be in state CONNECTING until we either get connected or go into fallback mode, so we should not fail data plane RPCs until one of those two things happens.

In the fallback-after-startup case, the "get an explicit response from the balancer telling us go into fallback" case should *not* depend on whether there are currently any READY connections to balancer-given backends, since it's intended to force clients to go to fallback regardless of whether they are currently connected to backends, and you should fix your implementation if it's not doing that.  Given that, there are several cases here:
- If we can't reach any of the balancer-provided backends before we go into fallback mode (e.g., if the backend connections fail before either the balancer connection fails or the balancer explicitly tells us to go into fallback), then we will fail some data plane RPCs.
- If we are in contact with the balancer-provided backends and the balancer tells us to go into fallback mode, we should not fail any RPCs; we should keep using the balancer-provided backends while we get in contact with the fallback backends.
- If we are in contact with the balancer-provided backends and the balancer call fails, and *then* we lose contact with the balancer-provided backends, it's a bit of a grey area.  In principle, I suppose we should go into state CONNECTING here and queue data plane RPCs instead of failing them, but if we actually fail some RPCs instead, I think we can probably live with that.

@apolcyn may want to weigh in here as well.

Comment (apolcyn) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: +1 to everything @markdroth just described.

Also note that go/grpclb-explicit-fallback describes the expected behavior of clients when receiving a fallback response from a balancer.

Comment (ejona86) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: > That line fails RPCs for a short time window between balancer RPC closed and trying fallback.

I just realized that sounded similar to b/138458426. I had found a path through the code that could cause that but https://github.com/grpc/grpc-java/pull/6657 looked like it'd fix it. Maybe there was a second path through the code? And apparently Go might still have this problem?

Comment (voidzcy) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:754]: From the description of "the client enters transient failure because all subchannels are "connecting", and one has entered "transient failure", so the pending pick fails." in b/138458426#comment4, I'd suspect that was due to the issue described in #7959, which was fixed recently.

**Comment by voidzcy** [comment]
I updated this a bit:

RPCs failed caused by reasons _not directly related to_ its connections to the backends (aka, anything happens before making connections to backends, such as balancer RPC broken before getting any backends, fail to fallback, etc) will end up with always UNAVAILABLE status code attached with cause and description from the original (immediate-fail or fallback) reason. Some examples are:
   - balancer RPC timeout before receiving any backends, then try to fallback but no fallback address found. RPCs fail with {UNAVAILABLE, description="Unable to fallback, no fallback addresses found\n Timeout waiting for remote balancer", cause=null}
   - balancer RPC failed (say, permission denied) before receiving any backends, then try to fallback but no fallback address found. RPCs fail with {UNAVAILABLE, description="Unable to fallback, no fallback addresses found\n <description from the status of balancer RPC>", cause=<cause from the status of balancer RPC>}

File: grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java (hunk 2 above)
Comment (voidzcy) [reply grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java:756]: > In the fallback-after-startup case, the "get an explicit response from the balancer telling us go into fallback" case should not depend on whether there are currently any READY connections to balancer-given backends, since it's intended to force clients to go to fallback regardless of whether they are currently connected to backends, and you should fix your implementation if it's not doing that.

Sorry sorry, what I mentioned in https://github.com/grpc/grpc-java/pull/8035#discussion_r608231893 was wrong. Balancer forcing entering fallback is correct. It will stop using balancer-provided backends immediately, even if there are READY connections.

Actually our implementation looks fine for handling the grey area:
- If connections to all balancer-provided backends fail before balancer RPC becomes broken. In this case, client RPCs fail with the status from one of the broken subchannels. After the balancer RPC fails, before attempting to fallback, the status used to fail client RPCs is changed to that from the balancer RPC.
- If balancer RPC fail before connections to balancer-provided backends all become broken. Client RPCs do not fail until  the later happens. After connections to all balancer-provided backends fail, before attempting to fallback, the status used to fail client RPCs is from one of the broken subchannels.

**Review by ejona86 — APPROVED** [review]
