### PR TITLE
servlet: disable RECYCLE_FACADES to reduce flaky tests

### LINKED ISSUE #12524: TomcatTransportTest.clientChecksInboundMetadataSize_header is flaky
https://github.com/grpc/grpc-java/actions/runs/19511968094/job/55853763048?pr=12523
https://github.com/grpc/grpc-java/actions/runs/19511968094/job/55853763051?pr=12523
```
TomcatTransportTest > clientChecksInboundMetadataSize_header FAILED
    java.lang.IllegalStateException: The output buffer object has been recycled and is no longer associated with this facade
        at org.apache.catalina.connector.CoyoteOutputStream.isReady(CoyoteOutputStream.java:186)
        at io.grpc.servlet.jakarta.AsyncServletOutputStreamWriter.runOrBuffer(AsyncServletOutputStreamWriter.java:225)
        at io.grpc.servlet.jakarta.AsyncServletOutputStreamWriter.flush(AsyncServletOutputStreamWriter.java:161)
        at io.grpc.servlet.jakarta.ServletServerStream$Sink.writeHeaders(ServletServerStream.java:236)
        at io.grpc.internal.AbstractServerStream.writeHeaders(AbstractServerStream.java:104)
        at io.grpc.internal.AbstractTransportTest.clientChecksInboundMetadataSize_header(AbstractTransportTest.java:2024)
```

### PR DESCRIPTION
**Pull request by becomeStar**
### Background
In the gRPC servlet transport with Tomcat 10 Embedded, 
we observed occasional flaky tests in `grpc-servlet-jakarta:tomcat10Test`. 
The issue is related to a race condition where the OutputBuffer is prematurely recycled  during asynchronous writes.

### Changes
Reference: https://github.com/spring-projects/spring-boot/issues/36763#issuecomment-1667382305

This PR explicitly calls `.setDiscardFacades(false)` on the Tomcat 10 Embedded Connector. 
The intention is to prevent outputBuffer reuse, so that the above race condition does not occur during tests.

### Purpose
- Reduce the likelihood of flaky tests in `grpc-servlet-jakarta:tomcat10Test`
- Apply the method suggested in the referenced Spring Boot discussion

### Note
This change aligns Tomcat 10 Embedded behavior with Tomcat 9 (where `RECYCLE_FACADES` defaults to `false`), and is known to prevent premature  `OutputBuffer` recycling during async writes.
Based on the investigation and prior reports (e.g., Spring Boot discussion),
this is currently the correct and safe configuration for servlet-based asynchronous responses in Tomcat 10.

Fixes #12524

### CODE REVIEW

**Comment by becomeStar** [comment]
I re-read the contribution guidelines and realized I had incorrectly included two lines of code formatting along with the core logic change, which violates the "Don't fix code style" rule. I have reverted the formatting changes, so this PR now only contains the intended one line of core logic change: .setDiscardFacades(false);. 

I believe this single line resolves the issue described in #12524, but I would like to confirm if the maintainers also consider this approach appropriate.

**Comment by ejona86** [comment]
> The issue is related to a race condition where the OutputBuffer is prematurely recycled during asynchronous writes.

Why are they prematurely recycled? That seems to be the problem. It is either a bug in Tomcat or in gRPC. The linked issue says:

> You are relying upon the request still be usable after its handling has completed which may not work reliably.

So it seems we need to fix our code to stop using the request when it is no longer valid. Or at least that should be the initial goal. Maybe we can't because of some reason, but then we'd want to understand why.

**Comment by ejona86** [comment]
I would accept this change as a "make the tests stop flaking," but then we'd want to create a new issue to track the bug involved here.

**Comment by becomeStar** [comment]
@ejona86 

Thank you for the insightful feedback. You are absolutely right.

I agree that disabling facade recycling is a workaround to stabilize the tests. We should investigate whether gRPC is accessing the request/response objects (specifically the underlying OutputBuffer) after their lifecycle has ended.

As you suggested, I will:
  1. Keep this PR focused on fixing the test flakiness.
  2. Open a new issue to track and investigate the root cause of the premature recycling due to the lifecycle mismatch  between Tomcat's object recycling and gRPC's asynchronous usage.

I'll create the issue shortly and reference it here.

**Comment by becomeStar** [comment]
I've created the tracking issue: #12540.
I'll investigate the root cause of the recycling behavior there.

File: servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java [hunk 1]
```diff
@@ -93,6 +93,7 @@ public void start(ServerListener listener) throws IOException {
             .setAsyncSupported(true);
         ctx.addServletMappingDecoded("/*", "TomcatTransportTest");
         tomcatServer.getConnector().addUpgradeProtocol(new Http2Protocol());
+        tomcatServer.getConnector().setDiscardFacades(false);
```
Comment (ejona86) [inline servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java:99]: Let's add a comment saying this is a workaround and have a link to the issue you created.

Comment (becomeStar) [reply servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java:99]: @ejona86

Added the workaround comment with the issue link. Thanks for the review.
I'll continue investigating the root cause in #12540."

**Comment by ejona86** [comment]
Thank you!
