### PR TITLE
xds: Fix WeakReference bug in SharedCallCounterMap

### LINKED ISSUE #8397: io.grpc.xds.SharedCallCounterMap.cleanQueue() NullPointerException
Version: v1.38.1
Env: Linux, Jdk8

It happened to grpc client with xds enabled:
```
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        ......
Caused by: java.lang.NullPointerException: null
        at io.grpc.xds.SharedCallCounterMap.cleanQueue(SharedCallCounterMap.java:76)
        at io.grpc.xds.SharedCallCounterMap.getOrCreate(SharedCallCounterMap.java:67)
        at io.grpc.xds.ClusterImplLoadBalancer.handleResolvedAddresses(ClusterImplLoadBalancer.java:124)
        at io.grpc.util.ForwardingLoadBalancer.handleResolvedAddresses(ForwardingLoadBalancer.java:46)
        at io.grpc.xds.PriorityLoadBalancer$ChildLbState.updateResolvedAddresses(PriorityLoadBalancer.java:269)
        at io.grpc.xds.PriorityLoadBalancer.tryNextPriority(PriorityLoadBalancer.java:136)
        at io.grpc.xds.PriorityLoadBalancer.handleResolvedAddresses(PriorityLoadBalancer.java:102)
        at io.grpc.xds.ClusterResolverLoadBalancer$ClusterResolverLbState.handleEndpointResourceUpdate(ClusterResolverLoadBalancer.java:246)
        at io.grpc.xds.ClusterResolverLoadBalancer$ClusterResolverLbState.access$1600(ClusterResolverLoadBalancer.java:157)
        at io.grpc.xds.ClusterResolverLoadBalancer$ClusterResolverLbState$EdsClusterState$1EndpointsUpdated.run(ClusterResolverLoadBalancer.java:427)
        at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
        at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
        at io.grpc.xds.ClusterResolverLoadBalancer$ClusterResolverLbState$EdsClusterState.onChanged(ClusterResolverLoadBalancer.java:431)
        at io.grpc.xds.ClientXdsClient$ResourceSubscriber.notifyWatcher(ClientXdsClient.java:1562)
        at io.grpc.xds.ClientXdsClient$ResourceSubscriber.onData(ClientXdsClient.java:1515)
        at io.grpc.xds.ClientXdsClient.handleResourcesAccepted(ClientXdsClient.java:1379)
        at io.grpc.xds.ClientXdsClient.handleEdsResponse(ClientXdsClient.java:982)
        at io.grpc.xds.AbstractXdsClient$AbstractAdsStream.handleRpcResponse(AbstractXdsClient.java:504)
        at io.grpc.xds.AbstractXdsClient$AdsStreamV3$1$1.run(AbstractXdsClient.java:663)
        at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
        at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
        at io.grpc.xds.AbstractXdsClient$AdsStreamV3$1.onNext(AbstractXdsClient.java:655)
        at io.grpc.xds.AbstractXdsClient$AdsStreamV3$1.onNext(AbstractXdsClient.java:652)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:465)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:447)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:652)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:637)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 common frames omitted
```

I failed to find the exact steps to reproduce this exception. But it almost always happens in my long-running server application.

### PR DESCRIPTION
**Pull request by dapengzhang0**
Fixes #8397.
#8397 is caused by mistakenly clearing up a map entry right after the entry is recreated after gc. Reproduced in regression test.

(`SharedCallCounterMap` is hard to read and can easily be a source of bugs. It's impossible to sufficiently test the class with unit test because GC can happen anytime concurrently with the method being tested. I'm not 100% confident about the correctness of the fix. If possible I would avoid using WeakReference in the first place.)

### CODE REVIEW

File: xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java [hunk 1]
```diff
@@ -52,19 +52,28 @@ static SharedCallCounterMap getInstance() {
...
+    AtomicLong counter = null;
     Map<String, CounterReference> clusterCounters = counters.get(cluster);
+    if (clusterCounters != null) {
+      CounterReference ref = clusterCounters.get(edsServiceName);
+      if (ref != null) {
+        counter = ref.get();
+      }
+    }
+    // In the case of ref.get() == null, must call cleanQueue() prior to creating a new map entry,
+    // otherwise the new entry will be deleted by any later cleanQueue().
```
Comment (ejona86) [inline xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java:64]: Seems the reliable fix for this would be to check that the `CounterReference` instance is the current value in `counters` before doing `remove()`.

Comment (dapengzhang0) [reply xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java]: Good idea!

**Review by ejona86 — APPROVED** [review]

File: xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java [hunk 2]
```diff
@@ -73,6 +73,9 @@ void cleanQueue() {
     CounterReference ref;
     while ((ref = (CounterReference) refQueue.poll()) != null) {
       Map<String, CounterReference> clusterCounter = counters.get(ref.cluster);
```
Comment (dapengzhang0) [inline xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java:75]: I'm guessing `clusterCounter` shouldn't be null, because refs should be enqueued in the same order as the order of  underlying referents being nullified by garbage collector. But I did not see javadoc explicitly say that. 

Is there any risk of NPE in extreme race case like the following?
ref1.referent nullified by => ref2 created and put in the counters map => ref2.referent nullified by gc => ref2 enqueued => ref1 enqueued.

File: xds/src/test/java/io/grpc/xds/SharedCallCounterMapTest.java [hunk 3]
```diff
@@ -62,4 +62,22 @@ public boolean isDone() {
     map.cleanQueue();
     assertThat(counters).isEmpty();
   }
+
+  @Test
+  public void gcAndRecreate() {
+    @SuppressWarnings("UnusedVariable") // assign to null for GC only
+    AtomicLong counter = map.getOrCreate(CLUSTER, EDS_SERVICE_NAME);
+    final CounterReference ref = counters.get(CLUSTER).get(EDS_SERVICE_NAME);
```
Comment (ejona86) [inline xds/src/test/java/io/grpc/xds/SharedCallCounterMapTest.java:70]: FYI, you can call `ref.clear()` and `ref.enqueue()` manually instead of relying on GC.

File: xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java (hunk 2 above)
Comment (dapengzhang0) [reply xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java:81]: Done. TIL thanks.

**Review by ejona86 — APPROVED** [review]
