### PR TITLE
Fix issue: CallOptions is not thread-safe.

### LINKED ISSUE #9658: CallOptions is not thread-safe
Although it is annotated with `Immutable`, [CallOptions](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/CallOptions.java) has no final fields, and is therefore not actually thread-safe. The javadoc for the `Immutable` annotations states:

> The class to which this annotation is applied is immutable. This means that its state cannot be seen to change by callers.

This can be shown to be violated with a simple [JCStress](https://github.com/openjdk/jcstress) test case; here is an [example](https://github.com/kilink/grpc-jcstress/blob/main/src/jcstress/java/net/kilink/jcstress/CallOptionsTest.java).

When I run the above test case on my aarch64 machine, I get results such as the following, showing memory visibility issues:

```
       Observed state   Occurrences   Expectation  Interpretation                                              
  -1, -1, not visible   125,492,608    ACCEPTABLE  Object is not seen yet.                                     
    -2, -2, authority            11     FORBIDDEN  Everything else is forbidden.                               
         -2, -2, null             8     FORBIDDEN  Everything else is forbidden.                               
     5, -2, authority             6     FORBIDDEN  Everything else is forbidden.                               
      5, 5, authority     2,139,458    ACCEPTABLE  Seen the complete object.           
```

Although to be honest, the above test case is not really needed, as one can simply refer to the JLS [1] [2] to see that CallOptions is not safely published and is therefore not guaranteed to be seen as consistent across threads.

The CallOptions class has a [comment ](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/CallOptions.java#L46-L48) explaining why the fields are not final, and it seems to be for stylistic reasons. I would think correctness would outweigh such concerns and the fields should be made final, or the `Immutable` annotation should be removed from the class.

[1] https://shipilev.net/blog/2014/safe-public-construction/#_safe_publication
[2] https://docs.oracle.com/javase/specs/jls/se7/html/jls-17.html#jls-17.5

### PR DESCRIPTION
**Pull request by pandaapo**
Fixes #9658 

Although `CallOptions` is annotated by `@Immutable`, its fields are not final. So it's not truly immutable, namely not thread-safe.

This PR add `final` to all fields of `CallOptions` and remove `@Immutable`. Using internal builder class to keep flexibility of constructing `CallOptions `.

### CODE REVIEW

File: api/src/main/java/io/grpc/CallOptions.java [hunk 1]
```diff
@@ -403,8 +471,9 @@ public CallOptions withMaxInboundMessageSize(int maxSize) {
   @ExperimentalApi("https://github.com/grpc/grpc-java/issues/2563")
   public CallOptions withMaxOutboundMessageSize(int maxSize) {
     checkArgument(maxSize >= 0, "invalid maxsize %s", maxSize);
-    CallOptions newOptions = new CallOptions(this);
-    newOptions.maxOutboundMessageSize = maxSize;
+    CallOptions newOptions = fullBuild(this)
+            .maxOutboundMessageSize(maxSize)
+            .build();
     return newOptions;
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:477]: The local var `newOptions` seems unnecessary. You could just do:

```
return fullBuild(this)
            .maxOutboundMessageSize(maxSize)
            .build();
```

Same for all other similar usage elsewhere

File: api/src/main/java/io/grpc/CallOptions.java [hunk 2]
```diff
@@ -427,19 +496,20 @@ public Integer getMaxOutboundMessageSize() {
...
-    authority = other.authority;
-    credentials = other.credentials;
-    executor = other.executor;
-    compressorName = other.compressorName;
-    customOptions = other.customOptions;
-    waitForReady = other.waitForReady;
-    maxInboundMessageSize = other.maxInboundMessageSize;
-    maxOutboundMessageSize = other.maxOutboundMessageSize;
-    streamTracerFactories = other.streamTracerFactories;
+  private Builder fullBuild(CallOptions other) {
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:501]: - why is this method non-static?
- instead of `fullBuild` the canonical pattern is to define `toBuilder()` as an instance method so all callers of `fullBuild` will instead call `toBuilder()` on `other`.

File: api/src/main/java/io/grpc/CallOptions.java [hunk 3]
```diff
@@ -28,55 +29,129 @@
...
+
+  private static class Builder {
+    private Deadline deadline;
+    private Executor executor;
+    private String authority;
+    private CallCredentials credentials;
+    private String compressorName;
+    private Object[][] customOptions = new Object[0][2];
+    // Unmodifiable list
+    private List<ClientStreamTracer.Factory> streamTracerFactories = Collections.emptyList();
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:96]: How do you ensure this is unmodifiable list? On line 147 you are just assigning the passed value (instead of creating an unmodifiable list)

File: api/src/main/java/io/grpc/CallOptions.java [hunk 4]
```diff
@@ -89,17 +164,15 @@ public final class CallOptions {
    */
   @ExperimentalApi("https://github.com/grpc/grpc-java/issues/1767")
   public CallOptions withAuthority(@Nullable String authority) {
-    CallOptions newOptions = new CallOptions(this);
-    newOptions.authority = authority;
+    CallOptions newOptions = fullBuild(this).authority(authority).build();
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:167]: with copy propagation you don't need the `newOptions` local.

```
return this.toBuilder().authority(authority).build();
```

File: api/src/main/java/io/grpc/CallOptions.java [hunk 5]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright 2015 The gRPC Authors
+ * Copyright 2015, 2022 The gRPC Authors
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:2]: I don't think we add or update the year in an existing copyright notice. Have you seen this elsewhere in the grpc code?

File: api/src/main/java/io/grpc/CallOptions.java [hunk 6]
```diff
@@ -20,6 +20,7 @@
 
 import com.google.common.base.MoreObjects;
 import com.google.common.base.Preconditions;
+
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:23]: Pls get rid of this unnecessary newline

**Review by sanjaypujare — CHANGES_REQUESTED** [review]
couple of comments added

File: api/src/main/java/io/grpc/CallOptions.java (hunk 2 above)
Comment (ejona86) [reply api/src/main/java/io/grpc/CallOptions.java:501]: When I tested the performance of the compiler to optimize away the Builder allocation, I used `new Builder(this)` in each of the methods. That way the allocation never escaped from the method. Having a `toBuilder()` should still be possible to optimize away the allocation, but I think it becomes more dependent on inlining. I suggest we move this to Builder's constructor and explicitly call `new` in each `with` method.

Part of the trouble here is Java's escape analysis is powerful, but varies highly on the whims of the JIT. We also want Dalvik/ART to work well for Android. So the least amount of guessing and making what we are doing clear is helpful.

Comment (sanjaypujare) [reply api/src/main/java/io/grpc/CallOptions.java:501]: > ...but I think it becomes more dependent on inlining. ...

Interesting. From this [article](https://blogs.oracle.com/javamagazine/post/escape-analysis-in-the-hotspot-jit-compiler): 

"EA provides an interesting insight: it is a feature that depends upon another optimization (automatic inlining) and is essentially useless without it."  

so I thought dependency on inlining is inherent.

Comment (sanjaypujare) [reply api/src/main/java/io/grpc/CallOptions.java]: > > * why is this method non-static?
> 
> Thanks for your review. I want to know what the benefit is?

If a method doesn't use any instance data it should be marked static - so its callable from more sites. Even otherwise it is a good practice.

File: api/src/main/java/io/grpc/CallOptions.java [hunk 7]
```diff
@@ -28,55 +29,129 @@
...
+    this.credentials = builder.credentials;
+    this.compressorName = builder.compressorName;
+    this.customOptions = builder.customOptions;
+    this.streamTracerFactories = builder.streamTracerFactories;
+    this.waitForReady = builder.waitForReady;
+    this.maxInboundMessageSize = builder.maxInboundMessageSize;
+    this.maxOutboundMessageSize = builder.maxOutboundMessageSize;
+  }
+
+  private static class Builder {
```
[the remark this answers is not in the document]
Comment (ejona86) [reply api/src/main/java/io/grpc/CallOptions.java]: Just assign to the fields directly, as they are accessible now (since you did (2) and (3)).

```java
  public CallOptions withDeadline(@Nullable Deadline deadline) {
    Builder b = toBuilder(this);
    b.deadline = deadline;
    return b.build();
  }
```

File: api/src/main/java/io/grpc/CallOptions.java [hunk 8]
```diff
@@ -156,19 +182,19 @@ public Deadline getDeadline() {
...
 
   /**
    * Disables 'wait for ready' feature for the call.
    * This method should be rarely used because the default is without 'wait for ready'.
    */
   public CallOptions withoutWaitForReady() {
-    CallOptions newOptions = new CallOptions(this);
-    newOptions.waitForReady = Boolean.FALSE;
-    return newOptions;
+    Builder builder = new Builder();
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:195]: Why is this not using `toBuilder`? It loses previous values from `this` instance.

File: api/src/main/java/io/grpc/CallOptions.java [hunk 9]
```diff
@@ -328,7 +354,8 @@ public <T> CallOptions withOption(Key<T> key, T value) {
       }
     }
 
-    newOptions.customOptions = new Object[customOptions.length + (existingIdx == -1 ? 1 : 0)][2];
+    builder.customOptions = new Object[customOptions.length + (existingIdx == -1 ? 1 : 0)][2];
+    CallOptions newOptions = builder.build();
```
Comment (sanjaypujare) [inline api/src/main/java/io/grpc/CallOptions.java:358]: I guess this and the following code (next 9 lines) is most probably correct but quite confusing. Why not add the new custom option to `builder.customOptions` first and then just return `builder.build()`. So there is no real need to declare `newOptions` and manipulate it

**Review by sanjaypujare — APPROVED** [review]
Looks good but I would like to see my last comment addressed

**Comment by sanjaypujare** [comment]
> 
> I noticed this. I want to fix it but my OS is windows. I can not reproduce this failure.

This could just be a flake because of its nature but it happens to be in CallOptionsTest which is the part you touched. Not sure what you were planning to fix.

Let me rerun the tests and see what happens.

File: api/src/main/java/io/grpc/CallOptions.java [hunk 10]
```diff
@@ -41,42 +41,68 @@ public final class CallOptions {
...
+    this.maxOutboundMessageSize = builder.maxOutboundMessageSize;
+  }
 
+  static class Builder {
+    Deadline deadline;
+    Executor executor;
+    String authority;
+    CallCredentials credentials;
+    String compressorName;
+    Object[][] customOptions = new Object[0][2];
```
Comment (ejona86) [inline api/src/main/java/io/grpc/CallOptions.java:95]: Although this object will only be used once, this will create it all the time. This and the emptyList() below are just for DEFAULT, so we should just make a static method to configure the default builder, or use a static block. I'll do that as a follow-up.

The optimizer should optimize these away, but it would still be there on startup and cause a non-trivial constructor. So it isn't a big deal, but still worth doing.

For reference, it'll look something like this:

```
static {
  Builder b = new Builder();
  b.customOptions = new Object[0][2];
  b.streamTracerFactories = Collections.emptyList();
  DEFAULT = b.build();
}

// or

public static final CallOptions DEFAULT = newDefault();

private static CallOptions newDefault() {
  Builder b = new Builder();
  b.customOptions = new Object[0][2];
  b.streamTracerFactories = Collections.emptyList();
  return b.build();
}
```

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
@pandaapo, thank you!
