### PR TITLE
core: Remove builder class signature rewriter

### LINKED ISSUE #7211: Hide AbstractManagedChannelImplBuilder from public API
Transport implementations extend `io.grpc.internal.AbstractManagedChannelImplBuilder` to obtain most of their builder implementations. However, this leaks to the user in the Javadoc and with an `api` dependency in Gradle. The Javadoc in particular is a confusing mess because it isn't clear what is stable, experimental, and internal. Since we don't generate `io.grpc.internal` Javadoc and since the extending class "shadows" the base `ManagedChannelBuilder`, it also means the user is unable to click links to get to documentation for a large number of its methods. We should avoid extending AbstractManagedChannelImplBuilder in public (non-internal) classes.

To do this, we should extend ForwardingChannelBuilder instead (probably extending the Simple* version, which would need to be created). Transport implementations would create a AbstractManagedChannelImplBuilder and forward to it. We don't want to remove (useful) public methods in this process and break users, so we should make sure that there aren't any stray public methods in AbstractManagedChannelImplBuilder that would be dropped in the process.

The only abstract method in AbstractManagedChannelImplBuilder is `buildTransportFactory()`. We should probably inject that method in the constructor and convert the class to concrete, non-abstract. To simplify migration we can create ManagedChannelImplBuilder as a shim on top of AbstractManagedChannelImplBuilder. The shim could override some protected methods and make them public. It can also provide a setter for the checkAuthority override used by things like NettyChannelBuilder. Once all classes (external and internal) are migrated we can remove AbstractManagedChannelImplBuilder and combine it with the shim. If some classes still extend ManagedChannelImplBuilder that may be okay, but we should try to avoid such inheritance if possible.

The same should be done for AbstractServerImplBuilder.

### LINKED ISSUE #8611: sometimes build fails with "Execution failed for task ':grpc-core:compileJava'. > assert i != -1"
### What version of gRPC-Java are you using?
incremental build from 0376de15b to 1f90e0e28 but happened before also
### What is your environment?
ubuntu-18.04, openJDK-11
### What did you expect to see?
build should succeed cleanly
### What did you see instead?
```
$ git fetch github 
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 40 (delta 15), reused 25 (delta 8), pack-reused 0
Unpacking objects: 100% (40/40), done.
From https://github.com/grpc/grpc-java
   0376de15b..1f90e0e28  master     -> github/master
$ git merge --ff-only 
Updating 0376de15b..1f90e0e28
Fast-forward
 core/src/main/java/io/grpc/util/CertificateUtils.java     |  18 +++++++--
 core/src/test/java/io/grpc/util/CertificateUtilsTest.java |  10 +++++
 testing/src/main/resources/certs/README                   |   5 +++
 testing/src/main/resources/certs/ecdsa.key                |   5 +++
 xds/src/main/java/io/grpc/xds/Bootstrapper.java           |  93 +++++++++++++++++++++++++++++++++++++++++++-
 xds/src/main/java/io/grpc/xds/BootstrapperImpl.java       | 135 +++++++++++++++++++++++++++++++++++++++++++++-------------------
 xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java   |  96 +++++++++++++++++++++++++++++++++++++++++++++
 7 files changed, 318 insertions(+), 44 deletions(-)
 create mode 100644 testing/src/main/resources/certs/ecdsa.key
$ ./gradlew -PskipAndroid=true -PskipCodegen=true build
Starting a Gradle Daemon (subsequent builds will be faster)
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true
> Task :grpc-core:compileJava FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/morgwai/projects/upstreamProjects/grpc-java/core/build.gradle' line: 68

* What went wrong:
Execution failed for task ':grpc-core:compileJava'.
> assert i != -1
         | |
         | false
         -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
9 actionable tasks: 5 executed, 4 up-to-date
```
simply repeating the build command made it succeed:
```
$ ./gradlew -PskipAndroid=true -PskipCodegen=true build
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

> Task :grpc-xds:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :grpc-interop-testing:test
[jetty-alpn-agent][ warn] Could not find a matching alpn-boot jar for Java version: 11.0.11

> Task :grpc-netty:test
[jetty-alpn-agent][ warn] Could not find a matching alpn-boot jar for Java version: 11.0.11

BUILD SUCCESSFUL in 6m 31s
324 actionable tasks: 139 executed, 185 up-to-date
```
### Steps to reproduce the bug
very hard to reproduce reliably: happened to me like 2 times across about 30 builds during last 2 months. As far as I remember the previous time it also happened during an incremental build, but not 100% sure.

### PR DESCRIPTION
**Pull request by sergiitk**
1. It's been long enough. Removes temporary ABI hack #7834.
2. Removes `AbstractManagedChannelImplBuilder` and `AbstractServerImplBuilder`
3. Introduces `ForwardingChannelBuilder2`, see details in #10585
4. Closes #7211
5. Fixes javadoc — makes the docs for the inherited methods in the channel and server builders visible:
    `NettyChannelBuilder` before and after:
    image
    image
    `NettyServerBuilder` before and after:
    image
    image

---

### ABI BREAKING!

This breaks the ABI of the classes listed below.

Users that recompiled  their code using grpc-java [`v1.36.0`](https://github.com/grpc/grpc-java/releases/tag/v1.36.0) (released on Feb 23, 2021) and later, ARE NOT AFFECTED.

Users that compiled their source using grpc-java earlier than [`v1.36.0`](https://github.com/grpc/grpc-java/releases/tag/v1.36.0) need to recompile when upgrading to grpc-java `v1.59.0`. Otherwise the code will fail on runtime with `NoSuchMethodError`. For example, code:

```java
NettyChannelBuilder.forTarget("localhost:100").maxRetryAttempts(2);
```

Will fail with

> `java.lang.NoSuchMethodError: 'io.grpc.internal.AbstractManagedChannelImplBuilder io.grpc.netty.NettyChannelBuilder.maxRetryAttempts(int)'`

Server builder example: code

```java
NettyServerBuilder.forPort(80).directExecutor();
```

Will fail with

> `java.lang.NoSuchMethodError: 'io.grpc.internal.AbstractServerImplBuilder
  io.grpc.netty.NettyServerBuilder.directExecutor()'`

#### Affected classes

Class `AbstractManagedChannelImplBuilder` is deleted, and no longer in the class hierarchy of the channel builders:
- `io.grpc.netty.NettyChannelBuilder`
- `io.grpc.okhttp.OkhttpChannelBuilder`
- `grpc.cronet.CronetChannelBuilder`

Class `AbstractServerImplBuilder` is deleted, and no longer in the class hierarchy of the server builders:
- `io.grpc.netty.NettyServerBuilder`
- `io.grpc.inprocess.InProcessServerBuilder`

---

#### Hide `AbstractManagedChannelImplBuilder` — initial attempt
1. Issue #7211
2. PR #7359
3. PR #7386
4. PR #7418
6. PR #7424
7. PR #7432
8. Released in [v1.33.0](https://github.com/grpc/grpc-java/releases/tag/v1.33.0)

#### ABI Backward Compatibility Support
1. Issue #7552
   - Fixed in PR #7564
   - Gist: [gRPC-NettyChannelBuilder-ABI-demo.md](https://gist.github.com/sergiitk/39583f20906df1813f5e170317a35dc4) - gRPC NettyChannelBuilder binary backwards-incompatibily demonstration
   - Released in [v1.33.1](https://github.com/grpc/grpc-java/releases/tag/v1.33.1)
2. PR #7834 
   - Released in [v1.36.0](https://github.com/grpc/grpc-java/releases/tag/v1.36.0)
3. Issue #8313 
    - Fixed in PR #8607
    - Released in [v1.42.0](https://github.com/grpc/grpc-java/releases/tag/v1.42.0)
4. Fixes #8611

### CODE REVIEW

File: api/src/main/java/io/grpc/ForwardingChannelBuilder.java [hunk 1]
```diff
@@ -28,40 +26,27 @@
  * A {@link ManagedChannelBuilder} that delegates all its builder methods to another builder by
  * default.
  *
- * @param <T> The type of the subclass extending this abstract class.
+ * <p>Important! Use {@link ForwardingChannelBuilder2} instead!
+ *
+ * <p>This class mistakenly used {@code <T extends ForwardingChannelBuilder<T>>} which causes
+ * return types to be {@link ForwardingChannelBuilder} instead of {@link ManagedChannelBuilder}.
+ * This pollutes the ABI of its subclasses with undesired method signatures.
+ * {@link ForwardingChannelBuilder2} generates return correct types; use it instead.
```
Comment (ejona86) [inline api/src/main/java/io/grpc/ForwardingChannelBuilder.java:34]: s/return correct/correct return/

**Review by ejona86 — APPROVED** [review]

File: api/src/main/java/io/grpc/ForwardingChannelBuilder.java (hunk 1 above)
Comment (sergiitk) [reply api/src/main/java/io/grpc/ForwardingChannelBuilder.java]: Thanks! Fixed

**Comment by sergiitk** [comment]
For posterity, here's some tests assets you can use to verify:

```java
package org.sergii.playground.netty.abi;

import io.grpc.netty.NettyChannelBuilder;

public class Main {

  public static void main(String[] args) {
    NettyChannelBuilder ncb = NettyChannelBuilder.forTarget("localhost:100");

    try {
      // Moved from AbstractManagedChannelImplBuilder to NettyChannelBuilder in 1.33.0
      ncb.maxInboundMessageSize(100);
    } catch (Throwable e) {
      System.out.println(e);
    }

    try {
      // maxRetryAttempts:
      //  <1.33.0: Inherited from AbstractManagedChannelImplBuilder
      //  =1.33.0: Inherited from ForwardingChannelBuilder
      // >=1.33.1: Inherited from tmp AbstractManagedChannelImplBuilder
      // >=1.59.0: Inherited ForwardingChannelBuilder2
      ncb.maxRetryAttempts(200);
    } catch (Throwable e) {
      System.out.println(e);
    }

    // note: maxInboundMetadataSize is the only method AbstractManagedChannelImplBuilder inherits
    //       from ManagedChannelBuilder.

    System.out.println(ncb);
  }
}
```


### <`v1.59.x`

```sh
# v1.32.3 + v1.58.0
❯ java -cp "./builders-abi-1.32.3.jar:./grpc-1.58.0/*" org.sergii.playground.netty.abi.Main
NettyChannelBuilder{delegate=io.grpc.internal.ManagedChannelImplBuilder@1460a8c0}

# v1.35.0 + v1.58.0
❯ java -cp "./builders-abi-1.35.0.jar:./grpc-1.58.0/*" org.sergii.playground.netty.abi.Main
NettyChannelBuilder{delegate=io.grpc.internal.ManagedChannelImplBuilder@1460a8c0}

# v1.36.0 + v1.58.0
❯ java -cp "./builders-abi-1.36.0.jar:./grpc-1.58.0/*" org.sergii.playground.netty.abi.Main
NettyChannelBuilder{delegate=io.grpc.internal.ManagedChannelImplBuilder@1460a8c0}
```

### >=`v1.59.x` BREAKING

```sh
# v1.32.3 + v1.59.x
❯ java -cp "./builders-abi-1.32.3.jar:./grpc-1.59.0-SNAPSHOT/*" org.sergii.playground.netty.abi.Main
java.lang.NoSuchMethodError: 'io.grpc.internal.AbstractManagedChannelImplBuilder io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize(int)'
java.lang.NoSuchMethodError: 'io.grpc.internal.AbstractManagedChannelImplBuilder io.grpc.netty.NettyChannelBuilder.maxRetryAttempts(int)'
NettyChannelBuilder{delegate=io.grpc.internal.ManagedChannelImplBuilder@1460a8c0}

# v1.35.0 + v1.59.x
❯ java -cp "./builders-abi-1.35.0.jar:./grpc-1.59.0-SNAPSHOT/*" org.sergii.playground.netty.abi.Main
java.lang.NoSuchMethodError: 'io.grpc.internal.AbstractManagedChannelImplBuilder io.grpc.netty.NettyChannelBuilder.maxRetryAttempts(int)'
NettyChannelBuilder{delegate=io.grpc.internal.ManagedChannelImplBuilder@1460a8c0}

# v1.36.0 + v1.59.x
❯ java -cp "./builders-abi-1.36.0.jar:./grpc-1.59.0-SNAPSHOT/*" org.sergii.playground.netty.abi.Main
NettyChannelBuilder{delegate=io.grpc.internal.ManagedChannelImplBuilder@1460a8c0}
```

**Comment by sergiitk** [comment]
cc @njhill

**Comment by joroKr21** [comment]
If it's breaking binary backwards compatibility it should be a new major version.
Otherwise we get `java.lang.ClassNotFoundException: io.grpc.internal.AbstractManagedChannelImplBuilder`

**Comment by sergiitk** [comment]
@joroKr21 Only classes marked with `@ExperimentalApi` were broken. We could've kept them broken (#7552) three years ago, when the breaking was originally made, but we went out of our way to provide a stop-gap solution (#7834), allowing our users nearly two years to rebuild their code.

**Comment by joroKr21** [comment]
Hmm ok, but I don't think I'm using any experimental APIs.
Looking at a stack trace, it seems to be coming from `ManagedChannelBuilder.forAddress` which is not experimental.
```
java.lang.NoClassDefFoundError: io/grpc/internal/AbstractManagedChannelImplBuilder
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:142)
	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:103)
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:44)
```

Is

**Comment by ejona86** [comment]
@joroKr21, that's probably resolved if you upgrade grpc-netty/grpc-netty-shaded/grpc-okhttp (whichever you are using) to v1.59.0+.

**Comment by joroKr21** [comment]
Ok - this is all coming from transitive dependencies, but can I assume that:
 * grpc-netty/grpc-netty-shaded/grpc-okhttp >= v1.59.0 is compatible with grpc-core < v1.59.0
 * grpc-netty/grpc-netty-shaded/grpc-okhttp < v1.59.0 is **not** compatible with grpc-core >= v1.59.0
 * grpc-netty/grpc-netty-shaded/grpc-okhttp < v1.59.0 is compatible with grpc-core < v1.59.0
 * grpc-netty/grpc-netty-shaded/grpc-okhttp >= v1.59.0 is compatible with grpc-core >= v1.59.0

So the only problem is when core is higher version than netty etc?

**Comment by ejona86** [comment]
grpc-okhttp uses internal APIs of grpc-core (which is only internal APIs these days). So technically the only thing _guaranteed_ to work is using the same version. grpc-bom can make that easier. Previously we used version pinning (e.g., `[1.59.0]`) to have Maven complain if there was a skew, but Maven wasn't reliable and Gradle didn't consider that an error, so it was removed in v1.56.0.

Things have happened to be compatible for a while if you do not _downgrade_ dependencies. So grpc-core could be newer than grpc-okhttp and things have worked fine for a while it seems. That's because we are generally adding new things, and not removing stuff.

This specific instance we removed something from grpc-core, so yeah, upgrading it is what caused the problem.
