### PR TITLE
cronet : Update library + Move to StableAPIs in Cronet

### LINKED ISSUE #10396: grpc-cronet: ExperimentalBidirectionalStream, ExperimentalCronetEngine are deprecated
I Attempted updating cronet dependencies in #10359:

```
org.chromium.net:cronet-api 108.5359.79 -> 113.5672.61
org.chromium.net:cronet-embedded 108.5359.79 -> 113.5672.61
```

Gradle build failed with various deprecation warnings:

<details>
<summary>gradle build log</summary>

(shortened repeated warnings)

```java
> Task :grpc-cronet:compileDebugJavaWithJavac
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:50: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
import org.chromium.net.ExperimentalBidirectionalStream;
                       ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:51: warning: [deprecation] ExperimentalCronetEngine in org.chromium.net has been deprecated
import org.chromium.net.ExperimentalCronetEngine;
                       ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:58: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
import org.chromium.net.ExperimentalBidirectionalStream;
                       ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:320: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
      ExperimentalBidirectionalStream.Builder builder =
      ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:320: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
      ExperimentalBidirectionalStream.Builder builder =
                                     ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:321: warning: [deprecation] ExperimentalCronetEngine in org.chromium.net has been deprecated
          ((ExperimentalCronetEngine) cronetEngine)
            ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:332: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
    private static void setTrafficStatsTag(ExperimentalBidirectionalStream.Builder builder,
                                           ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:332: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
    private static void setTrafficStatsTag(ExperimentalBidirectionalStream.Builder builder,
                                                                          ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:338: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
              setTrafficStatsTagMethod = ExperimentalBidirectionalStream.Builder.class
                                         ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:338: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
              setTrafficStatsTagMethod = ExperimentalBidirectionalStream.Builder.class
                                                                        ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:361: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
    private static void setTrafficStatsUid(ExperimentalBidirectionalStream.Builder builder,
                                           ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:361: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
    private static void setTrafficStatsUid(ExperimentalBidirectionalStream.Builder builder,
                                                                          ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:367: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
              setTrafficStatsUidMethod = ExperimentalBidirectionalStream.Builder.class
                                         ^
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:367: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
              setTrafficStatsUidMethod = ExperimentalBidirectionalStream.Builder.class
                                                                        ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:196: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
        ExperimentalBidirectionalStream.Builder expBidiStreamBuilder =
        ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:196: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
        ExperimentalBidirectionalStream.Builder expBidiStreamBuilder =
                                       ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:197: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
            (ExperimentalBidirectionalStream.Builder) builder;
             ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:197: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
            (ExperimentalBidirectionalStream.Builder) builder;
                                            ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:369: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
  private static void addRequestAnnotation(ExperimentalBidirectionalStream.Builder builder,
                                           ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:369: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
  private static void addRequestAnnotation(ExperimentalBidirectionalStream.Builder builder,
                                                                          ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:375: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
            addRequestAnnotationMethod = ExperimentalBidirectionalStream.Builder.class
                                         ^
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java:375: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
            addRequestAnnotationMethod = ExperimentalBidirectionalStream.Builder.class
                                                                        ^
22 warnings

> Task :grpc-cronet:compileDebugUnitTestJavaWithJavac
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:57: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
import org.chromium.net.ExperimentalBidirectionalStream;
                       ^
cronet/src/test/java/io/grpc/cronet/CronetChannelBuilderTest.java:38: warning: [deprecation] ExperimentalCronetEngine in org.chromium.net has been deprecated
import org.chromium.net.ExperimentalCronetEngine;
                       ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:79: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
  @Mock private ExperimentalBidirectionalStream cronetStream;
                ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:81: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
  @Mock private ExperimentalBidirectionalStream.Builder builder;
                ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:81: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
  @Mock private ExperimentalBidirectionalStream.Builder builder;
                                               ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:684: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
    ExperimentalBidirectionalStream.Builder getBuilder =
    ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:684: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
    ExperimentalBidirectionalStream.Builder getBuilder =
                                   ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:685: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
             ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:685: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
                                            ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:741: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
    ExperimentalBidirectionalStream.Builder builder =
    ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:741: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
    ExperimentalBidirectionalStream.Builder builder =
                                   ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:742: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
             ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:742: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
                                            ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:773: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
    ExperimentalBidirectionalStream.Builder builder =
    ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:773: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
    ExperimentalBidirectionalStream.Builder builder =
                                   ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:774: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
             ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:774: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
                                            ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:813: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
    ExperimentalBidirectionalStream.Builder builder =
    ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:813: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
    ExperimentalBidirectionalStream.Builder builder =
                                   ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:814: warning: [deprecation] ExperimentalBidirectionalStream in org.chromium.net has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
             ^
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:814: warning: [deprecation] Builder in ExperimentalBidirectionalStream has been deprecated
        mock(ExperimentalBidirectionalStream.Builder.class);
                                            ^
cronet/src/test/java/io/grpc/cronet/CronetChannelBuilderTest.java:53: warning: [deprecation] ExperimentalCronetEngine in org.chromium.net has been deprecated
  @Mock private ExperimentalCronetEngine mockEngine;
                ^
22 warnings

```
</details>

### Steps to reproduce the bug

Apply patch:
```
diff --git a/gradle/libs.versions.toml b/gradle/libs.versions.toml
index 7217d560a..b022132a9 100644
--- a/gradle/libs.versions.toml
+++ b/gradle/libs.versions.toml
@@ -36,8 +36,8 @@ auto-value-annotations = "com.google.auto.value:auto-value-annotations:1.10.2"
 checkstyle = "com.puppycrawl.tools:checkstyle:10.12.1"
 commons-math3 = "org.apache.commons:commons-math3:3.6.1"
 conscrypt = "org.conscrypt:conscrypt-openjdk-uber:2.5.2"
-cronet-api = "org.chromium.net:cronet-api:108.5359.79"
-cronet-embedded = "org.chromium.net:cronet-embedded:108.5359.79"
+cronet-api = "org.chromium.net:cronet-api:113.5672.61"
+cronet-embedded = "org.chromium.net:cronet-embedded:113.5672.61"
 errorprone-annotations = "com.google.errorprone:error_prone_annotations:2.20.0"
 errorprone-core = "com.google.errorprone:error_prone_core:2.20.0"
 google-api-protos = "com.google.api.grpc:proto-google-common-protos:2.22.0"
```

Then do `gradle build`.

### PR DESCRIPTION
**Pull request by Ashok-Varma**
In this Pull Request
1. Cronet is updated to `119.6045.31` from `108.5359.79`, In which Experimental API's are deprecated and moved to Stable Interfaces.
2. grpc-cronet Moved Experimental API's to Stable Interfaces
3. Removed use of reflection as Experimental API's are no longer in use (which are introdced in #6111)

Minor Changes
1. Updated JavaDoc : Android Permission from [`MODIFY_NETWORK_ACCOUNTING` (deprecated)](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/AndroidManifest.xml#6416) to `UPDATE_DEVICE_STATS`
2. Update to JAVA-8 API's to improve code readability
3. Moved from `Charset.forName("UTF-8")` to `StandardCharsets.UTF_8` Standard

Fixes #10396 (@sergiitk)

### CODE REVIEW

File: cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java [hunk 1]
```diff
@@ -173,7 +173,7 @@ final CronetChannelBuilder setTrafficStatsTag(int tag) {
    * Sets specific UID to use when accounting socket traffic caused by this channel. See {@link
    * android.net.TrafficStats} for more information. Designed for use when performing an operation
    * on behalf of another application. Caller must hold {@link
-   * android.Manifest.permission#MODIFY_NETWORK_ACCOUNTING} permission. By default traffic is
+   * android.Manifest.permission#UPDATE_DEVICE_STATS} permission. By default traffic is
```
Comment (Ashok-Varma) [inline cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:176]: https://android.googlesource.com/platform/frameworks/base/+/master/core/res/AndroidManifest.xml#6416

MODIFY_NETWORK_ACCOUNTING is deprecated and recommendation is to use UPDATE_DEVICE_STATS

File: cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java [hunk 2]
```diff
@@ -132,7 +132,7 @@ protected ManagedChannelBuilder<?> delegate() {
    * Sets the maximum message size allowed to be received on the channel. If not called,
    * defaults to {@link io.grpc.internal.GrpcUtil#DEFAULT_MAX_MESSAGE_SIZE}.
    */
-  public final CronetChannelBuilder maxMessageSize(int maxMessageSize) {
+  public CronetChannelBuilder maxMessageSize(int maxMessageSize) {
```
Comment (Ashok-Varma) [inline cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java:135]: CronetChannelBuilder Class is final. Methods inherit final from the class, removing explicitly call out final.
`public final class CronetChannelBuilder extends ForwardingChannelBuilder2<CronetChannelBuilder> {`

**Comment by Ashok-Varma** [comment]
Hi @sergiitk / @ejona86  / @temawi,

I've updated changes in to different commits. It's open for review

File: cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java [hunk 3]
```diff
@@ -166,13 +166,10 @@ public Runnable start(Listener listener) {
...
       started = true;
     }
-    return new Runnable() {
-      @Override
-      public void run() {
-        attrs = CronetClientTransport.this.listener.filterTransport(attrs);
-        // Listener callbacks should not be called simultaneously
-        CronetClientTransport.this.listener.transportReady();
-      }
+    return () -> {
```
Comment (ejona86) [inline cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java:169]: We can merge this change, but I do think we want to avoid going around replacing code with lambdas just because we can. The anonymous class is still perfectly acceptable.

(It's much more understandable with the `Runnable::run` in the test.)

File: cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java [hunk 4]
```diff
@@ -207,26 +202,22 @@ public void write() {
...
-    Map<String, String> headers = new HashMap<String, String>();
+    Map<String, String> headers = new HashMap<>();
     headers.put(":status", status);
     headers.put("content-type", "application/grpc");
     headers.put("test-key", "test-value");
-    List<Map.Entry<String, String>> headerList = new ArrayList<Map.Entry<String, String>>(3);
-    for (Map.Entry<String, String> entry : headers.entrySet()) {
-      headerList.add(entry);
-    }
+    List<Map.Entry<String, String>> headerList = new ArrayList<>(3);
```
Comment (ejona86) [inline cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:209]: You could go even further, right?
```java
return new ArrayList<>(headers.entrySet());
```

**Review by ejona86 — COMMENTED** [review]
This looks fine to me, but I'm not sure if enough Android devices have the stable API. We may need to fall-back to the experimental API to reach more devices. @temawi, would you be able to investigate that?

**Comment by ejona86** [comment]
> I was just wondering on Linux and Macos artifacts taking time (those are stalled for ~10 days), does it signify any problem in the builds ?

It's not a problem. We have to manually start those builds by adding that kokoro label.

File: cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java (hunk 3 above)
Comment (Ashok-Varma) [reply cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java:169]: Makes Sense, Updated

File: cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java (hunk 4 above)
Comment (Ashok-Varma) [reply cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java:209]: Yup, Updated
This are results of just depending on IDE suggestions :p

**Comment by Ashok-Varma** [comment]
> This looks fine to me, but I'm not sure if enough Android devices have the stable API. We may need to fall-back to the experimental API to reach more devices. @temawi, would you be able to investigate that?

I agree to this, Adding little-bit of background :
- [ExperimentalAPI deprecation](https://chromium-review.googlesource.com/c/chromium/src/+/3975392) done on Oct 27, 2022
- Any Custom Implementation of Cronet (if API is not yet updated), Needs to update the API +move the experimental implementations to CronetEngine.
- All Googles cronet implementations (embedded, fallback, play-services) are compatible with new API.

**Comment by temawi** [comment]
> > This looks fine to me, but I'm not sure if enough Android devices have the stable API. We may need to fall-back to the experimental API to reach more devices. @temawi, would you be able to investigate that?
> 
> I agree to this, Adding little-bit of background :
> 
> * [ExperimentalAPI deprecation](https://chromium-review.googlesource.com/c/chromium/src/+/3975392) done on Oct 27, 2022
> * Any Custom Implementation of Cronet (if API is not yet updated), Needs to update the API +move the experimental implementations to CronetEngine.
> * All Googles cronet implementations (embedded, fallback, play-services) are compatible with new API.

I also checked with the Cronet team - this should be a safe change to make.

**Comment by Ashok-Varma** [comment]
> @temawi, given the commits are split out, we'll probably want to rebase this instead of squashing (ideally the commits would have `cronet:` prefixes to make scanning easier, but this is fine).

Update commits with `cronet:` prefix

**Comment by ejona86** [comment]
@Ashok-Varma, see [the milestones](https://github.com/grpc/grpc-java/milestones). Minor releases are scheduled every six weeks.
