### PR TITLE
netty: Fix receipt of ClosedChannelException instead of actual error.…

### LINKED ISSUE #1330: Receiving ClosedChannelException instead of actual error
We aren't reporting a helpful error in very simple connectivity cases, like the server port is closed. Here is what it looks like when using the interop client against a non-existent server: 

```
$ ./build/install/grpc-interop-testing/bin/test-client
Running test empty_unary
...
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.Status.asRuntimeException(Status.java:431)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:157)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:106)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:212)
        at io.grpc.testing.integration.AbstractTransportTest.emptyUnary(AbstractTransportTest.java:164)
        at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:220)
        at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:209)
        at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:80)
Caused by: java.nio.channels.ClosedChannelException
```

It seems the problem may also impact other, much harder to diagnose, issues like client certificate validation (like in #1327).

### PR DESCRIPTION
**Pull request by buchgr**
… Fixes #1330.

Our API allows pings to be send even after the transport has been shutdown. We currently
don't handle the case, where the Netty channel has been closed but the NettyClientHandler
has not yet been removed from the pipeline, correctly. That is, we need to query the shutdown
status whenever we receive a ClosedChannelException.

Also, some cleanup.

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java [hunk 1]
```diff
@@ -472,7 +473,11 @@ private void sendPingFrame(ChannelHandlerContext ctx, SendPingCommand msg,
       @Override
       public void operationComplete(ChannelFuture future) throws Exception {
         if (!future.isSuccess()) {
-          finalPing.failed(future.cause());
+          Throwable cause = future.cause();
+          if (cause instanceof ClosedChannelException) {
+            cause = lifecycleManager.getShutdownThrowable();
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: What if getShutdownThrowable() is null?

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 2]
```diff
@@ -238,13 +240,11 @@ public Attributes getAttrs() {
   private Status statusFromFailedFuture(ChannelFuture f) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: Add a comment that this may only be called on the event loop.

**Comment by ejona86** [comment]
LGTM

File: netty/src/main/java/io/grpc/netty/NettyClientHandler.java (hunk 1 above)
Comment (buchgr) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: Then null is propagated to the `PingCallback`. The API spec seems to allow it. If our code works correctly, we should never get a `ClosedChannelException` without the `ClientTransportLifeCycleManager` knowing about it, no?

Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientHandler.java]: I don't believe PingCallback was intended to allow a null cause. And such a null cause is very difficult to debug.

We should just create a status in that case, [like done elsewhere](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L244), maybe with the message "Ping failed but for unknown reason".

**Comment by buchgr** [comment]
@ejona86 PTAL

**Comment by ejona86** [comment]
LGTM
