### PR TITLE
Handle exceptions from LoadBalancer.handleResolvedAddresses()

### LINKED ISSUE #1407: Name resolution failures can cause the call to hang.
If an exception is thrown from NameResolver.Listener.onUpdate(), the call hangs indefinitely and is never closed.  This is a problem if the actual name resolution succeeds, but is not successfully set.

### PR DESCRIPTION
**Pull request by zhangkun83**
And pass the exception to LoadBalancer.handleNameResolutionError(), in
the hope that it canb e propagated to the application, instead of
leaving the RPC hang forever.

Resolves #1407

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/ManagedChannelImpl.java [hunk 1]
```diff
@@ -171,7 +171,13 @@ public void onUpdate(List<ResolvedServerInfo> servers, Attributes config) {
         if (servers.isEmpty()) {
           onError(Status.UNAVAILABLE.withDescription("NameResolver returned an empty list"));
         } else {
-          loadBalancer.handleResolvedAddresses(servers, config);
+          try {
+            loadBalancer.handleResolvedAddresses(servers, config);
+          } catch (RuntimeException e) {
+            // It must be a bug! Push the exception back to LoadBalancer in the hope that it may be
+            // propagated to the application.
+            onError(Status.INTERNAL.withCause(e));
```
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: Please add a message here, since it may not be clear from the exception where it came from.

Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: Though I disagree on principle, for consistency we are also catching Error in other places.  Maybe add it here?

File: core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java [hunk 2]
```diff
@@ -386,6 +388,29 @@ public void nameResolverReturnsEmptyList() {
...
+    ManagedChannel channel = createChannel(nameResolverFactory, NO_INTERCEPTOR);
+    ClientCall<String, Integer> call = channel.newCall(method, CallOptions.DEFAULT);
+    call.start(mockCallListener, new Metadata());
+    assertEquals(1, loadBalancerFactory.balancers.size());
+    LoadBalancer<?> loadBalancer = loadBalancerFactory.balancers.get(0);
+    doThrow(ex).when(loadBalancer).handleResolvedAddresses(
+        Matchers.<List<ResolvedServerInfo>>anyObject(), any(Attributes.class));
+    nameResolverFactory.allResolved();
+    ArgumentCaptor<Status> statusCaptor = ArgumentCaptor.forClass(Status.class);
+    verify(mockCallListener, timeout(1000)).onClose(statusCaptor.capture(), any(Metadata.class));
```
Comment (carl-mastrangelo) [inline core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java]: Please add some new lines to these test methods.  It makes it easier to visually parse the parts of the test.  Normally tests are split up into SETUP, TEST, and VERIFY sections.  It's good to add a new line between each of those parts.  (and leads to good test organization!)

File: core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java [hunk 3]
```diff
@@ -386,6 +388,29 @@ public void nameResolverReturnsEmptyList() {
...
+    FakeNameResolverFactory nameResolverFactory = new FakeNameResolverFactory(false);
+    ManagedChannel channel = createChannel(nameResolverFactory, NO_INTERCEPTOR);
+    ClientCall<String, Integer> call = channel.newCall(method, CallOptions.DEFAULT);
+    call.start(mockCallListener, new Metadata());
+    assertEquals(1, loadBalancerFactory.balancers.size());
+    LoadBalancer<?> loadBalancer = loadBalancerFactory.balancers.get(0);
+    doThrow(ex).when(loadBalancer).handleResolvedAddresses(
+        Matchers.<List<ResolvedServerInfo>>anyObject(), any(Attributes.class));
+    nameResolverFactory.allResolved();
+    ArgumentCaptor<Status> statusCaptor = ArgumentCaptor.forClass(Status.class);
```
Comment (carl-mastrangelo) [inline core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java]: There are a fair number of Captors here.  Maybe make a `@Captor` instance variable up top and reuse between tests?

File: core/src/main/java/io/grpc/internal/ManagedChannelImpl.java (hunk 1 above)
Comment (zhangkun83) [inline core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: I don't know what message to add. The backtrace will clearly show where the exception came from.

Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/ManagedChannelImpl.java]: The cause is often missing from Status's toString, and excludes most of the backtrace.  If the Status was printed out it would not be clear what caused it.  Maybe add "Unexpected Name Resolution failure"  or some other tidbit.

**Comment by zhangkun83** [comment]
@carl-mastrangelo I have addressed all comments. PTAL.

**Comment by carl-mastrangelo** [comment]
LGTM
