### PR TITLE
core: Log a warning in ClientCall.cancel if no detail is provided.

### LINKED ISSUE #2054: Log a warning in ClientCall.cancel if it has neither a message nor exception
https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L347

### PR DESCRIPTION
**Pull request by zhangkun83**
Resolves #2054

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/ClientCallImpl.java [hunk 1]
```diff
@@ -344,10 +344,9 @@ public void cancel(@Nullable String message, @Nullable Throwable cause) {
           status = status.withCause(cause);
         }
         if (message == null && cause == null) {
-          // TODO(zhangkun83): log a warning with this exception once cancel() has been deleted from
-          // ClientCall.
           status = status.withCause(
               new CancellationException("Client called cancel() without any detail"));
+          log.log(Level.WARNING, "Suboptimal use of cancel", status.getCause());
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ClientCallImpl.java]: "Suboptimal" doesn't really tell you what is wrong or how to fix it. Maybe "Cancelled without a message or cause"? We may also want to do that check at the very beginning of the method to avoid racing with whether cancel has already been called.

Comment (zhangkun83) [inline core/src/main/java/io/grpc/internal/ClientCallImpl.java]: Done. PTAL.

File: core/src/main/java/io/grpc/internal/ClientCallImpl.java [hunk 2]
```diff
@@ -328,6 +328,10 @@ public void request(int numMessages) {
 
   @Override
   public void cancel(@Nullable String message, @Nullable Throwable cause) {
+    if (message == null && cause == null) {
+      cause = new CancellationException("Cancelled without a message or cause");
+      log.log(Level.WARNING, "Cancelling without a message or cause is suboptimal", cause);
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ClientCallImpl.java]: Oh, oops. I see now how "suboptimal" was explained by the exception. Sorry. It was fine before, but this works too.

**Comment by ejona86** [comment]
@zhangkun83 LGTM
