### PR TITLE
OkHttp: Temporally support multiple h2-xx protocol on client side.

### LINKED ISSUE #293: OkHttp only connects to "h2" ALPN protocol
Values "h2-14", "h2-15", and "h2-16" result in [Protocol](https://github.com/square/okhttp/blob/293792c5ee66323c6070f9d88227d6579feaba47/okhttp/src/main/java/com/squareup/okhttp/Protocol.java#L87) throwing an error from [OkHttpTlsUpgrader](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java#L80).

We should support all those options, as we still are seeing them being used since the final HTTP/2 spec hasn't been published.

```
java.lang.RuntimeException: java.io.IOException: Unexpected protocol: h2-14
            at io.grpc.transport.okhttp.OkHttpClientTransport.start(OkHttpClientTransport.java:300)
            at io.grpc.ChannelImpl.obtainActiveTransport(ChannelImpl.java:188)
            at io.grpc.ChannelImpl.access$600(ChannelImpl.java:55)
            at io.grpc.ChannelImpl$CallImpl.start(ChannelImpl.java:248)
            at io.grpc.ForwardingCall.start(ForwardingCall.java:45)
...
     Caused by: java.io.IOException: Unexpected protocol: h2-14
            at com.squareup.okhttp.Protocol.get(Protocol.java:94)
            at com.squareup.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:80)
```

### PR DESCRIPTION
**Pull request by madongfly**
Since the user provided SSLSocketFactory (especially in Android) may already do the handshake when creates the SSLSocket, and it may choose a different protocol name other than the one OkHttp is using.

Resolves #293

### CODE REVIEW

File: okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java [hunk 1]
```diff
@@ -69,21 +74,27 @@ public static SSLSocket upgrade(SSLSocketFactory sslSocketFactory,
...
 
     Platform platform = Platform.get();
-    try {
-      // Force handshake.
-      sslSocket.startHandshake();
-
-      String negotiatedProtocol = platform.getSelectedProtocol(sslSocket);
-      if (negotiatedProtocol == null) {
-        throw new RuntimeException("protocol negotiation failed");
+    // It's possible that the user provided SSLSocketFactory has already done the handshake
```
Comment (ejona86) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: I question if that is actually what happened. I think instead the application was configuring NPN on the socket factory and it won out over our ALPN settings.

If you are concerned about the initial handshake already being completed, then sslSocket.getSession() looks to be better than sslSocket.startHandshake().

Comment (madongfly) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: That was my first thought until I saw https://android.googlesource.com/platform/frameworks/base/+/534a67c/core/java/android/net/SSLCertificateSocketFactory.java

Even it's the case that the socket factory settings won out over our settings, this code should be able to handle it correctly too.

Comment (ejona86) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: Okay, that's good to know. That makes me all the more certain that sslSocket.getSession() is what we want. sslSocket.startHandshake() will start a new handshake if the first has already completed, which may have been done without ALPN/NPN support. Not that that case matters much, since we will end up failing anyway, but the code is more straightforward if we always call sslSocket.getSession() to wait until the handshake is done.

Comment (madongfly) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: The only reason I don't want getSession() is that it swallows the exception if there is an error during the handshake, although it returns an invalid session object with an invalid cipher suite of "SSL_NULL_WITH_NULL_NULL" so that we can detect the failure, but we lost the error message and stack trace which should be useful to tell users what's going on.

Comment (ejona86) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: Oh, I see. That really messes up things. Yeah, I guess we can only use heuristics then for cases like that.

File: okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java [hunk 2]
```diff
@@ -69,21 +74,27 @@ public static SSLSocket upgrade(SSLSocketFactory sslSocketFactory,
...
+      try {
+        // Force handshake.
+        sslSocket.startHandshake();
+
+        negotiatedProtocol = platform.getSelectedProtocol(sslSocket);
+        if (negotiatedProtocol == null) {
+          throw new RuntimeException("protocol negotiation failed");
+        }
+      } finally {
+        platform.afterHandshake(sslSocket);
```
Comment (ejona86) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: Are we missing a call to platform.configureTlsExtensions()?

**Comment by ejona86** [comment]
@madongfly, LGTM

File: okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java (hunk 2 above)
Comment (madongfly) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: It is done inside ConnectionSpec.apply().

Comment (ejona86) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: Where does it do that? I don't see any reference to Plaform in ConnectionSpec.java. And the SslSocket isn't passed anywhere other than supportedSpec().

Comment (madongfly) [inline okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java]: Hmm, seems it got changed, see https://github.com/square/okhttp/blob/parent-2.2.0/okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java#L143
