### PR TITLE
Remove Flakes caused by assertEquals

### LINKED ISSUE #1617: DeadlineTest.shortDeadlineEventuallyExpires is flaky
As seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/948/console
```
io.grpc.DeadlineTest > shortDeadlineEventuallyExpires FAILED
    java.lang.AssertionError: expected:<0.0> but was:<-6.401849E8>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:519)
        at org.junit.Assert.assertEquals(Assert.java:609)
        at io.grpc.DeadlineTest.shortDeadlineEventuallyExpires(DeadlineTest.java:73)
```

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Fixes #1617 and #1616

### CODE REVIEW

File: core/src/test/java/io/grpc/DeadlineTest.java [hunk 1]
```diff
@@ -69,15 +71,19 @@ public void shortDeadlineEventuallyExpires() throws Exception {
     assertTrue(deadline.timeRemaining(TimeUnit.NANOSECONDS) > 0);
     assertFalse(deadline.isExpired());
     Thread.sleep(101);
+
     assertTrue(deadline.isExpired());
-    assertEquals(0, deadline.timeRemaining(TimeUnit.NANOSECONDS), delta);
+    long actualDelta = deadline.timeRemaining(NANOSECONDS);
+    assertTrue(maxDelta + " < " + actualDelta, maxDelta >= actualDelta);
```
Comment (zhangkun83) [inline core/src/test/java/io/grpc/DeadlineTest.java]: This is exactly what the original [assertEquals(double, double, double)](http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(double, double, double)) is doing. I don't believe it would improvement the flakiness.

The reason of #1617 is that the actual delta is ~6E8 ns == ~600 ms > 20 ms (the delta). We can fix it by tuning up `maxDelta` to a larger value.

Comment (carl-mastrangelo) [inline core/src/test/java/io/grpc/DeadlineTest.java]: Take a second look.  It isn't calling that method.  It is calling the float version, which is not big enough to store the full 64 bit long values.  The flakiness is due to integer truncation, not time.

Comment (zhangkun83) [inline core/src/test/java/io/grpc/DeadlineTest.java]: Fair enough. Since the same pattern is repeated for quite a few times, wouldn't it be better to define a helper function for it? How about an `assertEquals(long, long, long)` in a utility class?

Comment (carl-mastrangelo) [inline core/src/test/java/io/grpc/DeadlineTest.java]: Done.

**Comment by carl-mastrangelo** [comment]
@zhangkun83 PTAL

File: core/src/test/java/io/grpc/DeadlineTest.java [hunk 2]
```diff
@@ -144,23 +149,43 @@ public void run() {
...
-    d = Deadline.after(10, TimeUnit.SECONDS);
-    assertEquals(d.timeRemaining(TimeUnit.NANOSECONDS), extractRemainingTime(d.toString()), delta);
+    assertDeadlineEquals(d, extractRemainingTime(d.toString()), maxDelta, NANOSECONDS);
+  }
+
+  public static void assertDeadlineEquals(
+      Deadline expected, Deadline actual, long delta, TimeUnit timeUnit) {
+    // This is probably overkill, but easier than thinking about overflow.
+    BigInteger actualTimeRemaining = BigInteger.valueOf(actual.timeRemaining(NANOSECONDS));
+    BigInteger expectedTimeRemaining = BigInteger.valueOf(expected.timeRemaining(NANOSECONDS));
```
Comment (zhangkun83) [inline core/src/test/java/io/grpc/DeadlineTest.java]: You are checking `timeRemaining()` against itself. Such test is flawed. With a hypothetical bug in `timeRemaining()` that all return values were off by the same value, `assertDeadlineEquals()` wouldn't be able to catch it.

The result of `timeRemaining()` should be checked against canonical values. I would recommend reverting to the original test pattern and use something like `assertEquals(long, long, long)`.

**Comment by zhangkun83** [comment]
LGTM
