### PR TITLE
Tightening up error message for GO_AWAY.

### LINKED ISSUE #163: GO_AWAY can result in cryptic error messages
In NettyClientHandler, we don't always store the original cause of the GO_AWAY and instead rely on a connection error.  This results in cryptic errors like this:

Caused by: io.grpc.Status$OperationException: UNAVAILABLE: null
        at io.grpc.Status.asException(Status.java:396)
        at io.grpc.transport.netty.NettyClientHandler.failPendingStreams(NettyClientHandler.java:398)
        at io.grpc.transport.netty.NettyClientHandler.createPendingStreams(NettyClientHandler.java:333)
        at io.grpc.transport.netty.NettyClientHandler.createStream(NettyClientHandler.java:240)
        at io.grpc.transport.netty.NettyClientHandler.write(NettyClientHandler.java:133)

### PR DESCRIPTION
**Pull request by nmittler**
The attempt here is to identify all causes of GO_AWAY and to ensure
there is a reasonable description to help understand the cause.

Fixes #163

### CODE REVIEW

**Comment by nmittler** [comment]
@louiscryan can you take a look?

File: netty/src/main/java/io/grpc/transport/netty/Utils.java [hunk 1]
```diff
@@ -86,6 +88,68 @@ static ByteBuf toByteBuf(ByteBufAllocator alloc, ByteBuffer source) {
...
+   * @return a {@link Status} representing the given error.
+   */
+  public static Status http2ErrorCodeToStatus(long errorCode) {
+    Http2Error error = toHttp2Error(errorCode);
+    if (error == null) {
+      return Status.UNKNOWN;
+    }
+
+    String msg = "HTTP/2 Error Code: " + error.name();
+    switch (error) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/transport/netty/Utils.java]: This doesn't seem to follow https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md

Comment (nmittler) [inline netty/src/main/java/io/grpc/transport/netty/Utils.java]: Fixed.

**Comment by nmittler** [comment]
@ejona86 PTAL

File: core/src/main/java/io/grpc/transport/HttpUtil.java [hunk 2]
```diff
@@ -121,5 +121,107 @@ public static Status httpStatusToGrpcStatus(int httpStatusCode) {
...
+    private static final Http2Error[] codeMap;
+    static {
+      Http2Error[] errors = Http2Error.values();
+      codeMap = new Http2Error[(int) errors[errors.length - 1].code()];
+      for (Http2Error error : errors) {
+        codeMap[(int) error.code()] = error;
+      }
+    }
+
+    private final long code;
```
Comment (louiscryan) [inline core/src/main/java/io/grpc/transport/HttpUtil.java]: int seems more than sufficient

File: core/src/main/java/io/grpc/transport/HttpUtil.java [hunk 3]
```diff
@@ -121,5 +121,107 @@ public static Status httpStatusToGrpcStatus(int httpStatusCode) {
...
+   * @return a {@link Status} representing the given error.
+   */
+  public static Status http2ErrorCodeToStatus(long code) {
+    Http2Error error = Http2Error.forCode(code);
+    if (error == null) {
+      return Status.UNKNOWN.withDescription("Unrecognized HTTP/2 error: " + code);
+    }
+
+    String msg = "HTTP/2 Error Code: " + error.name();
+    switch(error) {
```
Comment (louiscryan) [inline core/src/main/java/io/grpc/transport/HttpUtil.java]: why not just pass these in the constructor of the enum value

File: netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java [hunk 4]
```diff
@@ -192,7 +213,7 @@ private void onRstStreamRead(int streamId)
   public void channelInactive(ChannelHandlerContext ctx) throws Exception {
     try {
       // Fail any streams that are awaiting creation.
-      Status goAwayStatus = goAwayStatus().withDescription("network channel closed");
+      goAwayStatus(goAwayStatus().withDescription("Network channel closed"));
```
Comment (louiscryan) [inline netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java]: this is overwriting an earlier, and possibly more useful description. Could augment it instead

**Comment by louiscryan** [comment]
Mostly nits

File: core/src/main/java/io/grpc/transport/HttpUtil.java (hunk 2 above)
Comment (nmittler) [inline core/src/main/java/io/grpc/transport/HttpUtil.java]: done.

File: core/src/main/java/io/grpc/transport/HttpUtil.java (hunk 3 above)
Comment (nmittler) [inline core/src/main/java/io/grpc/transport/HttpUtil.java]: done.

File: netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java (hunk 4 above)
Comment (nmittler) [inline netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java]: done.

**Comment by nmittler** [comment]
@louiscryan PTAL

File: core/src/main/java/io/grpc/transport/HttpUtil.java [hunk 5]
```diff
@@ -121,5 +121,90 @@ public static Status httpStatusToGrpcStatus(int httpStatusCode) {
...
+    INTERNAL_ERROR(0x2, Status.INTERNAL),
+    FLOW_CONTROL_ERROR(0x3, Status.INTERNAL),
+    SETTINGS_TIMEOUT(0x4, Status.INTERNAL),
+    STREAM_CLOSED(0x5, Status.INTERNAL),
+    FRAME_SIZE_ERROR(0x6, Status.INTERNAL),
+    REFUSED_STREAM(0x7, Status.UNAVAILABLE),
+    CANCEL(0x8, Status.CANCELLED),
+    COMPRESSION_ERROR(0x9, Status.INTERNAL),
+    CONNECT_ERROR(0xA, Status.INTERNAL),
+    ENHANCE_YOUR_CALM(0xB, Status.RESOURCE_EXHAUSTED, "Bandwidth exhausted"),
```
Comment (louiscryan) [inline core/src/main/java/io/grpc/transport/HttpUtil.java]: could do Status.RESOURCE_EXHAUSTED.withDescription("Bandwidth exhausted") here and eliminate the constructor overload

**Comment by louiscryan** [comment]
LGTM, one minor suggestion

File: core/src/main/java/io/grpc/transport/HttpUtil.java (hunk 5 above)
Comment (nmittler) [inline core/src/main/java/io/grpc/transport/HttpUtil.java]: Not sure if this will work.  The default constructor is already doing withDescription with the HTTP/2 error code so that it's clear that the error is a result of an inbound HTTP/2 error.  We could use augmentDescription, in which case the error will be something like "HTTP/2 error code: X Bandwidth exhausted".  Is that what you're thinking?

Comment (louiscryan) [inline core/src/main/java/io/grpc/transport/HttpUtil.java]: Yup, thats what I had in mind.

File: netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java [hunk 6]
```diff
@@ -185,6 +189,23 @@ private void onRstStreamRead(int streamId)
     stream.transportReportStatus(Status.UNKNOWN, false, new Metadata.Trailers());
   }
 
+  private void onGoAwayRead(long errorCode, ByteBuf debugData) {
+    Status status = HttpUtil.Http2Error.statusForCode((int) errorCode);
+    if (debugData.isReadable()) {
+      // If a debug message was provided, use it.
+      String msg = debugData.toString(UTF_8);
+      status = status.withDescription(msg);
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java]: It seems this should have been augmentDescription as well, so that we know what the error code was.

Comment (nmittler) [inline netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java]: Created PR #188 to address this.
