### PR TITLE
core: Don't leak CallCredentials into OOB channels

### LINKED ISSUE #7643: ALTS: GRPCLB LoadBalancer had an error
When running [GCS benchmark](https://github.com/GoogleCloudPlatform/grpc-gcp-java/tree/master/end2end-test-examples/gcs) over DirectPath with gRPC 1.34.0-SNAPSHOT, it failed with the error below. It has been working with gRPC 1.33.1. 

### What version of gRPC-Java are you using?

gRPC 1.34.0-SNAPSHOT

### What is your environment?

Linux Debian/10

### What did you expect to see?

Connecting to the backend using ALTS.

### What did you see instead?

GRPCLB Error

```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Stream to GRPCLB LoadBalancer had an error
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:648)
        at io.grpc.gcs.GrpcClient.makeMediaRequest(GrpcClient.java:179)
        at io.grpc.gcs.GrpcClient.startCalls(GrpcClient.java:106)
        at io.grpc.gcs.TestMain.main(TestMain.java:52)
```

### Steps to reproduce the bug

```
java -jar $HOME/grpc-gcp-java/end2end-test-examples/gcs/libs_1.34.0/gcs-1.0-SNAPSHOT.jar --client=grpc --bkt=$GCS_BUCKET --obj=$GCS_OBJECT --method=read --dp=true --calls=1
```

### PR DESCRIPTION
**Pull request by ejona86**
The addition of CompositeChannelCredentials allowed CallCredentials to
be passed to the ManagedChannel itself. But the implementation was buggy
and used the call creds for out-of-band channels as well, which is
inappropriate since they have a different authority.

This also fixes a bug where resolving OOB channels would have CallCreds
duplicated; that wasn't noticed or important because we don't use
CallCreds in OOB channels.

Fixes #7643

-----

Note that the originalTransportFactory usage vs oobTransportFactory usage is
subtle. If you use the wrong one then CallCreds are duplicated. That's not great,
but also not the worst thing that could happen.

### CODE REVIEW

**Comment by ejona86** [comment]
@veblush, could you do one more test with this and post the log? I search for `:path: /grpc.lb.v1.LoadBalancer/BalanceLoad` in the log and then check to see if it has an authorization header.

**Comment by veblush** [comment]
@ejona86 Sure. Would running my client with this PR would be enough?

**Comment by ejona86** [comment]
@veblush, yeah. Patch this PR in and see if it resolves things. Any commit after the ChannelCredentials stuff was added would be fine. That means the commit you originally produced the issue should be fine to patch this into.

**Comment by veblush** [comment]
I got [1.34.1.log](https://github.com/grpc/grpc-java/files/5669389/1.34.1.log) by running gRPC Java 1.34.x with this PR cherry-picked.

**Comment by ejona86** [comment]
@veblush, excellent! That log shows this PR did successfully avoid including the call creds. So this PR should fix the original issue you experienced (even if we can't reproduce it now).

File: core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java [hunk 1]
```diff
@@ -1741,6 +1744,87 @@ public void oobchannels() {
         .returnObject(balancerRpcExecutor.getScheduledExecutorService());
   }
 
+  @Test
+  public void oobchannelsHaveNoChannelCallCredentials() {
```
Comment (sanjaypujare) [inline core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java:1748]: s/oobchannels/oobChannels/

File: core/src/main/java/io/grpc/internal/ManagedChannelImpl.java [hunk 2]
```diff
@@ -1577,7 +1582,7 @@ public ManagedChannel build() {
           // TODO(creamsoup) prevent main channel to shutdown if oob channel is not terminated
           return new ManagedChannelImpl(
                   managedChannelImplBuilder,
-                  transportFactory,
+                  originalTransportFactory,
```
Comment (sanjaypujare) [inline core/src/main/java/io/grpc/internal/ManagedChannelImpl.java:1585]: Shouldn't this be `oobTransportFactory`? Otherwise there is no `CallCredentialsApplyingTransport` and no callCreds can be sent over oobChannel?

Comment (sanjaypujare) [reply core/src/main/java/io/grpc/internal/ManagedChannelImpl.java:1585]: I checked the new test and if the test is passing then this change seems to be correct.

**Review by sanjaypujare — APPROVED** [review]
LGTM. 2 comments added

File: core/src/main/java/io/grpc/internal/ManagedChannelImpl.java (hunk 2 above)
Comment (ejona86) [reply core/src/main/java/io/grpc/internal/ManagedChannelImpl.java:1585]: This is the part that I mentioned was subtle in the description. It needs to be the original factory because this is getting passed to a _new_ `ManagedChannelImpl`. _That new instance_ will wrap the factory. If we use oobTransportFactory here then the CallCredentials are applied twice. This was a pre-existing bug that I only noticed because of the test I added.

File: core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java (hunk 1 above)
Comment (ejona86) [reply core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java]: Done.

File: core/src/main/java/io/grpc/internal/ManagedChannelImpl.java (hunk 2 above)
Comment (sanjaypujare) [reply core/src/main/java/io/grpc/internal/ManagedChannelImpl.java:1585]: Thanks for the explanation. Great catch.

**Review by dapengzhang0 — APPROVED** [review]
LGTM
