### PR TITLE
netty: Support pseudo headers in all GrpcHttp2RequestHeaders methods

### LINKED ISSUE #8981: Netty 4.1.75.Final HTTP/2 connection closures
### What version of gRPC-Java are you using?

1.46.0-SNAPSHOT

### What is your environment?
macOS

### What did you expect to see?
After bumping Netty from 4.1.72.Final to 4.1.75.Final I'd expect tests to pass.

### What did you see instead?

Broken tests:

```
> Task :grpc-alts:test

io.grpc.alts.HandshakerServiceChannelTest > resource_lifecycleTwice FAILED
    io.grpc.StatusRuntimeException: INTERNAL: Connection closed after GOAWAY. HTTP/2 error code: COMPRESSION_ERROR, debug data: Use direct accessor methods for pseudo headers.
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:164)
        at app//io.grpc.testing.protobuf.SimpleServiceGrpc$SimpleServiceBlockingStub.unaryRpc(SimpleServiceGrpc.java:355)
        at app//io.grpc.alts.HandshakerServiceChannelTest.doRpc(HandshakerServiceChannelTest.java:98)
        at app//io.grpc.alts.HandshakerServiceChannelTest.resource_lifecycleTwice(HandshakerServiceChannelTest.java:85)

io.grpc.alts.HandshakerServiceChannelTest > resource_works FAILED
    io.grpc.StatusRuntimeException: INTERNAL: Connection closed after GOAWAY. HTTP/2 error code: COMPRESSION_ERROR, debug data: Use direct accessor methods for pseudo headers.
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:164)
        at app//io.grpc.testing.protobuf.SimpleServiceGrpc$SimpleServiceBlockingStub.unaryRpc(SimpleServiceGrpc.java:355)
        at app//io.grpc.alts.HandshakerServiceChannelTest.doRpc(HandshakerServiceChannelTest.java:98)
        at app//io.grpc.alts.HandshakerServiceChannelTest.resource_works(HandshakerServiceChannelTest.java:75)
```

### Steps to reproduce the bug

Bump `nettyVersion` to 4.1.75.Final and run `./gradlew clean build`.

### Possible cause

`GrpcHttp2RequestHeaders` most probably contains incorrect implementation and unnecessary guards against accessing pseudo headers, which are not specified by Netty and are in fact used by the `contains` method.

### PR DESCRIPTION
**Pull request by ejona86**
The previous code assumed that only gRPC would be using these methods.
But twice now Netty has made a change (generally relating to security)
that used a method for pseudo headers that previously wasn't supported.
Let's stop the whack-a-mole and just implement them all.

This restores compatibility with Netty 4.1.75.Final. Fixes #8981

CC @njhill
Alternative to #9001

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java [hunk 1]
```diff
@@ -353,44 +358,42 @@ public Http2Headers add(CharSequence csName, CharSequence csValue) {
...
       if (equals(TE_HEADER, name)) {
         return te;
       }
       return get(name);
     }
 
-    private void addPseudoHeader(CharSequence csName, CharSequence csValue) {
-      AsciiString name = requireAsciiString(csName);
-      AsciiString value = requireAsciiString(csValue);
+    private AsciiString getPseudoHeader(AsciiString name) {
```
Comment (sergiitk) [inline netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java:370]: Should we annotate this with `@Nullable`?

File: netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java [hunk 2]
```diff
@@ -340,7 +340,12 @@ public Http2Headers add(CharSequence csName, CharSequence csValue) {
       AsciiString name = validateName(requireAsciiString(csName));
       AsciiString value = requireAsciiString(csValue);
       if (isPseudoHeader(name)) {
-        addPseudoHeader(name, value);
+        AsciiString previous = getPseudoHeader(name);
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java:343]: It'd be possible to implement this without a get-then-set if `setPseudoHeader()` returned the old value. We'd have to re-set the old value if there was one already present, but that's not the worst. Returning-old-value`setPseudoHeader()` would seem to most benefit `remove()`, but it isn't safe for remove because it would throw for `remove(":status')`. Having the returning-old-value `setPseudoHeader()` made it really easy to make mistakes, so I went with the KISS approach. These code paths don't matter for performance.

File: netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java [hunk 3]
```diff
@@ -133,6 +133,101 @@ public void decode_emptyHeaders() throws Http2Exception {
     assertThat(decodedHeaders.toString()).contains("[]");
   }
 
+  // contains is used by Netty 4.1.75+. https://github.com/grpc/grpc-java/issues/8981
```
Comment (sergiitk) [inline netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java:136]: Let's make it clearer what is "contains"
```suggestion
  // `contains()` is used by Netty 4.1.75+. https://github.com/grpc/grpc-java/issues/8981
```

File: netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java [hunk 4]
```diff
@@ -133,6 +133,101 @@ public void decode_emptyHeaders() throws Http2Exception {
...
+    assertThat(http2Headers.remove(AsciiString.of(":authority"))).isFalse();
+    assertThat(http2Headers.remove(AsciiString.of(":method"))).isFalse();
+    assertThat(http2Headers.remove(AsciiString.of(":scheme"))).isFalse();
+    assertThat(http2Headers.remove(AsciiString.of(":status"))).isFalse();
+  }
+
+  @Test
+  public void GrpcHttp2RequestHeaders_pseudoHeaders_present() {
+    Http2Headers http2Headers = new GrpcHttp2RequestHeaders(2);
+    http2Headers.add(AsciiString.of(":path"), AsciiString.of("mypath"));
```
Comment (sergiitk) [inline netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java:169]: Should we also test the case where `.add()` throws `Duplicate %s header`?

**Review by sergiitk — APPROVED** [review]

File: netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java (hunk 1 above)
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java:370]: This class doesn't use `@Nullable`. In my mind it'd be misleading to add it to this one method. The get() method just above this one and probably many more would need to be checked.

File: netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java (hunk 3 above)
Comment (ejona86) [reply netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java]: Oh, definitely. I just added the `()`, not the back-ticks.

I'm not eager to bring markdown syntax into Java, as we already have to deal with normal text vs Javadoc/HTML. I could use double quotes, or the old-school backtick+single-quote, or even markdown backticks, but it seems to be clear without any of them.

File: netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java (hunk 4 above)
Comment (ejona86) [reply netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java:170]: Yes, but that brings up pains on which approach to use so I just didn't.

There's a recent go/lsc-assertthrows inside google converting old-style into assertThrows() but I didn't want this to be the first usage of the "new" method. And then there's the trouble that last I checked inside Google we were using a hodge-podge junit 4.12 with lots of backports so we are using junit 4.12 in gRPC, but assertThrows() was added in 4.13.

But yes, we should have it. I've added some with the try-catch+fail approach.

File: netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java [hunk 5]
```diff
@@ -418,8 +421,12 @@ public CharSequence scheme() {
...
-        throw new IllegalArgumentException("Use direct accessor methods for pseudo headers.");
+        AsciiString value = getPseudoHeader(name);
+        if (value == null) {
+          return Collections.emptyList();
+        } else {
+          return Collections.singletonList(value);
+        }
       }
       if (equals(TE_HEADER, name)) {
         return Collections.singletonList((CharSequence) te);
```
Comment (njhill) [inline netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java:432]: I think this should also return empty list in not present case?

File: netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java [hunk 6]
```diff
@@ -418,8 +421,12 @@ public CharSequence scheme() {
...
       AsciiString name = requireAsciiString(csName);
       if (isPseudoHeader(name)) {
-        // This code should never be reached.
-        throw new IllegalArgumentException("Use direct accessor methods for pseudo headers.");
+        AsciiString value = getPseudoHeader(name);
+        if (value == null) {
+          return Collections.emptyList();
+        } else {
+          return Collections.singletonList(value);
+        }
```
Comment (njhill) [inline netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java:429]: Not a fan of the conditional operator? :)

File: netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java (hunk 5 above)
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java:432]: If I had noticed when I found the bug with the pseudo headers, I might have fixed it. But I didn't, and it seems fine to be separate.

File: netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java (hunk 6 above)
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java:429]: Honestly, I didn't even consider it. I do use it, albeit less as time goes on. I'd say I don't use it any more, but I think I sometimes notice it is missing in Go, so I do sometimes use it. Here I have no desire, I think because it isn't trivial code. Like, neither case is a literal. But even then... dunno.

This particular is also interesting, because I didn't write:
```java
if (value == null) {
  return Collections.emptyList();
}
return Collections.singletonList(value);
```

But that's because I don't consider `value == null` an error. These two cases are symmetric and equal in complexity, so I have them mirror each other. If `value != null` case was 3 lines, I'd have changed the style. But again, I didn't even consider that as an option. I had a mental model and I wrote it down.
