### PR TITLE
Use stream.cancel() instead of cancel() in ClientCallImpl

### LINKED ISSUE #1531: Use stream.cancel() instead of cancel() in ClientCallImpl
Some error handling in ClientCallImpl is calling ClientCall.cancel() instead of stream.cancel(). For example, in [sendMessage()](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L317). This causes incorrect throwing of `IllegalStateException` to later callers.

### PR DESCRIPTION
**Pull request by ejona86**
Using cancel() sets cancelCalled=true which causes methods like
sendMessage() to throw IllegalStateException. This results in spurious
exceptions that are impossible to avoid. The API was designed to only
throw IllegalStateException when the caller called methods in the wrong
order, which is not the case here.

Fixes #1531

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/ClientCallImpl.java [hunk 1]
```diff
@@ -316,7 +316,7 @@ public void sendMessage(ReqT message) {
       InputStream messageIs = method.streamRequest(message);
       stream.writeMessage(messageIs);
     } catch (Throwable e) {
-      cancel(Status.CANCELLED.withCause(e).withDescription("Failed to stream message"));
+      stream.cancel(Status.CANCELLED.withCause(e).withDescription("Failed to stream message"));
```
Comment (carl-mastrangelo) [inline core/src/main/java/io/grpc/internal/ClientCallImpl.java]: Github won't let me comment on line 282, so here: remove the TODO?

**Comment by carl-mastrangelo** [comment]
@ejona86 LGTM.

Worth checking Server code for something similar?

File: core/src/main/java/io/grpc/internal/ClientCallImpl.java (hunk 1 above)
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ClientCallImpl.java]: Removed TODO and cancel(Status). I sort of expect we'll add it back eventually, but it is easy to do that later if/when we need it.

**Comment by ejona86** [comment]
@carl-mastrangelo, PTAL

**Comment by ejona86** [comment]
@carl-mastrangelo, it looks like server-side is using an internalClose() helper that calls stream.close(). So I think server-side is generally good.

**Comment by carl-mastrangelo** [comment]
Still LGTM
