### PR TITLE
Fix errror message when DNS name is invalid.

### LINKED ISSUE #3701: NullPointerException when create channel with hostname contains '_' underscore
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
grpc-core-1.6.1

### What JVM are you using (`java -version`)?
openjdk version 1.8.0_141

### What did you do?
Create a channel with hostname contains underscore ('_')
`ManagedChannelBuilder.forTarget("host_1").usePlaintext(true).build();`
It is due to the java.net.URI return null on getHost() when hostname contains '_'.
We understand that '_' is not align with standard, but many systems support '_' nowadays, and is hard to avoid.

### What did you see instead?
```
java.lang.NullPointerException: host
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at io.grpc.internal.DnsNameResolver.<init>(DnsNameResolver.java:97)
	at io.grpc.internal.DnsNameResolverProvider.newNameResolver(DnsNameResolverProvider.java:50)
	at io.grpc.internal.DnsNameResolverProvider.newNameResolver(DnsNameResolverProvider.java:39)
	at io.grpc.NameResolverProvider$NameResolverFactory.newNameResolver(NameResolverProvider.java:162)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:447)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:383)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:320)
```

### PR DESCRIPTION
**Pull request by creamsoup**
It used to throw NPE, since URI.create creates URI with null hostname. Now it
thorws IllegalArgumentException for invalid DNS name, NPE for null name.

Resolves #3701

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @creamsoup isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

File: core/src/main/java/io/grpc/internal/DnsNameResolver.java [hunk 1]
```diff
@@ -132,10 +132,11 @@
     this.executorResource = executorResource;
     // Must prepend a "//" to the name when constructing a URI, otherwise it will be treated as an
     // opaque URI, thus the authority and host of the resulted URI would be null.
-    URI nameUri = URI.create("//" + name);
+    URI nameUri = URI.create("//" + checkNotNull(name));
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/DnsNameResolver.java]: Pass a second argument to checkNotNull, so it is easier to figure out which value was NPE. So I'd suggest passing `"name"` here.

**Comment by ejona86** [comment]
@creamsoup, you just need to login to the linux foundation with your google account. That should be enough to fix the CLA.

File: core/src/main/java/io/grpc/internal/DnsNameResolver.java (hunk 1 above)
Comment (creamsoup) [reply core/src/main/java/io/grpc/internal/DnsNameResolver.java]: thanks, done.
