### PR TITLE
api: Clarify expectations regarding ServerCall#close

### LINKED ISSUE #7571: ServerCall#close(Status, Metadata) never called for client-cancelled calls
### What version of gRPC-Java are you using?

- 1.33.0
- also affects previous versions

### What is your environment?

- Windows 10 x64
- Java 11 x64

### What do you wish to achieve

I wish to report the request count/duration including the result status (including `CANCELLED` ones).
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerCall.java#L63

See also:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/438

### What did you expect to see?

No error in the attached test / `ServerCall#close(Status, Metadata)` should have been called with status `Status.Code.CANCELLED`.

### What did you see instead?

````txt
org.opentest4j.AssertionFailedError: Call closed ==> expected: <true> but was: <false>
````

Which might lead to a memory leak if a resource is attached to the `ServerCall` instead of the `ServerCall.Listener`.

### Steps to reproduce the bug

````java
class CloseTest extends SimpleGrpc.SimpleImplBase implements ServerInterceptor {

    private boolean callClosed = false;
    private boolean listenerClosed = false;

    @Test
    void testCallClosed() throws IOException, InterruptedException, ExecutionException {
        final Server server = InProcessServerBuilder.forName("self")
                .addService(ServerInterceptors.intercept(this, this))
                .build();
        server.start();

        final ManagedChannel channel = InProcessChannelBuilder.forName("self")
                .usePlaintext()
                .build();

        final SimpleStub stub = SimpleGrpc.newStub(channel);

        final CountDownLatch counter = new CountDownLatch(1);
        final AtomicReference<Throwable> error = new AtomicReference<>();

        final ClientCallStreamObserver<Message> observer = (ClientCallStreamObserver<Message>) stub
                .echo(new StreamObserver<Message>() {

                    @Override
                    public void onNext(final Message value) {
                        // Do nothing
                    }

                    @Override
                    public void onError(final Throwable t) {
                        error.set(t);
                        counter.countDown();
                    }

                    @Override
                    public void onCompleted() {
                        counter.countDown();
                    }

                });

        observer.cancel("Cancelled", null);
        counter.await();
        assertNotNull(error.get());
        assertEquals(Code.CANCELLED, ((StatusRuntimeException) error.get()).getStatus().getCode());

        assertTrue(this.listenerClosed, "Listener closed");
        assertTrue(this.callClosed, "Call closed"); // <-- BOOM

        channel.shutdown();
        server.shutdown();
    }

    @Override
    public StreamObserver<Message> echo(final StreamObserver<Message> responseObserver) {
        return responseObserver;
    }

    @Override
    public <ReqT, RespT> Listener<ReqT> interceptCall(final ServerCall<ReqT, RespT> call, final Metadata headers,
            final ServerCallHandler<ReqT, RespT> next) {
        final ServerCall<ReqT, RespT> metricsCall = new SimpleForwardingServerCall<>(call) {

            @Override
            public void close(final Status status, final Metadata trailers) {
                CloseTest.this.callClosed = true;
                super.close(status, trailers);
            }

        };
        return new SimpleForwardingServerCallListener<>(next.startCall(metricsCall, headers)) {

            public void onCancel() {
                CloseTest.this.listenerClosed = true;
                super.onCancel();
            }

        };
    }

}
````

````proto
syntax = "proto3";

option java_multiple_files = true;
option java_package = "test";
option java_outer_classname = "SimpleProto";

service Simple {

    rpc echo(stream Message) returns (stream Message) {}

}

message Message {
    string text = 1;
}
````

### Possible workarounds

1. Add a custom cancel method to the `ServerCall` and call it from the `Listener#onCancelled`
2. Use the GrpcContext#addCancellationListener to mark the call as cancelled (not tested)

### Expected changes

- `ServerCall#close` is also called for (client-side) cancellations.

or

- `ServerCall#close`'s documentation is amended stating that it won't be called for (client-side) cancellations and other client errors such as connection loss/timeout(?).

### PR DESCRIPTION
**Pull request by ST-DDT**
~~Fixes #7571~~

### CODE REVIEW

File: api/src/main/java/io/grpc/ServerCall.java [hunk 1]
```diff
@@ -163,6 +163,11 @@ public boolean isReady() {
    * <p>Since {@link Metadata} is not thread-safe, the caller must not access (read or write) {@code
    * trailers} after this point.
    *
+   * <p>Implementation note regarding ForwardingServerCalls: This method is called after the
```
Comment (ejona86) [inline api/src/main/java/io/grpc/ServerCall.java:166]: I'd much rather not call out ForwardingServerCalls. And saying something like "this method won't be called" isn't right either as it is up to the application whether it is called or not.

I think we should have some text to emphasize that the close call is _not_ the point where the RPC is complete. Instead, that is onComplete/onCancel. We can probably add that to the paragraph above. We can also say that close is not necessary to be called if the RPC is cancelled as the call is already dead.

**Comment by ejona86** [comment]
Oh, you closed. Was that an accident? This doesn't seem like something bad to improve.

**Comment by ST-DDT** [comment]
I closed this PR because the original purpose of the PR which is the second sentence is not true (see linked issue).

I could reopen it with a changed description though.
How about

````java
   * <p>Implementation note: This method is called after the
   * server completed the processing of the request, but before the response status is sent to the
   * client, so the client is still able to cancel the request.
````

File: api/src/main/java/io/grpc/ServerCall.java [hunk 2]
```diff
@@ -163,6 +163,12 @@ public boolean isReady() {
    * <p>Since {@link Metadata} is not thread-safe, the caller must not access (read or write) {@code
    * trailers} after this point.
    *
+   * <p>Implementation note: This method is called after the server completed the processing of the
+   * request (service implementation), but before the response status is sent to the client, so the
```
Comment (ejona86) [inline api/src/main/java/io/grpc/ServerCall.java:167]: I like that, but I'd really hope to avoid "implementation note." This is more how the API is designed versus how things just so happen to be implemented.

> This method implies the caller completed processing the RPC, but it does not imply the RPC is complete. The call implementation will need additional time to complete the RPC and during this time the client is still able to cancel the request or a network error might cause the RPC to fail. If you wish to know...

It could maybe use some more wordsmithing, but is that better?

Did you want to include anything along the lines of "this method is not necessary when Listener.onCancel() is called?"

**Review by ejona86 — APPROVED** [review]

**Review by dapengzhang0 — APPROVED** [review]
LGTM

**Comment by ejona86** [comment]
@ST-DDT, thank you! I appreciate these javadoc improvements.
