### PR TITLE
Fix NPE in ProtoInputStream.drainTo

### LINKED ISSUE #1225: NPE in ProtoInputStream.drainTo
```
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:65)
        at io.grpc.protobuf.ProtoInputStream.drainTo(ProtoInputStream.java:74)
        at io.grpc.internal.MessageFramer.writeToOutputStream(MessageFramer.java:224)
        at io.grpc.internal.MessageFramer.writeKnownLength(MessageFramer.java:185)
        at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:135)
        at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:125)
        at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:165)
        at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:204)
        at com.google.cloud.bigtable.grpc.io.ReconnectingChannel$DelayingCall.sendMessage(ReconnectingChannel.java:122)
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:65)
```

It looks like if you call `drainTo()` twice then it will NPE. Calling `drainTo()` twice is sort of strange, so I wouldn't expect this to be critical, but we should still not NPE.

### PR DESCRIPTION
**Pull request by ejona86**
Fixes #1225

### CODE REVIEW

File: protobuf/src/main/java/io/grpc/protobuf/ProtoInputStream.java [hunk 1]
```diff
@@ -70,9 +70,11 @@ public int drainTo(OutputStream target) throws IOException {
       written = message.getSerializedSize();
       message.writeTo(target);
       message = null;
-    } else {
+    } else if (partial != null) {
       written = (int) ByteStreams.copy(partial, target);
       partial = null;
+    } else {
+      written = 0;
```
Comment (nmittler) [inline protobuf/src/main/java/io/grpc/protobuf/ProtoInputStream.java]: Just initialize written to zero on line 69?

**Comment by nmittler** [comment]
LGTM

File: protobuf/src/main/java/io/grpc/protobuf/ProtoInputStream.java (hunk 1 above)
Comment (ejona86) [inline protobuf/src/main/java/io/grpc/protobuf/ProtoInputStream.java]: No, I'd rather the compiler help verify that each condition block sets the value.
