### PR TITLE
stub: Wait for onClose when blocking stub is interrupted

### LINKED ISSUE #5576: ClientCall errors does not finally invoke ClientCall.Listener.onClose()
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

v1.19.0

### What did you expect to see?

`ClientCall.Listener.onClose()` should be invoked when there is a ClientCall error for unary calls.

When there is an exception thrown by `call.sendMessage()` or `call.halfClose()` within `asyncUnaryRequestCall()` (See https://sourcegraph.com/github.com/grpc/grpc-java/-/blob/stub/src/main/java/io/grpc/stub/ClientCalls.java#L276:37), it results in `cancelThrow()` calling `ClientCall.cancel()` and scheduling a stream closed task (i.e. `ClientCall.Listener.onClose`) on the executor.  However, the exception propagates up to `futureUnaryCall ` and `blockingUnaryCall` which catches it again, calls `cancelThrow()` again but never drains the executor within the try-catch block (See https://sourcegraph.com/github.com/grpc/grpc-java/-/blob/stub/src/main/java/io/grpc/stub/ClientCalls.java#L123-146).  Thus `ClientCall.cancel()` is called but not `ClientCall.Listener.onClose()` on client call errors.

Is `ClientCall.Listener.onClose()` expected to be called whenever the client call terminates?  Is dropping the `ClientCall.Listener.onClose()` call a bug or expected behaviour?

### PR DESCRIPTION
**Pull request by ejona86**
Interceptors need to see the onClose to clean up properly.

This also changes an isInterrupted() to interrupted(), since previously
the interrupted flag was still set when InterruptedException was thrown.
This caused an infinite loop with the new code. Previously, all callers
immediately re-set the interrupted flag, so there was no issue.

Fixes #5576

CC @ravirajj
CC @njhill, since I touched the ThreadlessExecutor because of isInterrupted()

### CODE REVIEW

File: stub/src/main/java/io/grpc/stub/ClientCalls.java [hunk 1]
```diff
@@ -123,25 +123,30 @@ private ClientCalls() {}
...
       while (!responseFuture.isDone()) {
         try {
           executor.waitAndDrain();
         } catch (InterruptedException e) {
-          Thread.currentThread().interrupt();
-          throw Status.CANCELLED
-              .withDescription("Call was interrupted")
-              .withCause(e)
-              .asRuntimeException();
+          interrupt = true;
```
Comment (carl-mastrangelo) [inline stub/src/main/java/io/grpc/stub/ClientCalls.java]: optional:

```
...
int interrupt = 0;
if (interrupts++ == 1) {
  throw Status.....asRuntimeException();
}
```

This allows a single interrupt to clean up, but a second interrupt while waiting for onClose to bypass.

File: stub/src/main/java/io/grpc/stub/ClientCalls.java [hunk 2]
```diff
@@ -546,30 +551,52 @@ protected String pendingToString() {
       return listener;
     }
 
-    private Object waitForNext() throws InterruptedException {
+    private Object waitForNext() {
       if (threadless == null) {
-        return buffer.take();
+        boolean interrupt = false;
```
Comment (carl-mastrangelo) [inline stub/src/main/java/io/grpc/stub/ClientCalls.java]: extract this up a line?

Comment (njhill) [reply stub/src/main/java/io/grpc/stub/ClientCalls.java]: and further could just have a single try/finally outside of the if/else?

File: stub/src/main/java/io/grpc/stub/ClientCalls.java [hunk 3]
```diff
@@ -123,25 +123,30 @@ private ClientCalls() {}
...
-              .withCause(e)
-              .asRuntimeException();
+          interrupt = true;
+          call.cancel("Thread interrupted", e);
+          // Now wait for onClose() to be called, so interceptors can clean up
         }
       }
       return getUnchecked(responseFuture);
     } catch (RuntimeException e) {
+      // Something very bad happened. All bets are off; it may be dangerous to wait for onClose().
```
Comment (ravirajj) [inline stub/src/main/java/io/grpc/stub/ClientCalls.java]: Wondering how this fix ensures the `onClose()` is run if an exception is thrown on line 129 by `futureUnaryCall()`?  Does this mean it doesn't attempt to run the `onClose()`?

File: stub/src/main/java/io/grpc/stub/ClientCalls.java [hunk 4]
```diff
@@ -546,30 +551,52 @@ protected String pendingToString() {
       return listener;
     }
 
-    private Object waitForNext() throws InterruptedException {
+    private Object waitForNext() {
       if (threadless == null) {
```
Comment (ravirajj) [inline stub/src/main/java/io/grpc/stub/ClientCalls.java]: You could move the `if` statement inside the try-catch so it just wraps the `while` statement.

File: stub/src/main/java/io/grpc/stub/ClientCalls.java (hunk 3 above)
Comment (ravirajj) [reply stub/src/main/java/io/grpc/stub/ClientCalls.java]: Apart from `onClose()`, the executor may also have other listener methods (i.e. `onReady()`, etc.) scheduled.  I'm guessing it's dangerous to run listener methods other than `onClose()` at this point?  Is there a way you can just run the `onClose()`?

Comment (ejona86) [reply stub/src/main/java/io/grpc/stub/ClientCalls.java]: Because we wait for `responseFuture.isDone()`, then we only call `getUnchecked()` after `onClose()` has been called. The rest of the methods should not throw; if they do, we do a minor amount of clean up, but the system is in a broken state already. We can't run onClose directly because we don't have a reference to the right Listener; only the Channel has that.

`onClose()` is guaranteed to be the last listener method called. So things like `onReady()` shouldn't be a problem.

File: stub/src/main/java/io/grpc/stub/ClientCalls.java (hunk 1 above)
Comment (ejona86) [reply stub/src/main/java/io/grpc/stub/ClientCalls.java]: Cancelling multiple times is a noop. I'm not too interested in optimizing this, especially since multiple interrupts would be unlikely.

Comment (carl-mastrangelo) [reply stub/src/main/java/io/grpc/stub/ClientCalls.java]: It's not so much an optimization, but a safety check.  If the onClose callback gets dropped it would allow this thread to escape and shutdown.

Comment (ejona86) [reply stub/src/main/java/io/grpc/stub/ClientCalls.java]: We allow an infinite number of interrupts, waiting for the onClose. I'm not sure how the onClose could be dropped here.

Comment (ejona86) [reply stub/src/main/java/io/grpc/stub/ClientCalls.java]: We discussed offline, and the thought is this could block for a long time waiting for the onClose. If interrupted twice we could choose to exit early, without waiting for the onClose.

I think this is more appropriate at the moment, although I agree it is unfortunate we have to wait for the onClose. If we had #636 done and a fallback executor, we could add a shutdown to ThreadlessExecutor where it would begin throwing RejectedExecutionException on execute(). We would then shutdown() when we exit the loop here. We can then return more quickly, knowing that if/when the onClose is scheduled it will still be run (on the fallback executor).
