### PR TITLE
Refresh name resolution if all addresses failed to connect.

### LINKED ISSUE #1463: DNS resolution expiration
It looks like the channel is somehow caching the IP resolved through DNS but never refreshing it. We are using grpc in AWS and since ELB's IPs change over time, we've run into issues and found out grpc clients are trying to connect to an old IP.

Code snippet:

``` Scala
private[this] val channel = NettyChannelBuilder.forAddress(httpHost, httpPort).negotiationType(NegotiationType.PLAINTEXT).build();
  private[this] val blockingStub = CrudGrpc.newBlockingStub(channel)
  private[this] def getStub = blockingStub.withDeadlineAfter(timeout.toNanos, TimeUnit.NANOSECONDS)

override def getEntity(id: String): Entity = {
  getStub.getEntity(id)
}
```

Is our assumption correct? Is there any issue in how are we using the client library? Would it be a bad practice (performance-wise at least) to create a new channel in each request?

Thanks in advance

### PR DESCRIPTION
**Pull request by zhangkun83**
Resolves #1463

### CODE REVIEW

File: core/src/main/java/io/grpc/DnsNameResolver.java [hunk 1]
```diff
@@ -94,7 +117,7 @@ public void run() {
         try {
           inetAddrs = InetAddress.getAllByName(host);
         } catch (Exception e) {
-          listener.onError(Status.UNAVAILABLE.withCause(e));
+          savedListener.onError(Status.UNAVAILABLE.withCause(e));
           return;
```
Comment (ejona86) [inline core/src/main/java/io/grpc/DnsNameResolver.java]: resolving = false isn't done in this code path. You may consider a try-finally (although it is unfortunate it would increase the indentation).

**Comment by ejona86** [comment]
@zhangkun83, one important comment/bug, but otherwise LGTM

File: core/src/main/java/io/grpc/DnsNameResolver.java (hunk 1 above)
Comment (zhangkun83) [inline core/src/main/java/io/grpc/DnsNameResolver.java]: Nice catch. Done.

**Comment by ejona86** [comment]
@zhangkun83 LGTM
