### PR TITLE
core: fix bug when stream listener not set before stream closed

### LINKED ISSUE #1936: directExecutor on Server is broken if handler not found
When directExecutor is used, [failure to find a handler will call close()](https://github.com/grpc/grpc-java/blob/v0.14.0/core/src/main/java/io/grpc/internal/ServerImpl.java#L316) before setListener is called. This is effectively a manifestation of the concern presented in [NettyServerHandler](https://github.com/grpc/grpc-java/blob/c6fd94c/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L199).

### PR DESCRIPTION
**Pull request by dapengzhang0**
Resolves #1936

Two bugs fixed:
- NPE in `ServerImpl#streamCreated()` when stream listener not set before
  stream closed
- It is possible that `internalCancel()` is called during
  `InProcessClientStream#start()` due to early server `onComplete()` or server `onError()`,
  in this case no need to enlist `streams`, otherwise the channel can not be shutdown by `shutdown()`.

### CODE REVIEW

File: core/src/main/java/io/grpc/internal/ServerImpl.java [hunk 1]
```diff
@@ -386,7 +386,6 @@ public ServerStreamListener streamCreated(final ServerStream stream, final Strin
       wrappedExecutor.execute(new ContextRunnable(context) {
           @Override
           public void runInContext() {
-            ServerStreamListener listener = NOOP_LISTENER;
```
Comment (ejona86) [inline core/src/main/java/io/grpc/internal/ServerImpl.java]: These changes have no effect. The tests still pass after I revert them.

File: core/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 2]
```diff
@@ -557,10 +564,19 @@ public void start(ClientStreamListener listener) {
         synchronized (InProcessTransport.this) {
           ServerStreamListener serverStreamListener = serverTransportListener.streamCreated(
```
Comment (ejona86) [inline core/src/main/java/io/grpc/inprocess/InProcessTransport.java]: I'd much rather solve the race by splitting initialization and start. Basically allow `clientStream.setListener()` to be called and then have a separate start() which calls into the application.

File: core/src/main/java/io/grpc/internal/ServerImpl.java (hunk 1 above)
Comment (dapengzhang0) [inline core/src/main/java/io/grpc/internal/ServerImpl.java]: reverted

File: core/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 2 above)
Comment (dapengzhang0) [inline core/src/main/java/io/grpc/inprocess/InProcessTransport.java]: done

File: core/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 3]
```diff
@@ -555,13 +560,11 @@ public void start(ClientStreamListener listener) {
...
 
         synchronized (InProcessTransport.this) {
-          ServerStreamListener serverStreamListener = serverTransportListener.streamCreated(
-              serverStream, method.getFullMethodName(), headers);
-          clientStream.setListener(serverStreamListener);
           streams.add(InProcessTransport.InProcessStream.this);
           if (streams.size() == 1) {
             clientTransportListener.transportInUse(true);
           }
+          serverTransportListener.streamCreated(serverStream, method.getFullMethodName(), headers);
```
Comment (ejona86) [inline core/src/main/java/io/grpc/inprocess/InProcessTransport.java]: It looks like `streamCreated()` still returns `serverStreamListener`. Is it possible to make it `void`? I could imagine that maybe tests become more difficult, but normal code shouldn't use the return value at all.

File: interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java [hunk 4]
```diff
@@ -0,0 +1,269 @@
...
+
+  @Before
+  public void setUp() throws Exception {
+    inProcessServer.start();
+  }
+
+  @After
+  public void tearDown() throws Exception {
+    inProcessChannel.shutdownNow();
+    inProcessServer.shutdownNow();
```
Comment (ejona86) [inline interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java]: Also await for termination, and assert that it terminates.

File: interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java [hunk 5]
```diff
@@ -0,0 +1,269 @@
...
+          @Override
+          public void onCompleted() {
+            finishLatch.countDown();
+          }
+        };
+
+    // make a gRPC call
+    TestServiceGrpc.newStub(inProcessChannel).streamingInputCall(responseObserver);
+
+    assertTrue(finishLatch.await(1, TimeUnit.SECONDS));
```
Comment (ejona86) [inline interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java]: This is a strange timeout when there is a overall `Timeout` of one second. Either this timeout should be smaller or the overall timeout should be higher.

File: core/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 3 above)
Comment (dapengzhang0) [inline core/src/main/java/io/grpc/inprocess/InProcessTransport.java]: I also wanted to remove returns. Done

File: interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java (hunk 4 above)
Comment (dapengzhang0) [inline interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java]: done

File: interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java (hunk 5 above)
Comment (dapengzhang0) [inline interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java]: done

File: core/src/test/java/io/grpc/internal/ServerImplTest.java [hunk 6]
```diff
@@ -407,8 +406,11 @@ public void basicExchangeSuccessful() throws Exception {
     assertNotNull(statsTraceCtx);
     when(stream.statsTraceContext()).thenReturn(statsTraceCtx);
 
-    ServerStreamListener streamListener
-        = transportListener.streamCreated(stream, "Waiter/serve", requestHeaders);
+    transportListener.streamCreated(stream, "Waiter/serve", requestHeaders);
+    ArgumentCaptor<ServerStreamListener> streamListenerCaptor =
```
Comment (ejona86) [inline core/src/test/java/io/grpc/internal/ServerImplTest.java]: Since a captor for this type is used frequently, feel free to make it a field in the class like `statusCaptor` (possibly with `@Captor`).
