### PR TITLE
netty: Preserve early server handshake failure cause in logs

### LINKED ISSUE #8495: Netty server loses exception during handshake
Recently when debugging a server-caused handshake failure, we enabled logs and saw:

```
Sep 08, 2021 4:56:49 PM io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler failWrites
FINE: Ignoring duplicate failure
io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed while performing protocol negotiation for [FilterChainMatchingProtocolNegotiators$FilterChainMatchingHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
```

But there was no earlier failure. This seems to be a problem introduced by the client/server protocol negotiator unification and WriteBufferingAndExceptionHandler. On client-side we issue a fake write (that gets thrown away by NettyClientHandler) and use it for detecting errors during handshake:

https://github.com/grpc/grpc-java/blob/fb004630019ad6cc7de737e1230d993529a01e21/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L290

We don't have anything similar on server-side, but WriteBufferingAndExceptionHandler is expecting to communicate a failure via a failed write.

https://github.com/grpc/grpc-java/blob/fb004630019ad6cc7de737e1230d993529a01e21/netty/src/main/java/io/grpc/netty/NettyServerTransport.java#L153-L154

### PR DESCRIPTION
**Pull request by becomeStar**
Early server-side negotiation failures may terminate a transport before NettyServerHandler is fully active in the pipeline. In those cases, the original handshake failure can be missing from transport termination logging because termination may rely on connectionError(), which can be null on this early path.

This change adds a server-side NOOP write in NettyServerTransport.start() (analogous to the existing client-side NOOP write path). If that write fails, its cause is passed to notifyTerminated(), preserving and logging the original transport termination reason for debugging.

To support this, NettyServerHandler now accepts NOOP_MESSAGE writes by writing an empty buffer, and tests are added to verify:
  - transport failure logging for plaintext-client to TLS-server failure
  - server NOOP write handling in NettyServerHandler

Fixes #8495

### CODE REVIEW

File: netty/src/test/java/io/grpc/netty/WriteBufferingAndExceptionHandlerTest.java [hunk 1]
```diff
@@ -381,4 +385,61 @@ public void uncaughtReadFails() throws Exception {
...
+
+    RuntimeException handshakeFailure =
+        Status.UNAVAILABLE.withDescription("handshake failed").asRuntimeException();
+
+    chan.pipeline().fireExceptionCaught(handshakeFailure);
+    chan.pipeline().fireExceptionCaught(new RuntimeException("Second"));
+
+    assertTrue(latch.await(5, TimeUnit.SECONDS));
+    assertThat(exceptionCount.get()).isEqualTo(1);
+  }
```
Comment (kannanjgithub) [inline netty/src/test/java/io/grpc/netty/WriteBufferingAndExceptionHandlerTest.java]: Also assert that the exception is for the handshake failure.

File: netty/src/test/java/io/grpc/netty/WriteBufferingAndExceptionHandlerTest.java [hunk 2]
```diff
@@ -381,4 +385,61 @@ public void uncaughtReadFails() throws Exception {
...
+          public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
+            exceptionCount.incrementAndGet();
+            latch.countDown();
+          }
+        };
+
+    WriteBufferingAndExceptionHandler handler =
+        new WriteBufferingAndExceptionHandler(new ChannelHandlerAdapter() {});
+
+    LocalAddress addr = new LocalAddress("local");
```
Comment (kannanjgithub) [inline netty/src/test/java/io/grpc/netty/WriteBufferingAndExceptionHandlerTest.java]: nit: Move this declaration closer to usage, before the .bind call below.

**Comment by kannanjgithub** [comment]
Replied my thought on issue #8495.

**Comment by becomeStar** [comment]
@kannanjgithub 

Thank you very much for your detailed analysis and for taking the time to simulate the failure. Your observation about the object handle changing is incredibly helpful and provides a clear clue as to why the original root cause may be getting lost.

It does seem that failCause can effectively be reset when a new instance of WriteBufferingAndExceptionHandler is introduced into the pipeline, which explains why a secondary exception ends up being surfaced instead of the original handshake failure.

I’ll dig further into where and why the handler instance is being replaced and look for a way to ensure the first meaningful exception is preserved across instances.

Based on your feedback, I’ll work toward a refined solution that addresses this state-loss issue directly. Once I have a clearer fix, I can either update this PR or follow up with a new one, depending on what you think makes the most sense.

Thanks again for the detailed investigation and guidance — it’s been extremely helpful.

**Comment by becomeStar** [comment]
@kannanjgithub

Thanks again for the guidance.

I added one new commit to this PR following the direction we discussed: a server-side NOOP write path in `NettyServerTransport.start()` that reports the write failure cause to `notifyTerminated(...)`, plus the corresponding server-side NOOP handling and tests.

Could you please take another look when you have a moment?

**Review by kannanjgithub — APPROVED** [review]

**Comment by ejona86** [comment]
Thank you!
