### PR TITLE
netty:Auto adjust BDP ping frequency

### LINKED ISSUE #8260: BDP PINGs are sent much more frequently than necessary
### What version of gRPC-Java are you using?
1.37.0
### What is your environment?
5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
### What did you expect to see?
Client does not flood server with PING frames when `autoTuneFlowControl` is enabled (default)
### What did you see instead?
Connection closed on server with
```text
    io.netty.handler.codec.http2.Http2Exception: Maximum number 10000 of outstanding control frames reached
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108)
	at io.netty.handler.codec.http2.Http2ControlFrameLimitEncoder.handleOutstandingControlFrames(Http2ControlFrameLimitEncoder.java:96)
	at io.netty.handler.codec.http2.Http2ControlFrameLimitEncoder.writePing(Http2ControlFrameLimitEncoder.java:69)
	at io.netty.handler.codec.http2.Http2FrameCodec.write(Http2FrameCodec.java:333)
```
### Steps to reproduce the bug
[Client](https://gist.github.com/mostroverkhov/63cb3a53804c008a72f9e6f07334298a) makes request-response calls continuously such that there is constant number of outstanding requests.

Server is 3rd party GRPC implementation based on Netty. 

It only acks received PING frames, and does not send own PING frames(ack=false). 
Acked frames content is `1234`.

Client and server are on the same host.
 
Eventually (after several seconds) connection is closed by server with  
```text
    io.netty.handler.codec.http2.Http2Exception: Maximum number 10000 of outstanding control frames reached
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108)
	at io.netty.handler.codec.http2.Http2ControlFrameLimitEncoder.handleOutstandingControlFrames(Http2ControlFrameLimitEncoder.java:96)
	at io.netty.handler.codec.http2.Http2ControlFrameLimitEncoder.writePing(Http2ControlFrameLimitEncoder.java:69)
	at io.netty.handler.codec.http2.Http2FrameCodec.write(Http2FrameCodec.java:333)
```

There is workaround `NettyChannelBuilder.flowControlWindow(int)` which happens to disable `autoTuneFlowControl`.

### PR DESCRIPTION
**Pull request by larry-safran**
Only initiate a BDP ping after every X bytes of data where X is a multiple of the window size that increases when the window isn't changing.  

Added a ticker to the Netty handlers so that bandwidth could be properly controlled from tests.

Fixes #8260

### CODE REVIEW

**Comment by larry-safran** [comment]
@ejona86 please review

**Review by ejona86 — COMMENTED** [review]
Sending what I have, in whatever state it happens to be.

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java [hunk 1]
```diff
@@ -55,19 +57,31 @@ abstract class AbstractNettyHandler extends GrpcHttp2ConnectionHandler {
...
 
     // During a graceful shutdown, wait until all streams are closed.
     gracefulShutdownTimeoutMillis(GRACEFUL_SHUTDOWN_NO_TIMEOUT);
 
     // Extract the connection window from the settings if it was set.
     this.initialConnectionWindow = initialSettings.initialWindowSize() == null ? -1 :
-            initialSettings.initialWindowSize();
+        initialSettings.initialWindowSize();
     this.autoTuneFlowControlOn = autoFlowControl;
-    if (pingLimiter == null) {
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java:67]: Overwriting an argument is a bad practice, so I introduced `activePingLimiter` whose assignment is logically identical to the if.

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java [hunk 2]
```diff
@@ -55,19 +57,31 @@ abstract class AbstractNettyHandler extends GrpcHttp2ConnectionHandler {
...
-      pingLimiter = new AllowPingLimiter();
-    }
-    this.flowControlPing = new FlowControlPinger(pingLimiter);
+    PingLimiter activePingLimiter = (pingLimiter != null) ? pingLimiter :  new AllowPingLimiter();
+    this.flowControlPing = new FlowControlPinger(activePingLimiter);
+    this.ticker = (ticker != null) ? ticker : Ticker.systemTicker();
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java]: done

File: netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java [hunk 3]
```diff
@@ -501,4 +504,113 @@ public void transportTracer_windowUpdate_local() throws Exception {
...
+
+    readXCopies(1, data1KbBuf); // ping again since had 160K data since last ping started
+    assertEquals(3, handler.flowControlPing().getPingCount());
+    fakeClock.forwardTime(1, TimeUnit.MILLISECONDS);
+    readPingAck(pingData);
+
+    fakeClock.forwardTime(1, TimeUnit.MILLISECONDS);
+    readXCopies(1, data1KbBuf); // no ping, too little data
+    assertEquals(3, handler.flowControlPing().getPingCount());
+    handler.flowControlPing().setDataSizeAndSincePing(200000);
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java:556]: Done

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java [hunk 4]
```diff
@@ -232,7 +261,10 @@ private void setDataSizeSincePing(int dataSize) {
     @VisibleForTesting
     void setDataSizeAndSincePing(int dataSize) {
       setDataSizeSincePing(dataSize);
-      lastPingTime = System.nanoTime() - TimeUnit.SECONDS.toNanos(1);
+      pingFrequencyMultiplier = 1;
+      lastPingTime = (ticker.read() > TimeUnit.SECONDS.toNanos(1))
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java]: Done

**Comment by larry-safran** [comment]
@ejona86 ping

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java [hunk 5]
```diff
@@ -157,7 +174,12 @@ public void onDataRead(int dataLength, int paddingLength) {
       if (!autoTuneFlowControlOn) {
         return;
       }
-      if (!isPinging() && pingLimiter.isPingAllowed()) {
+      if (lastTargetWindow == 0 && pingCount > 0) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java:178]: Does `pingCount > 0` just avoid this delaying the first ping? Could we instead move this condition after the `!isPinging()` condition and remove the `pingCount > 0`? That'd make it more obvious it happens after. Also, we send pings for reasons other than BDP, so `pingCount` is imprecise.

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java]: It is still subtracting a second, and it is doing something funky with the signedness of `ticker.read()`. It is completely fine for `ticker.read()` to be negative and to overflow and underflow.

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 6]
```diff
@@ -20,9 +20,11 @@
 import static io.netty.channel.ChannelOption.ALLOCATOR;
 import static io.netty.channel.ChannelOption.SO_KEEPALIVE;
 
+
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java:23]: Delete.

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 7]
```diff
@@ -113,6 +116,24 @@ class NettyClientTransport implements ConnectionClientTransport {
...
       LocalSocketPicker localSocketPicker, ChannelLogger channelLogger,
       boolean useGetForSafeMethods) {
+    this(address,channelFactory, channelOptions, group, negotiator, autoFlowControl,
+        flowControlWindow, maxMessageSize, maxHeaderListSize, keepAliveTimeNanos,
+        keepAliveTimeoutNanos, keepAliveWithoutCalls, authority, userAgent, tooManyPingsRunnable,
+        transportTracer, eagAttributes, localSocketPicker, channelLogger, useGetForSafeMethods,
+        Ticker.systemTicker());
+  }
+
+  NettyClientTransport(
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java:126]: Do we really need another constructor? Is it too onerous to modify the existing one?

File: netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java [hunk 8]
```diff
@@ -501,4 +505,128 @@ public void transportTracer_windowUpdate_local() throws Exception {
...
+    for (int i = 0; i < copies; i++) {
+      channelRead(dataFrame(STREAM_ID, false, data.copy())); // buffer it
+      stream().request(1); // consume it
+    }
+  }
+
+  private ByteBuf initXkbBuffer(int multiple) {
+    ByteBuf data = ctx().alloc().buffer(5 + 1024 * multiple);
+    // add header
+    data.writeByte(0);
```
Comment (ejona86) [inline netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java:623]: Seems this should use `dataFrame()`

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java [hunk 9]
```diff
@@ -55,19 +58,31 @@ abstract class AbstractNettyHandler extends GrpcHttp2ConnectionHandler {
       ChannelLogger negotiationLogger,
       boolean autoFlowControl,
       PingLimiter pingLimiter) {
+    this(channelUnused, decoder, encoder, initialSettings, negotiationLogger, autoFlowControl,
+        pingLimiter, Ticker.systemTicker());
+  }
+
+  AbstractNettyHandler(
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java:65]: We don't worry about clients extending this class?

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java (hunk 5 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java:168]: Note that the old line 160 and the new line 182 are identical.  It is really just lines 178-181 being inserted before, so just a question of whether to leave lastTargetWindow as 0 to allow the first ping to go without the delay.  We want the other pings to be delayed if we haven't gotten enough data.

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java (hunk 6 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: Done.

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java (hunk 7 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: I was concerned about compatibility for our users.  I've updated all references and removed the old constructor.

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 10]
```diff
@@ -137,6 +158,7 @@ class NettyClientTransport implements ConnectionClientTransport {
     this.logId = InternalLogId.allocate(getClass(), remoteAddress.toString());
     this.channelLogger = Preconditions.checkNotNull(channelLogger, "channelLogger");
     this.useGetForSafeMethods = useGetForSafeMethods;
+    this.ticker = (ticker != null) ? ticker : Ticker.systemTicker();
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: Done

File: netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java (hunk 8 above)
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java:623]: This is to create a copyable byte buffer for use with dataFrame.

File: netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java [hunk 11]
```diff
@@ -1280,4 +1282,61 @@ protected WriteQueue initWriteQueue() {
   protected void makeStream() throws Exception {
     createStream();
   }
+
+  @Override
+  protected AbstractStream stream() {
+    if (stream == null) {
+      NettyServerStream.TransportState state = new NettyServerStream.TransportState(
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java]: Changed to call makeStream for null streams

File: netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java [hunk 12]
```diff
@@ -1280,4 +1282,61 @@ protected WriteQueue initWriteQueue() {
...
+          handler(),
+          channel().eventLoop(),
+          connection().connectionStream(),
```
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java]: Removed as part of switching to makeStream

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java:65]: The class is package-private, so shouldn't be a problem.

We shouldn't really have any API that you can readily extend, other than interfaces and pseudo-interfaces (abstract classes that could have been interfaces with default methods). The only `Abstract*` classes I see in our javadoc are the stubs, which are extended by the generated code (it used to be just AbstractStub, but per-stub-type classes were later introduced for reasons). We have _lots_ of `final` classes.

[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java]: Done.

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java]: The current logic isn't what's being show here.  It is actually:
```
    void setDataSizeAndSincePing(int dataSize) {
      setDataSizeSincePing(dataSize);
      pingFrequencyMultiplier = 1;
      lastPingTime = ticker.read() ;
    }
```

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java (hunk 5 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java:168]: This pingCount value is being stored in FlowControlPinger, so I believe that it is only tracking the BDP pings.

Comment (ejona86) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java:168]: Oh, `pingCount` was previously unused except for tests. I was thinking it was the counter that is actually saved in PingLimiter.

> so just a question of whether to leave lastTargetWindow as 0 to allow the first ping to go without the delay

I was fine with that part. But to achieve the same goal it seemed clearer to swap the two `if`s. (I think there was confusion when I said "condition" which could mean the entire if or each part of the if.)

```
if (!isPinging() && pingLimiter.isPingAllowed() ...) {
  ...
}
if (lastTargetWindow == 0) {
  ...
}
```

I can live with the `pingCount > 0`, but wanted to offer the alternative.

File: netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java [hunk 13]
```diff
@@ -1280,4 +1280,18 @@ protected WriteQueue initWriteQueue() {
   protected void makeStream() throws Exception {
     createStream();
   }
+
+  @Override
+  protected AbstractStream stream()  {
+    if (stream == null) {
+      try {
+        makeStream();
+      } catch (Exception e) {
```
Comment (ejona86) [inline netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java:1289]: Don't repackage the exception, just add `throws Exception` to the method signature.

File: netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java [hunk 14]
```diff
@@ -136,12 +139,31 @@ public class NettyClientHandlerTest extends NettyHandlerTestBase<NettyClientHand
...
 
   @Override
   protected void manualSetUp() throws Exception {
     setUp();
   }
 
+  @Override
+  protected AbstractStream stream() {
+    if (stream == null) {
+      stream = new NettyClientStream(streamTransportState,
```
Comment (ejona86) [inline netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java:152]: This needs a call to `stream.start()` to actually create the stream. I'm a bit worried by how the test works without it. (Not a problem with your test in particular, but just the overall pre-existing test structure.)

File: netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java (hunk 8 above)
Comment (ejona86) [reply netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java:623]: Ah, I see. Did you consider using `grpcDataFrame()` instead of `dataFrame()`?

File: netty/src/main/java/io/grpc/netty/NettyServerHandler.java [hunk 15]
```diff
@@ -213,6 +214,35 @@ static NettyServerHandler newHandler(
...
       Attributes eagAttributes) {
+    return newHandler(channelUnused, frameReader,frameWriter, transportListener,
+        streamTracerFactories, transportTracer, maxStreams, autoFlowControl, flowControlWindow,
+        maxHeaderListSize, maxMessageSize, keepAliveTimeInNanos, keepAliveTimeoutInNanos,
+        maxConnectionIdleInNanos, maxConnectionAgeInNanos, maxConnectionAgeGraceInNanos,
+        permitKeepAliveWithoutCalls, permitKeepAliveTimeInNanos, eagAttributes,
+        Ticker.systemTicker());
+  }
+
+  static NettyServerHandler newHandler(
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyServerHandler.java:225]: Remove this extra factory method and modify the existing one?

**Review by ejona86 — APPROVED** [review]
I'm a bit concerned about whether the NettyClientStream.start() blows up in our face, but assuming it doesn't, consider the comments and LGTM.

File: netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java (hunk 5 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java]: After your comment, walking through the logic I confirmed that lastTargetWindow will never get reset to 0, so the new value for it isn't needed for the comparison in the if(!isPinging()... .  So, moving as you suggest.

File: netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java (hunk 14 above)
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java:152]: The Netty streams don't have a start method.

File: netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java (hunk 8 above)
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java:623]: grpcDataFrame takes a byte[] which I could return instead of the ByteBuf, but would still need to be built the same way.  grpcDataFrame probably would be slightly more efficient which makes it a good practice.  I'll update it.

File: netty/src/main/java/io/grpc/netty/NettyServerHandler.java (hunk 15 above)
Comment (larry-safran) [reply netty/src/main/java/io/grpc/netty/NettyServerHandler.java:198]: done

File: netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java (hunk 14 above)
Comment (ejona86) [reply netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java:152]: They most definitely do, because it is [part of the `ClientStream` API](https://github.com/grpc/grpc-java/blob/f5e8459748735c794932637d932070f302779d5e/core/src/main/java/io/grpc/internal/ClientStream.java#L79). The method is implemented on `AbstractClientStream`.

File: netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java (hunk 8 above)
Comment (ejona86) [reply netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java]: With `byte[]` I figured you'd use `new byte[1024*x]` instead of `initXkbBuffer()`, what whatever.

File: netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java (hunk 14 above)
Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java:152]: You're right that it is only working because stream is never null when this is called.

Comment (larry-safran) [reply netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java:152]: Created PR 9774 to eliminate this unused and incomplete logic.
