### PR TITLE
TCP_USER_TIMEOUT property setting issue fixed

### LINKED ISSUE #11517: TCP_USER_TIMEOUT property setting issue
The channelFactory may create a NioSocketChannel, but here it uses Utils.maybeGetTcpUserTimeoutOption() to determine whether to set the TCP_USER_TIMEOUT.  It may lead to setting TCP_USER_TIMEOUT when using NioSocketChannel, but in fact, only EpollSocketChannel supports setting this property. I feel that the judgment here is not strict enough. Should we consider optimization?
image

### PR DESCRIPTION
**Pull request by hlx502**
In NettyClientTransport, the TCP_USER_TIMEOUT attribute can be set only if the channel is of the AbstractEpollStreamChannel.

Fixes #11517

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 1]
```diff
@@ -286,6 +280,13 @@ public void run() {
       };
     }
     channel = regFuture.channel();
+    // For non-epoll based channel, the option will be ignored.
+    if (keepAliveTimeNanos != KEEPALIVE_TIME_NANOS_DISABLED && channel instanceof AbstractEpollStreamChannel) {
```
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java:284]: Instead of adding an epoll dependency, let's continue as was already done and use reflection. `Class.forName("io.netty.channel.epoll.AbstractEpollStreamChannel").isInstance(channel)` (and handle errors)

**Comment by ejona86** [comment]
Note that checkstyle is failing due to a long line.

**Review by ejona86 — APPROVED** [review]
Thank you!

**Comment by ejona86** [comment]
@kannanjgithub, can you review?

**Review by kannanjgithub — APPROVED** [review]
