### PR TITLE
inprocess: Support tracing message sizes

### LINKED ISSUE #8712: InProcess: client streaming memory leak when retry enabled
### What version of gRPC-Java are you using?

1.42.0

### What is your environment?

Linux 5.15.2
openjdk version "11.0.13" 2021-10-19

### What did you expect to see?

No java heap space exception.

### What did you see instead?

`java.lang.OutOfMemoryError: Java heap space`

### Steps to reproduce the bug

We've recently updated our grpc dependency from 1.39.0 to 1.42.0 which now causes an out of memory error in one of our tests.

I've attached a test project that can reproduce the problem.
[grpcheap.zip](https://github.com/grpc/grpc-java/files/7562661/grpcheap.zip)

How to run:

```
mvn clean test -Dgrpc.version=1.39.0   # test runs successfully
mvn clean test -Dgrpc.version=1.42.0   # test fails with OOM
```

Please be aware that the test is run with limited heap size (see pom.xml): `-Xmx64M`

The general idea of the test is this:
Client-side has an `InputStream` that produces ~200mb data. This data of that stream is (lazily) split into ~1mb chunks and these are then streamed to the server.

What happens when I run the test with grpc >1.40 is that I get an OOM when it has sent ~60mb worth of chunks, which obviously is near the `-Xmx` limit. However, what I would expect is that the heap usage would never rise to that level, as after each 1mb chunk has been sent that chunk can be gc'ed. I've also attached a screenshot of visualvm where you can see the heap graph of the test using grpc 1.39.0 vs 1.42.0:

grpc

### PR DESCRIPTION
**Pull request by shivaspeaks**
This makes it safe to use with retry which can now measure how much memory is buffered and it enables in-process retry by default.

An optional API is added for `InProcessChannelBuilder` which avoids serializing the message in order to know its size, using which can improve the performance when accurate message sizes are not needed and if nothing else needs the serialized message.

Fixes #8712

### CODE REVIEW

**Comment by larry-safran** [comment]
This PR should include reversing the workaround since it is no longer needed.  Also, we need a test case that enables retries for an InProcessTransport and then sends a bunch of messages so it can verify that there wasn't a memory leak.

**Comment by ejona86** [comment]
> Also, we need a test case that enables retries for an InProcessTransport and then sends a bunch of messages so it can verify that there wasn't a memory leak.

That sounds like it'll be too much effort. Tests that look at memory use directly tend to be a bad idea, and "run until oom" is hard to get right. It is easiest to reproduce the issue using a real stub+channel, but I don't think RetryableStream offers a real way to see that it has committed in that case. And even if we did it at the transport layer instead, things aren't much better. Wiring that all up seems too much work for a first PR in gRPC, and probably excessive for you and me as well for the amount of value it'll provide.

AbstractTransportTest already has tests for the outbound/inbound size tracer callbacks (`sizesReported() == true`). They are simply disabled for InProcessTransport today. If we pass those tests, RetryableStream will be satisfied. So let's just do that, which does mean we'll implement `outboundUncompressedSize`, `inboundWireSize`, `inboundUncompressedSize` as well, but that's incrementally pretty easy. (The wire sizes and the uncompressed sizes are the same for in-process.)

We should still manually verify the memory use is fixed using the reproduction. But it seems too much work for little gain to make it automated.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 1]
```diff
@@ -786,6 +790,28 @@ public void writeMessage(InputStream message) {
...
+          } catch (RuntimeException e) {
+            throw Status.INTERNAL
+                    .withDescription("Failed to calculate size")
+                    .withCause(e)
+                    .asRuntimeException();
+          }
+          statsTraceCtx.outboundUncompressedSize(messageLength);
+          statsTraceCtx.outboundWireSize(messageLength);
+          // messageLength should be same at receiver's end as no actual wire is involved.
+          serverStream.statsTraceCtx.inboundUncompressedSize(messageLength);
```
Comment (larry-safran) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:813]: Given that you are reporting on the server side, why not just get rid of the if statements around sizes reported?

File: inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java [hunk 2]
```diff
@@ -117,10 +117,6 @@ public ClientTransportFactory buildClientTransportFactory() {
     managedChannelImplBuilder.setStatsRecordStartedRpcs(false);
     managedChannelImplBuilder.setStatsRecordFinishedRpcs(false);
     managedChannelImplBuilder.setStatsRecordRetryMetrics(false);
-
-    // By default, In-process transport should not be retriable as that leaks memory.  Since
-    // there is no wire, bytes aren't calculated so buffer limit isn't respected
-    managedChannelImplBuilder.disableRetry();
```
Comment (kannanjgithub) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java:123]: In the issue there was a [comment](https://github.com/grpc/grpc-java/issues/8712#issuecomment-976032497) saying retry is enabled by default since 1.40. Since disableRetry() was called here, can you check how that could be the case?

File: core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java [hunk 3]
```diff
@@ -870,7 +874,7 @@ public void basicStream() throws Exception {
     clientStream.halfClose();
     assertTrue(serverStreamListener.awaitHalfClosed(TIMEOUT_MS, TimeUnit.MILLISECONDS));
 
-    if (sizesReported()) {
+    if (sizesReportedAtClient()) {
```
Comment (kannanjgithub) [inline core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java:877]: Should be if (sizesReportedAtServer()) ?

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 4]
```diff
@@ -786,6 +790,28 @@ public void writeMessage(InputStream message) {
...
+          long messageLength = -1;
+          try {
+            messageLength = getKnownLength(message);
+          } catch (IOException e) {
+            throw Status.INTERNAL
+                    .withDescription("Failed to calculate size")
+                    .withCause(e)
+                    .asRuntimeException();
+          } catch (StatusRuntimeException e) {
+            throw e;
```
Comment (kannanjgithub) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:803]: Why do we need to treat this exception different? Why not have a single catch statement for all 3 exception types?

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java [hunk 5]
```diff
@@ -87,7 +87,7 @@ protected ManagedClientTransport newClientTransport(InternalServer server) {
   }
 
   @Override
-  protected boolean sizesReported() {
+  protected boolean sizesReportedAtServer() {
```
Comment (kannanjgithub) [inline inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java:90]: Isn't your changes in InProcessTest.java writing to serverStream.statsTraceCtx reporting the sizes at server now?

File: core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java [hunk 6]
```diff
@@ -919,7 +923,7 @@ public void basicStream() throws Exception {
     assertEquals("Hi. Who are you?", methodDescriptor.parseResponse(message));
     assertThat(clientStreamTracer1.nextInboundEvent())
         .matches("inboundMessageRead\\(0, -?[0-9]+, -?[0-9]+\\)");
-    if (sizesReported()) {
+    if (sizesReportedAtServer()) {
       assertThat(clientStreamTracer1.getInboundWireSize()).isGreaterThan(0L);
```
Comment (kannanjgithub) [inline core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java:927]: I think we should add an assertion if (this instanceof InProcessTransportTest)) then assert that the outbound wire and uncompressed sizes are the same for the client stream tracer and the server stream tracer.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 1 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:830]: Updated with the new commit by reporting sizes on both client side and server sides and removing if statements. 

Correction: In previous commit sizes were reported only on client side.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 4 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java]: Motivation is from MessageFramer, [here](https://github.com/grpc/grpc-java/blob/9bed655c568b4f09a32b3910745a949f5f08d956/core/src/main/java/io/grpc/internal/MessageFramer.java#L138)

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java (hunk 5 above)
Comment (shivaspeaks) [reply inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java]: Previously it was only at client side as the github bug talks about only client side memory leak. But in the latest commit, sizes are being reported on both server and client side.

File: core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java (hunk 6 above)
Comment (shivaspeaks) [reply core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java]: Is it needed now as the new commit contains sizes being reported on both sides, client and server? 
Now all the transports will be having same checks. If required we can sure add this additional check for just Inprocess transport.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java (hunk 2 above)
Comment (larry-safran) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java:123]: On 7/19/22 I added these lines that are being deleted here.  It was a workaround so that ManagedChannelImplBuilder could continue to have retry enabled without InProcessTransport running into the memory leak problem.

**Review by larry-safran — APPROVED** [review]

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 7]
```diff
@@ -414,6 +418,31 @@ private void streamClosed() {
...
+
+    private long getMessageLength(InputStream inputStream) {
+      try {
+        return getKnownLength(inputStream);
+      } catch (IOException e) {
+        throw Status.INTERNAL
+                .withDescription("Failed to calculate size")
+                .withCause(e)
+                .asRuntimeException();
+      } catch (StatusRuntimeException e) {
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:436]: We don't need to special-case StatusRuntimeException. This code won't throw that, whereas in MessageFramer (which it seems you were copying), the code would use such an exception itself. If an InputStream throws a StatusRuntimeException, I think we still want to use our status code.

That also means we can use `IOException|RuntimeException` syntax now.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 8]
```diff
@@ -414,6 +418,31 @@ private void streamClosed() {
       }
     }
 
+    private int getKnownLength(InputStream inputStream) throws IOException {
+      if (inputStream instanceof KnownLength || inputStream instanceof ByteArrayInputStream) {
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:422]: We need to support all InputStream types. These two conditions are the fast path. But we will still need the slow path that serializes into byte[]s and then creates a new InputStream for the receiving side. That is probably easiest done with `ByteStreams.toByteArray()` and `ByteArrayInputStream` (it isn't the most efficient, but in general if someone wants something to be fast we need KnownLength).

**Review by ejona86 — COMMENTED** [review]
We're going to need a way to disable the new behavior, for performance cases. Even if the InputStream is KnownLength, a protobuf has to walk its tree and calculate its size. I'm not quite sure what form would be best, but all of them should be an option on InProcess{Channel,Server}Builder.

I'm toying with the idea of "assumedMessageSize(int)". The main issue with disabling the new behavior is obviously retries will be broken. The option _could_ also disable retries, but it seems it might be nicer to have the user provide us with a message size, and we'll just use that instead. Dunno if we need "assumedMessageSize(int sent, int received)" or any other more fancy options. And I don't know if the idea itself is too fancy and it'd be easy to just accept no retries. Although it also impacts tracing, and more.

@larry-safran, any ideas?

**Comment by larry-safran** [comment]
I think that `assumedMessageSize(int bytes)` is the way to go.  Having different values for sending and receiving when they are expected to be identical seems overly complicated.  Since the size  tracing for both is being driven from the client side, we probably only need this method on the `InProcessChannelBuilder`.

**Comment by ejona86** [comment]
> Since the size tracing for both is being driven from the client side, we probably only need this method on the InProcessChannelBuilder.

Right now it is being driven by the sender, which is both client and server. I don't think we'd want to mix the configuration between the channel and server; so we'd want to configure it on both sides. That'd be a bit annoying, but seems like the alternative is too confusing.

**Comment by larry-safran** [comment]
Okay, we just need to say in the javadoc that it applies to messages sent
from the side of the channel where it is specified and probably reference
each other.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 9]
```diff
@@ -99,6 +99,9 @@ final class InProcessTransport implements ServerTransport, ConnectionClientTrans
   private ServerTransportListener serverTransportListener;
   private Attributes serverStreamAttributes;
   private ManagedClientTransport.Listener clientTransportListener;
+  // These sizes are assumed from the sender' side.
+  private long serverAssumedMessageSize = -1;
+   private long clientAssumedMessageSize = -1;
```
Comment (larry-safran) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:104]: Why have 2 values? I thought we agreed on just one.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 10]
```diff
@@ -164,6 +167,14 @@ public InProcessTransport(
         Optional.<ServerListener>absent(), includeCauseWithStatus);
   }
 
+  public InProcessTransport(
```
Comment (larry-safran) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:170]: It is better practice to have the constructor with fewer arguments call the one with more arguments passing in the default for the extra arguments.  In this case, all of the existing logic moves to the one with assumedMessageSize and the one without assumedMessageSize would have no logic other than calling the one with it passing in a -1.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 11]
```diff
@@ -192,6 +203,7 @@ public synchronized Runnable start(ManagedClientTransport.Listener listener) {
         serverStreamTracerFactories = server.getStreamTracerFactories();
         // Must be semi-initialized; past this point, can begin receiving requests
         serverTransportListener = server.register(this);
+        serverAssumedMessageSize = server.getAssumedMessageSize();
```
Comment (larry-safran) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:206]: assigning the value is part of initialization, so should go before the comment above.  You want all initialization to be complete before registering it.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 12]
```diff
@@ -545,7 +543,24 @@ public void writeMessage(InputStream message) {
           clientStream.statsTraceCtx.inboundMessage(outboundSeqNo);
           clientStream.statsTraceCtx.inboundMessageRead(outboundSeqNo, -1, -1);
 
-          long messageLength = getMessageLength(message);
+          /*long messageLength = serverAssumedMessageSize == -1
+                  ? getMessageLength(message) : serverAssumedMessageSize;*/
+          long messageLength = -1;
+          try {
+            if (!(message instanceof KnownLength) && !(message instanceof ByteArrayInputStream)) {
```
Comment (larry-safran) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:550]: It should be inside this if that you check for assumedMessageSize.  If it is -1 do the existing logic otherwise just set messageLength to assumedMessageSize.

Same for the client stream.

File: inprocess/src/test/java/io/grpc/inprocess/AnonymousInProcessTransportTest.java [hunk 13]
```diff
@@ -52,6 +52,6 @@ protected InternalServer newServer(
   protected ManagedClientTransport newClientTransport(InternalServer server) {
     return new InProcessTransport(
         address, GrpcUtil.DEFAULT_MAX_HEADER_LIST_SIZE,
-        testAuthority(server), USER_AGENT, eagAttrs(), false);
+        testAuthority(server), USER_AGENT, eagAttrs(), false, -1);
```
Comment (larry-safran) [inline inprocess/src/test/java/io/grpc/inprocess/AnonymousInProcessTransportTest.java:55]: You shouldn't change this to make sure that the default left the old behavior.

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java [hunk 14]
```diff
@@ -83,7 +83,7 @@ protected String testAuthority(InternalServer server) {
   protected ManagedClientTransport newClientTransport(InternalServer server) {
     return new InProcessTransport(
         new InProcessSocketAddress(TRANSPORT_NAME), GrpcUtil.DEFAULT_MAX_HEADER_LIST_SIZE,
-        testAuthority(server), USER_AGENT, eagAttrs(), false);
+        testAuthority(server), USER_AGENT, eagAttrs(), false, -1);
```
Comment (larry-safran) [inline inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java:86]: You can leave this as it was since the default will be -1.  You should also add a test where you use create the InProcessTransport with a positive number (like 100) and verify that the reported length is what you expected.

**Comment by larry-safran** [comment]
To fix the census test, in CensusModulesTest.java change the class declaration to
`  private static class StringInputStream extends InputStream implements KnownLength { ` and add to the StringInputStream class
```

    @Override
    public int available() throws IOException {
      return string == null ? 0 : string.length();
    }
```

That will allow the test to behave in the way it intends.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 10 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:169]: I'm afraid we might need to change couple of things if we do this as there's one parameter which is used by InternalInProcess, "optionalServerListener" and is forwarded to the private constructor. If we do what has been suggested above then we specifically want users to provide "Optional.<ServerListener>absent()" when asking for assumedMessageSize in overloaded constructor. I tried couple of workarounds to just initialize this variable beforehand, but then we need to remove 'final' keyword from it as the warning says with assumption, it might have been initialized and the build fails.

Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:169]: That was added in https://github.com/grpc/grpc-java/commit/fd5f4aac631b17ad8b8c3796a7b1502273b1424e . I think it is no longer being used that way. We can potentially delete some of that code, but we should double-check it isn't being used in this repo and not in google3.

**Review by kannanjgithub — APPROVED** [review]

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 10 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:169]: I think there is one mention of InternalInProcess in google3, [here](https://source.corp.google.com/piper///depot/google3/third_party/java_src/appengine_standard/jar_contents/runtime-impl.classes;l=8524;bpv=0;bpt=0) in runtime implementations. Not sure it is actually getting used.

Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:169]: That isn't a usage. That is just a list of classes that are in the built output.

File: inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java
Comment (larry-safran) [inline inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java:1]: There isn't a need to have a completely separate class.  Just add tests to the regular InProcessTransportTest where you check that sizes are correctly reported for various scenarios:  Specified an assumedSize that is different from the actual size; didn't specify the assumedSize; sent several messages.

Comment (shivaspeaks) [reply inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java:1]: We might not be able do that because we need to have an instance of InProcessTransport specified with `TEST_MESSAGE_LENGTH` for this test. So if do that within InProcessTransportTest itself then we are expecting other tests like AnonymousInProcessTransportTest with the expected `TEST_MESSAGE_LENGTH`.

File: core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java [hunk 15]
```diff
@@ -249,6 +250,11 @@ protected long fakeCurrentTimeNanos() {
     throw new UnsupportedOperationException();
   }
 
+  protected void assertInProcessTransportAssumedMessageSize(
```
[the remark this answers is not in the document]
Comment (shivaspeaks) [reply core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java:253]: The actual tests are indeed written in the test file specific to InProcessTransport. The only reason to keep it like it is (overriden) is that the way tests are written. The test flow is already created in AbstractTransportTest, if I tend to move the `assertInProcessTransportAssumedMessageSize()` completely  away from AbstractTransportTest then we might need to do some redundant work there such as again creating basicStream etc.

[the remark this answers is not in the document]
Comment (larry-safran) [reply core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java:253]: It is better to do the redundant work than to pollute the shared base class.

File: inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java
Comment (larry-safran) [reply inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java:1]: You just need to do the full channel creation in the specific tests instead of relying on the shared setup.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 16]
```diff
@@ -515,6 +541,29 @@ public void writeMessage(InputStream message) {
           statsTraceCtx.outboundMessageSent(outboundSeqNo, -1, -1);
           clientStream.statsTraceCtx.inboundMessage(outboundSeqNo);
           clientStream.statsTraceCtx.inboundMessageRead(outboundSeqNo, -1, -1);
+
+          long messageLength;
+          try {
+            if (assumedMessageSize != -1) {
+              messageLength = assumedMessageSize;
+            } else if (message instanceof KnownLength || message instanceof ByteArrayInputStream) {
+              messageLength = getKnownLength(message);
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:550]: Just call `inputStream.available()` directly here? This is already within a try block that catches IOException, and there's no reason for one to be StatusRuntimeException and the other to be regular RuntimeException.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 17]
```diff
@@ -515,6 +541,29 @@ public void writeMessage(InputStream message) {
           statsTraceCtx.outboundMessageSent(outboundSeqNo, -1, -1);
           clientStream.statsTraceCtx.inboundMessage(outboundSeqNo);
           clientStream.statsTraceCtx.inboundMessageRead(outboundSeqNo, -1, -1);
+
+          long messageLength;
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:545]: We should do all this messageLength work outside of the `synchronized (this)` block. It's okay to "waste" CPU doing the work and then it turns out `closed == true`.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 18]
```diff
@@ -515,6 +541,29 @@ public void writeMessage(InputStream message) {
...
+              messageLength = getKnownLength(message);
+            } else {
+              InputStream oldMessage = message;
+              byte[] payload = ByteStreams.toByteArray(message);
+              messageLength = payload.length;
+              message = new ByteArrayInputStream(payload);
+              oldMessage.close();
+            }
+          } catch (IOException e) {
+            throw new RuntimeException("Error processing the message length", e);
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:559]: I'm uncertain about what "proper" exception handling looks like here. I'll need to look into it.

Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:559]: Looks like any exception is fine. It might be converted into CANCELLED:
https://github.com/grpc/grpc-java/blob/d034a56cb0de3b5e3635c8ecb381085d02b4ddbf/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L526

Although that isn't guaranteed; it looks like when using DelayedStream nothing might catch this exception. I think the answer here is "the exception never happens so nobody would notice if it isn't handled well."

File: inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java
Comment (shivaspeaks) [reply inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java:1]: I'm trying to take reference from [basicStream()](https://github.com/grpc/grpc-java/blob/d034a56cb0de3b5e3635c8ecb381085d02b4ddbf/core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java#L793) and creating a new test function in InProcessTransportTest naming it basicStreamInProcess(). All the lines before line 857, I'm almost taking every line for the setup except the Assertion statements and verification statements.

And at last I'll just be Asserting with what we need to test
```
assertEquals(TEST_MESSAGE_LENGTH, streamTracerSender.getOutboundWireSize());
assertEquals(TEST_MESSAGE_LENGTH, streamTracerSender.getOutboundUncompressedSize());
assertEquals(TEST_MESSAGE_LENGTH, streamTracerReceiver.getInboundWireSize());
assertEquals(TEST_MESSAGE_LENGTH, streamTracerReceiver.getInboundUncompressedSize());
```
So by doing this, a lot of variables and inner private classes of AbstractTransportTest comes into picture. I made all of them as protected or public wherever necessary. Otherwise we will be ending up re-writing all the classes again provided in AbstractTransportTest. Adding all this will pollute the class even more and that too just for 1 test! Also, I'm running into more unseen errors by full channel creation within test. Maybe we should fallback to the current approach itself of having a different class and we cans specify in the javadoc that this test specifically runs for assumed size in InProcess transport? Its getting complex here.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 16 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:550]: Alright sounds good.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 17 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:545]: Got it.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java [hunk 19]
```diff
@@ -210,4 +211,9 @@ public InProcessServerBuilder useTransportSecurity(File certChain, File privateK
   void setStatsEnabled(boolean value) {
     this.serverImplBuilder.setStatsEnabled(value);
   }
+
+  public InProcessServerBuilder assumedMessageSize(long assumedMessageSize) {
```
[the remark this answers is not in the document]
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java:215]: I'll add javadoc and disallow negative values.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java [hunk 20]
```diff
@@ -243,6 +239,7 @@ static final class InProcessClientTransportFactory implements ClientTransportFac
     private final int maxInboundMetadataSize;
     private boolean closed;
     private final boolean includeCauseWithStatus;
+    private final long assumedMessageSize = -1;
```
[the remark this answers is not in the document]
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java:242]: Noted.

File: inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java
Comment (kannanjgithub) [reply inprocess/src/test/java/io/grpc/inprocess/SizesReportedInProcessTransportTest.java:1]: Hi @larry-safran, we are waiting for your reply. We don't want to copy the private classes TestServerStreamTracer and TestClienttreamTracer in AbstractTransportTest, and moving them out to separate classes defeats the purpose of avoiding creating new test files unnecessarily.

**Comment by larry-safran** [comment]
Hi Shiva,
  Sorry for the long delay getting back to you.  All of the private static
classes are really general utility classes and should be public.
StringMarshaller already exists in
api/src/testFixtures/java/io/grpc/StringMarshaller.java. The
StringBinaryMarshaller should probably be moved to that StringMarshaller
class and both removed from AbstractTransportTest.

Adding a getServerStreamTracerFactory() method to AbstractTransportTest
should make creating the server you want easy.

Then you can add @Test methods to InProcessTransportTest.  I'd suggest
pulling the common initializations into helper method(s).

Hope that helps,
  Larry

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java [hunk 21]
```diff
@@ -163,11 +178,62 @@ public Listener<Void> startCall(ServerCall<Void, Void> call, Metadata headers) {
...
-      ClientCalls.futureUnaryCall(call, null).get(5, TimeUnit.SECONDS);
+      ClientCalls.futureUnaryCall(call, null).get(TIMEOUT_MS, TimeUnit.MILLISECONDS);
       fail("Call should fail.");
     } catch (ExecutionException ex) {
       StatusRuntimeException s = (StatusRuntimeException)ex.getCause();
       assertEquals(Code.UNIMPLEMENTED, s.getStatus().getCode());
     }
   }
+
+  @Ignore
```
Comment (larry-safran) [inline inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java:189]: Is the @Ignore because it isn't working?

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java [hunk 22]
```diff
@@ -55,23 +61,26 @@ public class InProcessTransportTest extends AbstractTransportTest {
...
 
   @Override
   protected InternalServer newServer(
-      int port, List<ServerStreamTracer.Factory> streamTracerFactories) {
-    return newServer(streamTracerFactories);
+      List<ServerStreamTracer.Factory> streamTracerFactories) {
+    InProcessServerBuilder builder = InProcessServerBuilder
+        .forName(TRANSPORT_NAME)
+        .maxInboundMetadataSize(GrpcUtil.DEFAULT_MAX_HEADER_LIST_SIZE)
+        .assumedMessageSize(TEST_MESSAGE_LENGTH);
```
Comment (larry-safran) [inline inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java:82]: This means that we aren't testing without assumedMessageSize.  I would suggest that instead of setting assumedMessageSize here we just create a new server in basicStreamInProcess()
```
    InProcessServerBuilder builder = InProcessServerBuilder
        .forName(TRANSPORT_NAME)
        .maxInboundMetadataSize(GrpcUtil.DEFAULT_MAX_HEADER_LIST_SIZE)
        .assumedMessageSize(TEST_MESSAGE_LENGTH);
server = new InProcessServer(builder, server.getStreamTracerFactories());
```

**Review by larry-safran — COMMENTED** [review]
This is getting very close.

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java (hunk 21 above)
Comment (shivaspeaks) [reply inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java:189]: This test is working. But this test is also running when AnonymousInProcessTransportTest runs and then fails because Anonymous.. creates its own transport. What I can do is override this test method (basicStreamInProcess) in AnonymousInProcessTransportTest and then @Ignore it. Solution works but is this the right approach? If yes then I also wanted to check with unit test's name `basicStreamInProcess`.

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java (hunk 22 above)
Comment (shivaspeaks) [reply inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java:82]: Sure.

File: inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java (hunk 21 above)
Comment (larry-safran) [reply inprocess/src/test/java/io/grpc/inprocess/InProcessTransportTest.java:189]: You are using `newClientTransportWithAssumedMessageSize`, so you could just override that in AnonymousInProcessTransportTest so that it uses `address`

**Review by larry-safran — APPROVED** [review]

File: inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java [hunk 23]
```diff
@@ -225,9 +222,23 @@ public InProcessChannelBuilder propagateCauseWithStatus(boolean enable) {
     return this;
   }
 
+  /**
+   * Sets whether to include the provided messageSize or not and is propagated
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java:226]: The language here is pretty confusing. InProcessTransport is an implementation detail; it shouldn't be mentioned. How about:

> Assumes RPC messages are the specified size. This avoids serializing messages for metrics and retry memory tracking. This can dramatically improve performance when accurate message sizes are not needed and if nothing else needs the serialized message.

We should add a note to set this on both the client-side and server-side?

File: inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java [hunk 24]
```diff
@@ -225,9 +222,23 @@ public InProcessChannelBuilder propagateCauseWithStatus(boolean enable) {
...
+   * forward to InProcessTransport. This was added to not calculate messageSize
+   * if already provided while calling builder.
+   *
+   * @param assumedMessageSize length of InProcess transport's messageSize
+   * @return this
+   */
+  public InProcessChannelBuilder assumedMessageSize(long assumedMessageSize) {
+    checkArgument(assumedMessageSize >= 0, "assumedMessageSize must be >= 0");
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java:234]: Document that the size should be non-negative? Alternatively, we could document that a negative value disables the assumption; we typically provide a way to undo previous calls, but it isn't likely all that important here.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java [hunk 25]
```diff
@@ -111,6 +111,7 @@ public static String generateName() {
   private final ServerImplBuilder serverImplBuilder;
   final SocketAddress listenAddress;
   int maxInboundMetadataSize = Integer.MAX_VALUE;
+  long assumedMessageSize = -1;
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java:114]: Does this do anything?

Comment (larry-safran) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java:114]: This value is looked for to identify that the assumedMessageSize hasn't been set.  It would be nice to, as was said above, consider any negative number to be disabling assumedMessageSize and allow users to specify negative numbers (with appropriate update to javadoc).

Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java:114]: Let me say this another way: it seems either the client-side or server-side value is ignored. InProcessTransport is shared between client and server, so one must be thrown away. I thought it was server-side, but looking a bit more I now see the `assumedMessageSize = server.getAssumedMessageSize();` line in start(), maybe it is client-side as the value is overwritten by server-side.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java [hunk 26]
```diff
@@ -186,6 +199,8 @@ public synchronized Runnable start(ManagedClientTransport.Listener listener) {
         serverSchedulerPool = server.getScheduledExecutorServicePool();
         serverScheduler = serverSchedulerPool.getObject();
         serverStreamTracerFactories = server.getStreamTracerFactories();
+        assumedMessageSize =
+            (assumedMessageSize == -1) ? server.getAssumedMessageSize() : assumedMessageSize;
```
Comment (shivaspeaks) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:203]: @ejona86 I made this conditional change in response to this [comment](https://github.com/grpc/grpc-java/pull/11406#discussion_r1757048666)

By doing this, assumedMessageSize will take the value from client provided if it was not provided by server.

Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:203]: Hi @ejona86 please review this.

Comment (larry-safran) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:203]: Hi Shiva,
  You should only have the assumedMessageSize on one side and then have both sides use that.  You shouldn't allow for values to be set separately for client and server side, so remove it from either InProcessChannelBuilder or InProcessServerBuilder.

Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java]: Okay. I removed it from InProcessServerBuilder.

**Review by larry-safran — APPROVED** [review]

File: core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java [hunk 27]
```diff
@@ -139,9 +139,6 @@ protected abstract InternalServer newServer(
   /**
    * Returns true (which is default) if the transport reports message sizes to StreamTracers.
```
Comment (ejona86) [inline core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java:140]: Delete the javadoc for the deleted method as well.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java [hunk 28]
```diff
@@ -225,9 +222,24 @@ public InProcessChannelBuilder propagateCauseWithStatus(boolean enable) {
...
   }
 
+  /**
+   * Assumes RPC messages are the specified size. This avoids serializing
+   * messages for metrics and retry memory tracking. This can dramatically
+   * improve performance when accurate message sizes are not needed and if
+   * nothing else needs the serialized message.
+   * @param assumedMessageSize length of InProcess transport's messageSize.
+   * @return this
+   * @throws IllegalArgumentException if assumedMessageSize is non-positive
```
Comment (ejona86) [inline inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java:232]: non-positive means 0 would throw. This should just be "negative"

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 10 above)
Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:168]: What happened here? I don't see why we can't make the variable `final`.

There's only four pre-existing call sites for constructing an InProcessTransport, and three of them use the same constructor. Why can't we just modify the existing constructor and add `-1` to the two test lines that construct the transport?

Comment (larry-safran) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:168]: I was confused by this comment, but finally figured out the context.  The suggestion is to make `assumedMessageSize` final which means that it can't be initialized in the declaration, it must be initialized in all of the constructors.  So constructors can pass a -1 if they didn't have an assumedMessageSize argument.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java (hunk 28 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java]: Done.

File: core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java (hunk 27 above)
Comment (shivaspeaks) [reply core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java]: Oh okay, this was left unseen. Done.

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 10 above)
Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:168]: Marking this conversation as not resolved.

Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:168]: #11605 this PR makes it possible to do the above mentioned thing. I was not sure about cleaning that code. Thanks.

Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:168]: This was possible without that other PR. You just modify the existing constructor and change all callers.

Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java:168]: Okay so I lost the context why I kept it like that, I recall the problem is, there's a public constructor `InProcessTransport` which I was avoiding to touch as I thought we should not change the existing callers (what if clients are using that api directly, my concern was around this).

Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java]: New commit added with all the needful from this thread.

Comment (ejona86) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java]: While the constructor is public, the class is package-private, so the API is not actually exposed to arbitary callers.

**Review by ejona86 — APPROVED** [review]
When merging, we should rework the commit message. Saying "Fix inprocess memory leak" doesn't really say what leak is being fixed or what change is being done. Take a look at CONTRIBUTING.md for formatting commit messages, but this could be "inprocess: Fix retry unlimited buffering" or "inprocess: Support tracing message sizes". In the description it would then talk about the other aspect, so "This adds support for tracing message sizes so retry can measure how much memory is buffered" or "This makes it safe to use with retry which can now measure how much memory is buffered," respectively. It should also talk about how measuring message sizes can be expensive so an API was added to avoid that cost.

We should also use "Fixes #8712" syntax in the description so the commit/PR and the issue are linked (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue).

File: inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java (hunk 10 above)
Comment (shivaspeaks) [reply inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java]: I see.

**Comment by zhangkun83** [comment]
Since this change also enables in-process retry by default, I would expect this to be explicitly called out in the commit message.
