### PR TITLE
core: DelayedStream should start() real stream immediately

### LINKED ISSUE #6283: DelayedClientTransport can trigger RejectedExecutionException
We've seen the following exception (b/142475326):
```
java.util.concurrent.RejectedExecutionException
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:13)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:696)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:646)
        at io.grpc.internal.DelayedStream$DelayedStreamListener$5.run(DelayedStream.java:475)
        at io.grpc.internal.DelayedStream$DelayedStreamListener.drainPendingCallbacks(DelayedStream.java:500)
        at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:168)
        at io.grpc.internal.DelayedStream.setStream(DelayedStream.java:132)
        at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:358)
        at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

The application was using our default executor, which means we scheduled work after the channel terminated or the reference counting is broken.

When the channel terminates it guarantees that it is done scheduling work on the executor, but not that all the scheduled work is complete. The problem here appears that some of that work is scheduling more work on the same executor.

Specifically, this runnable can produce more runnables:
https://github.com/grpc/grpc-java/blob/ddaf1c8ce96a99da01a3915d5a84c6efd9c09bea/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L297-L302

But while that runnable is running, 'stream' is likely to have already been removed from 'pendingStreams'. So if the channel is shut down at that point the transport will terminate abruptly and no other transport will "own" the call yet, so the entire channel can terminate before the runnable completes.

We could either split start() draining to a separate method in DelayedStream so that newStream()+start() can be called directly within reprocess(), or we could keep a counter for the number of streams still draining and delay transport termination until it reaches zero.

### PR DESCRIPTION
**Pull request by ejona86**
DelayedClientTransport needs to avoid becoming terminated while it owns
RPCs. Previously DelayedClientTransport could terminate when some of its
RPCs had their realStream but realStream.start() hadn't yet been called.

To avoid that, we now make sure to call realStream.start()
synchronously with setting realStream. Since start() and the method
calls before start execute quickly, we can run it in-line. But it does
mean we now need to split the Stream methods into "before start" and
"after start" categories for queuing.

Fixes #6283

CC @voidzcy

### CODE REVIEW

**Comment by ejona86** [comment]
A test will be added as part of https://github.com/grpc/grpc-java/pull/7749

**Comment by YifeiZhuang** [comment]
We went through the flow, and here is an over simplified chart to illustrate why RPCs will never be orphaned after the fix. 
[delayed stream start then set](https://drive.google.com/file/d/1eJh3cMj8rwHPXIGFxGBzTJ69_235pGhV/view?usp=sharing)
[delayed stream set and start](https://drive.google.com/file/d/1YTAmwl12A00lRWtVs4TAMSxGJ-gGA9S6/view?usp=sharing)

FYI @dapengzhang0

File: core/src/main/java/io/grpc/internal/DelayedClientTransport.java [hunk 1]
```diff
@@ -346,7 +344,8 @@ private PendingStream(PickSubchannelArgs args) {
       this.args = args;
     }
 
-    private void createRealStream(ClientTransport transport) {
+    /** Runnable may be null. */
```
Comment (dapengzhang0) [inline core/src/main/java/io/grpc/internal/DelayedClientTransport.java:347]: Why not use `@Nullable` or `@CheckForNull` annotation rather than comment?

File: core/src/main/java/io/grpc/internal/DelayedStream.java [hunk 2]
```diff
@@ -298,10 +325,11 @@ public void run() {
         }
       });
     } else {
+      drainPendingCalls();
       if (listenerToClose != null) {
```
Comment (dapengzhang0) [inline core/src/main/java/io/grpc/internal/DelayedStream.java:329]: Seems `listenerToClose` must be nonnull here (after adding assertion `checkState(listener != null)`). `delegateToRealStream  == true` iff `listenerToClose == null` as they change value together.

**Review by dapengzhang0 — APPROVED** [review]
LGTM. A couple of minor comments.

File: core/src/main/java/io/grpc/internal/DelayedClientTransport.java (hunk 1 above)
Comment (ejona86) [reply core/src/main/java/io/grpc/internal/DelayedClientTransport.java:347]: All of those are equivalent, and I wouldn't spend any time debating which to use for a private method. If we had a nullness checker such that the annotations weren't just a comment with a different syntax, it would be different.

File: core/src/main/java/io/grpc/internal/DelayedStream.java (hunk 2 above)
Comment (ejona86) [reply core/src/main/java/io/grpc/internal/DelayedStream.java]: Yes, `listener` is non-null and it is copied to `listenerToClose` only when `delegateToRealStream = false`. Removed `listenerToClose`, as there's no longer any synchronization necessary when accessing listener.

File: core/src/main/java/io/grpc/internal/DelayedStream.java [hunk 3]
```diff
@@ -306,14 +306,11 @@ public void cancel(final Status reason) {
     checkState(listener != null, "May only be called after start");
```
Comment (YifeiZhuang) [inline core/src/main/java/io/grpc/internal/DelayedStream.java:306]: Separate note: there might be a race at delayedClient `shutdownNow()` to make `start()` call after `cancel()`, which may cause shutdownNow fail?

Comment (ejona86) [reply core/src/main/java/io/grpc/internal/DelayedStream.java:306]: Yes, `shutdownNow()` could call `cancel()` before `start()` which is now disallowed. Fixing that is not trivial; I'll need to look into a few options.

Comment (dapengzhang0) [reply core/src/main/java/io/grpc/internal/DelayedStream.java:306]: For `shutdownNow()`, we can do `runnable = pendingStream.setStream(new FailingStream(status))` before `pendingStream.cancel(status)`

Comment (YifeiZhuang) [reply core/src/main/java/io/grpc/internal/DelayedStream.java:306]: If we keep reusing `cancel()` for force shutdown then we can't avoid competing with customer call and there is no way we can guarantee the call order, and we would have to support that. I feel it would be fair to have `delayedStream` take the responsibility instead of `shutdownNow()`. Or we use another method to do force shutdown to not mix with `cancel()`, but that would require same about of change. This problem is originally there so I guess we should fix that separately.

Comment (ejona86) [reply core/src/main/java/io/grpc/internal/DelayedStream.java:306]: I was wrong. Fixing it was trivial! "Use setStream() instead of cancel()." Thank you @YifeiZhuang for noticing.

**Review by YifeiZhuang — APPROVED** [review]
