### PR TITLE
netty: Handle channel creation failure

### LINKED ISSUE #2296: Client side NPE when sending large number of concurrent requests
Both server and client use GRPC 1.0.
Client log:

```
Exception in thread "grpc-default-executor-95" java.lang.NullPointerException: channel
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at io.grpc.netty.WriteQueue.<init>(WriteQueue.java:76)
        at io.grpc.netty.NettyClientHandler.startWriteQueue(NettyClientHandler.java:223)
        at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:172)
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:45)
        at io.grpc.internal.TransportSet.startNewTransport(TransportSet.java:215)
        at io.grpc.internal.TransportSet.obtainActiveTransport(TransportSet.java:188)
        at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:637)
        at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:579)
        at 
......
```

Server log:

```
WARN  [2016-09-22 21:28:41,870] io.netty.channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. [client=null]
! java.io.IOException: Too many open files in system
! at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_60]
! at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_60]
! at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_60]
! at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:140) ~[netty.jar:4.1.5.Final]
! at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) ~[netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551) [netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465) [netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty.jar:4.1.5.Final]
! at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty.jar:4.1.5.Final]
! at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty.jar:4.1.5.Final]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

### PR DESCRIPTION
**Pull request by ejona86**
Something 'very bad' has happened, but without grpc propagating the
cause from the Future it is very difficult to figure out what.

Fixes #2296

### CODE REVIEW

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 1]
```diff
@@ -198,7 +213,27 @@ public Runnable start(Listener transportListener) {
      * that it may begin buffering writes.
      */
     b.handler(negotiationHandler);
-    channel = b.register().channel();
+    ChannelFuture regFuture = b.register();
```
Comment (carl-mastrangelo) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: out of curiosity, why not add a listener?  The future could not be resolved by line 220 right?

Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: This is discussed some in the comment below that talks about "we are calling lifecycleManager from the event loop". Basically, I need `statusExplainingWhyTheChannelIsNull` to be computed before `start()` returns, and I feel like adding the listener within the `if (channel == null)` doesn't help much vs what I've done.

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java [hunk 2]
```diff
@@ -163,7 +178,7 @@ public ClientStream newStream(MethodDescriptor<?, ?> method, Metadata headers) {
 
   @SuppressWarnings("unchecked")
   @Override
-  public Runnable start(Listener transportListener) {
+  public Runnable start(final Listener transportListener) {
```
Comment (dapengzhang0) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: final seems not needed

File: netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java [hunk 3]
```diff
@@ -276,6 +278,68 @@ public void bufferedStreamsShouldBeClosedWhenConnectionTerminates() throws Excep
...
+    // Should not throw
+    callMeMaybe(transport.start(clientTransportListener));
+
+    // And RPCs and PINGs should fail cleanly, reporting the failure
+    Rpc rpc = new Rpc(transport);
+    try {
+      rpc.waitForResponse();
+      fail("Expected exception");
+    } catch (Exception ex) {
+      if (!(getRootCause(ex) instanceof CantConstructChannelError)) {
```
Comment (dapengzhang0) [inline netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java]: `assertTrue("Could not find expected error", (getRootCause(ex) instanceof CantConstructChannelError)` rather than `throw new AssertionError`?

ditto for the other

Comment (ejona86) [inline netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java]: I chose the `AssertionError` because it reports what `ex` actually is on failure. Instead of `assertTrue()` that would just say "Could not find expected error".

File: netty/src/main/java/io/grpc/netty/NettyClientTransport.java (hunk 2 above)
Comment (ejona86) [inline netty/src/main/java/io/grpc/netty/NettyClientTransport.java]: Ah, thanks for noticing. Removed.

**Comment by ejona86** [comment]
There was a compilation conflict with master (a constructor changed). I've rebased and fixed the problem. I'll merge once the tests pass.
