### PR TITLE
xds: Fix load reporting when pick first is used for locality-routing.

### LINKED ISSUE #11434: xds: Incorrect load reporting when using pick first as locality-routing policy
ClusterImplLoadBalancer assumes all addresses for a subchannel are in the same locality:
https://github.com/grpc/grpc-java/blob/90d0fabb1f100231ab6544cf8e352c623771dee1/xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java#L216-L217

That is the case when pick_first is being used as an endpoint-picking policy. But when pick_first is being used for affinity cross-locality (instead of ring_hash), that is wrong and can assign the load to the wrong locality.

The PickFirstLeafLoadBalancer doesn't have this problem, because it uses a separate subchannel for each address. But it also is not the default (again).

b/349186137

### PR DESCRIPTION
**Pull request by DNVindhya**
This fixes Incorrect load reporting when using pick first as locality-routing policy.

Cause: ClusterImplLoadBalancer used to assume all the address are in the same locality and used first address in the list of addresses to determine locality. This is not always true leading to incorrect load reporting.

Fix: Get locality from address connected by the subchannel.

Closes #11434.

### CODE REVIEW

File: api/src/main/java/io/grpc/InternalSubchannelAddress.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.grpc;
+
+/**
+ * An internal class. Do not use.
+ *
+ * <p>An interface to provide the address connected by subchannel.
```
Comment (larry-safran) [inline api/src/main/java/io/grpc/InternalSubchannelAddress.java:22]: This says it provides the `address`, but the method provides address attributes.

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java [hunk 2]
```diff
@@ -213,35 +214,43 @@ public void updateBalancingState(ConnectivityState newState, SubchannelPicker ne
...
+              listener.onSubchannelState(newState);
+            }
+          });
+        }
+
         @Override
         public void shutdown() {
-          if (localityStats != null) {
-            localityStats.release();
+          if (localityAtomicReference.get() != null) {
```
Comment (larry-safran) [inline xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:252]: This can't possibly be null AFAICT

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java [hunk 3]
```diff
@@ -274,6 +283,28 @@ private List<EquivalentAddressGroup> withAdditionalAttributes(
...
 
+    private ClusterLocality createClusterLocalityFromAttributes(Attributes addressAttributes) {
+      Locality locality = addressAttributes.get(InternalXdsAttributes.ATTR_LOCALITY);
+      String localityName = addressAttributes.get(InternalXdsAttributes.ATTR_LOCALITY_NAME);
+
+      // Endpoint addresses resolved by ClusterResolverLoadBalancer should always contain
+      // attributes with its locality, including endpoints in LOGICAL_DNS clusters.
+      // In case of not (which really shouldn't), loads are aggregated under an empty
+      // locality.
+      if (locality == null) {
```
Comment (larry-safran) [inline xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:294]: It shouldn't be, but is possible that locality is set but locality name is null.  You should probably have an else clause that does a null check on localityName.

File: xds/src/main/java/io/grpc/xds/client/LoadStatsManager2.java [hunk 4]
```diff
@@ -91,7 +91,7 @@ private synchronized void releaseClusterDropCounter(
       String cluster, @Nullable String edsServiceName) {
     checkState(allDropStats.containsKey(cluster)
             && allDropStats.get(cluster).containsKey(edsServiceName),
-        "stats for cluster %s, edsServiceName %s not exits", cluster, edsServiceName);
+        "stats for cluster %s, edsServiceName %s not exist", cluster, edsServiceName);
```
Comment (larry-safran) [inline xds/src/main/java/io/grpc/xds/client/LoadStatsManager2.java:94]: s/not exist/do not exist/

**Review by larry-safran — APPROVED** [review]
I've recommended a number of minor changes to comments

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java (hunk 3 above)
Comment (ejona86) [reply xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:294]: This is existing code, and it seems in general code assumes the values to be non-null. I'd much rather we handle that centrally in `io.grpc.xds.client.Locality.create()` than lots of random not-possible-to-trigger checks. The data is primarily coming from a proto, so it will be `""` when unset.

Comment (DNVindhya) [reply xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:292]: Are you suggesting to move the locality name null check to `io.grpc.xds.client.Locality.create()`?

Comment (ejona86) [reply xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:292]: Oh, I see now Larry's comment wasn't about the Locality struct, but instead the attribute. That had been discussed when the code was originally introduced:
https://github.com/grpc/grpc-java/pull/11133#discussion_r1586584776

This PR is likely to be reverted (in some way) later, once the old PF policy goes away. So changes to the existing code are likely to be lost.

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java [hunk 5]
```diff
@@ -213,36 +214,42 @@ public void updateBalancingState(ConnectivityState newState, SubchannelPicker ne
...
-      }
-      final ClusterLocalityStats localityStats =
-          (lrsServerInfo == null)
-              ? null
-              : xdsClient.addClusterLocalityStats(lrsServerInfo, cluster,
-              edsServiceName, locality);
-
+      // This clusterLocality ideally should not be utilized. We derive locality
+      // information from the first address, even prior to the subchannel becoming ready.
+      // This is primarily for the purpose of facilitating load reporting in the pre-READY
```
Comment (ejona86) [inline xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:219]: There's no load reporting pre-READY. But an LB API could return the subchannel even before it is ready, and PF does this. We generally won't end up reporting load for such picks because the channel will ignore the selected (not-ready) subchannel, but we needed to handle the case.

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java [hunk 6]
```diff
@@ -362,10 +391,12 @@ public PickResult pickSubchannel(PickSubchannelArgs args) {
             }
           }
           final ClusterLocalityStats stats =
-              result.getSubchannel().getAttributes().get(ATTR_CLUSTER_LOCALITY_STATS);
+              result.getSubchannel().getAttributes().get(ATTR_CLUSTER_LOCALITY).get()
+                  .getClusterLocalityStats();
           if (stats != null) {
```
Comment (ejona86) [inline xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:396]: Before this PR this check was handling the case where a subchannel was used that didn't have ATTR_CLUSTER_LOCALITY_STATS set. Can you preserve that check?

**Review by ejona86 — APPROVED** [review]

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java (hunk 6 above)
Comment (DNVindhya) [reply xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java]: Added the check along with the null check for stats. PTAL

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java [hunk 7]
```diff
@@ -77,10 +79,9 @@ final class ClusterImplLoadBalancer extends LoadBalancer {
       Strings.isNullOrEmpty(System.getenv("GRPC_XDS_EXPERIMENTAL_CIRCUIT_BREAKING"))
           || Boolean.parseBoolean(System.getenv("GRPC_XDS_EXPERIMENTAL_CIRCUIT_BREAKING"));
 
-  private static final Attributes.Key<ClusterLocalityStats> ATTR_CLUSTER_LOCALITY_STATS =
-      Attributes.Key.create("io.grpc.xds.ClusterImplLoadBalancer.clusterLocalityStats");
-  private static final Attributes.Key<String> ATTR_CLUSTER_LOCALITY_NAME =
-      Attributes.Key.create("io.grpc.xds.ClusterImplLoadBalancer.clusterLocalityName");
+  private static final Attributes.Key<AtomicReference<ClusterLocality>>
+      ATTR_CLUSTER_LOCALITY =
```
Comment (larry-safran) [inline xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java:83]: You can put ATTR_CLUSTER_LOCALITY on the same line as the type.

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java (hunk 5 above)
Comment (larry-safran) [reply xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java]: Did you miss pushing the update?

Comment (DNVindhya) [reply xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java]: Discussed offline, we both are able to see the updated comment.

File: xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java (hunk 7 above)
Comment (DNVindhya) [reply xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java]: Done
